;;;; ip.lisp - ARP, IP, UDP, TCP, ICMP, DHCP, DNS (shared, arch-independent)
;;;;
;;;; Requires: e1000.lisp (e1000-send, e1000-receive, e1000-rx-buf)
;;;; Requires arch adapter: io-delay, e1000-state-base

;; Network state layout (relative to e1000-state-base):
;;   +0x00: MMIO base (u64)   +0x08: MAC (6 bytes)
;;   +0x10: RX cursor (u32)   +0x14: TX cursor (u32)
;;   +0x18: Our IP (4 bytes)  +0x1C: Gateway IP (u32)
;;   +0x28: Gateway MAC (6b)  +0x30: TCP state (u32)
;;   +0x34: TCP local port    +0x36: TCP remote port
;;   +0x38: TCP remote IP     +0x3C: TCP local seq
;;   +0x40: TCP ack seq       +0x58: DNS server (u32)
;;   +0x5C: Subnet mask       +0x60: DHCP state
;;   +0x64: DHCP xid          +0x68: DHCP offered IP
;;   +0x6C: DHCP server IP    +0x70: ICMP seq counter
;;   +0x74: UDP src port       +0x76: UDP src IP
;;   +0x7C: UDP data addr      +0x80: UDP data len

;; ================================================================
;; Byte order helpers
;; ================================================================

(defun htons (v)
  (logior (ash (logand v #xFF) 8)
          (logand (ash v -8) #xFF)))

(defun htonl (v)
  (logior (ash (logand v #xFF) 24)
          (logior (ash (logand (ash v -8) #xFF) 16)
                  (logior (ash (logand (ash v -16) #xFF) 8)
                          (logand (ash v -24) #xFF)))))

(defun buf-write-u16 (buf off val)
  (aset buf off (logand (ash val -8) #xFF))
  (aset buf (+ off 1) (logand val #xFF)))

(defun buf-write-u32 (buf off val)
  (aset buf off (logand (ash val -24) #xFF))
  (aset buf (+ off 1) (logand (ash val -16) #xFF))
  (aset buf (+ off 2) (logand (ash val -8) #xFF))
  (aset buf (+ off 3) (logand val #xFF)))

(defun buf-read-u16 (buf off)
  (logior (ash (aref buf off) 8)
          (aref buf (+ off 1))))

(defun buf-read-u32 (buf off)
  (logior (ash (aref buf off) 24)
          (logior (ash (aref buf (+ off 1)) 16)
                  (logior (ash (aref buf (+ off 2)) 8)
                          (aref buf (+ off 3))))))

(defun buf-copy-mac (buf dest-off src-addr)
  (dotimes (i 6)
    (aset buf (+ dest-off i) (mem-ref (+ src-addr i) :u8))))

(defun buf-read-u16-mem (addr off)
  (logior (ash (mem-ref (+ addr off) :u8) 8)
          (mem-ref (+ addr off 1) :u8)))

(defun buf-read-u32-mem (addr off)
  (logior (ash (mem-ref (+ addr off) :u8) 24)
          (logior (ash (mem-ref (+ addr off 1) :u8) 16)
                  (logior (ash (mem-ref (+ addr off 2) :u8) 8)
                          (mem-ref (+ addr off 3) :u8)))))

;; ================================================================
;; Ethernet / ARP
;; ================================================================

(defun eth-set-header (buf dst-mac-addr ethertype)
  (let ((state (e1000-state-base)))
    (dotimes (i 6)
      (aset buf i (mem-ref (+ dst-mac-addr i) :u8)))
    (dotimes (i 6)
      (aset buf (+ 6 i) (mem-ref (+ state #x08 i) :u8)))
    (buf-write-u16 buf 12 ethertype)))

(defun arp-request (target-ip)
  (let ((state (e1000-state-base))
        (pkt (make-array 42)))
    ;; Ethernet: broadcast destination
    (dotimes (i 6) (aset pkt i #xFF))
    ;; Source MAC
    (dotimes (i 6) (aset pkt (+ 6 i) (mem-ref (+ state #x08 i) :u8)))
    ;; Ethertype: ARP = 0x0806
    (aset pkt 12 #x08) (aset pkt 13 #x06)
    ;; ARP header
    (aset pkt 14 0) (aset pkt 15 1)     ; HW type: Ethernet
    (aset pkt 16 #x08) (aset pkt 17 0)  ; Proto: IPv4
    (aset pkt 18 6) (aset pkt 19 4)     ; HW/Proto addr lengths
    (aset pkt 20 0) (aset pkt 21 1)     ; Opcode: request
    ;; Sender MAC
    (dotimes (i 6) (aset pkt (+ 22 i) (mem-ref (+ state #x08 i) :u8)))
    ;; Sender IP
    (let ((our-ip (mem-ref (+ state #x18) :u32)))
      (aset pkt 28 (logand our-ip #xFF))
      (aset pkt 29 (logand (ash our-ip -8) #xFF))
      (aset pkt 30 (logand (ash our-ip -16) #xFF))
      (aset pkt 31 (logand (ash our-ip -24) #xFF)))
    ;; Target MAC: zeros
    (dotimes (i 6) (aset pkt (+ 32 i) 0))
    ;; Target IP
    (let ((tip (htonl target-ip)))
      (aset pkt 38 (logand tip #xFF))
      (aset pkt 39 (logand (ash tip -8) #xFF))
      (aset pkt 40 (logand (ash tip -16) #xFF))
      (aset pkt 41 (logand (ash tip -24) #xFF)))
    (e1000-send pkt 42)))

(defun arp-resolve ()
  (let ((state (e1000-state-base)))
    (arp-request #x0A000202)
    (let ((found 0))
      (dotimes (round 200)
        (when (zerop found)
          (io-delay)
          (let ((pkt-len (e1000-receive)))
            (when (not (zerop pkt-len))
              (let ((buf (e1000-rx-buf)))
                (when (eq (mem-ref (+ buf 12) :u8) #x08)
                  (when (eq (mem-ref (+ buf 13) :u8) #x06)
                    (when (eq (mem-ref (+ buf 21) :u8) 2)
                      (dotimes (i 6)
                        (setf (mem-ref (+ state #x28 i) :u8)
                              (mem-ref (+ buf 22 i) :u8)))
                      (setq found 1)))))))))
      (when (not (zerop found))
        (write-byte 65) (write-byte 82) (write-byte 80) (write-byte 58)
        (write-byte 79) (write-byte 75) (write-byte 10))
      found)))

(defun arp-reply (req-buf)
  (let ((state (e1000-state-base))
        (pkt (make-array 42)))
    ;; Learn sender's MAC as gateway MAC (for ip-send destination)
    (dotimes (i 6)
      (setf (mem-ref (+ state #x28 i) :u8) (mem-ref (+ req-buf 22 i) :u8)))
    (dotimes (i 6) (aset pkt i (mem-ref (+ req-buf 22 i) :u8)))
    (dotimes (i 6) (aset pkt (+ 6 i) (mem-ref (+ state #x08 i) :u8)))
    (aset pkt 12 #x08) (aset pkt 13 #x06)
    (aset pkt 14 0) (aset pkt 15 1)
    (aset pkt 16 #x08) (aset pkt 17 0)
    (aset pkt 18 6) (aset pkt 19 4)
    (aset pkt 20 0) (aset pkt 21 2)     ; reply
    (dotimes (i 6) (aset pkt (+ 22 i) (mem-ref (+ state #x08 i) :u8)))
    (dotimes (i 4) (aset pkt (+ 28 i) (mem-ref (+ state #x18 i) :u8)))
    (dotimes (i 6) (aset pkt (+ 32 i) (mem-ref (+ req-buf 22 i) :u8)))
    (dotimes (i 4) (aset pkt (+ 38 i) (mem-ref (+ req-buf 28 i) :u8)))
    (e1000-send pkt 42)))

;; ================================================================
;; IP
;; ================================================================

(defun ip-checksum (buf start len)
  (let ((sum 0)
        (i 0))
    (dotimes (j (truncate len 2))
      (let ((word (logior (ash (aref buf (+ start i)) 8)
                          (aref buf (+ start i 1)))))
        (setq sum (+ sum word))
        (setq i (+ i 2))))
    (let ((folded (+ (logand sum #xFFFF) (ash sum -16))))
      (logand (logxor folded #xFFFF) #xFFFF))))

(defun ip-send (dst-ip proto payload-buf payload-len)
  (let ((state (e1000-state-base))
        (total-len (+ 20 payload-len))
        (pkt (make-array 1514)))
    ;; Ethernet header: gateway MAC as destination
    (dotimes (i 6) (aset pkt i (mem-ref (+ state #x28 i) :u8)))
    (dotimes (i 6) (aset pkt (+ 6 i) (mem-ref (+ state #x08 i) :u8)))
    (aset pkt 12 #x08) (aset pkt 13 0)
    ;; IP header
    (aset pkt 14 #x45) (aset pkt 15 0)
    (buf-write-u16 pkt 16 total-len)
    (buf-write-u16 pkt 18 0)
    (aset pkt 20 #x40) (aset pkt 21 0)
    (aset pkt 22 64) (aset pkt 23 proto)
    (aset pkt 24 0) (aset pkt 25 0)
    ;; Source IP
    (aset pkt 26 (mem-ref (+ state #x18) :u8))
    (aset pkt 27 (mem-ref (+ state #x19) :u8))
    (aset pkt 28 (mem-ref (+ state #x1A) :u8))
    (aset pkt 29 (mem-ref (+ state #x1B) :u8))
    ;; Destination IP
    (let ((nip (htonl dst-ip)))
      (aset pkt 30 (logand nip #xFF))
      (aset pkt 31 (logand (ash nip -8) #xFF))
      (aset pkt 32 (logand (ash nip -16) #xFF))
      (aset pkt 33 (logand (ash nip -24) #xFF)))
    ;; IP checksum
    (let ((csum (ip-checksum pkt 14 20)))
      (aset pkt 24 (logand (ash csum -8) #xFF))
      (aset pkt 25 (logand csum #xFF)))
    ;; Copy payload
    (dotimes (i payload-len)
      (aset pkt (+ 34 i) (aref payload-buf i)))
    (e1000-send pkt (+ 14 total-len))))

;; ================================================================
;; UDP
;; ================================================================

(defun udp-send (dst-ip dst-port src-port data len)
  (let ((udp-len (+ 8 len))
        (buf (make-array 1480)))
    (buf-write-u16 buf 0 src-port)
    (buf-write-u16 buf 2 dst-port)
    (buf-write-u16 buf 4 udp-len)
    (buf-write-u16 buf 6 0)
    (dotimes (i len)
      (aset buf (+ 8 i) (aref data i)))
    (ip-send dst-ip 17 buf udp-len)))

(defun udp-handle (buf ip-offset)
  (let ((state (e1000-state-base))
        (udp-offset (+ buf ip-offset 20)))
    (setf (mem-ref (+ state #x74) :u16)
          (logior (ash (mem-ref udp-offset :u8) 8)
                  (mem-ref (+ udp-offset 1) :u8)))
    (setf (mem-ref (+ state #x76) :u32)
          (logior (ash (mem-ref (+ buf ip-offset 12) :u8) 24)
                  (logior (ash (mem-ref (+ buf ip-offset 13) :u8) 16)
                          (logior (ash (mem-ref (+ buf ip-offset 14) :u8) 8)
                                  (mem-ref (+ buf ip-offset 15) :u8)))))
    (let ((udp-len (logior (ash (mem-ref (+ udp-offset 4) :u8) 8)
                           (mem-ref (+ udp-offset 5) :u8))))
      (let ((data-len (- udp-len 8)))
        (setf (mem-ref (+ state #x7C) :u32) (+ udp-offset 8))
        (setf (mem-ref (+ state #x80) :u32) data-len)
        data-len))))

(defun udp-receive (timeout)
  (let ((state (e1000-state-base)))
    (setf (mem-ref (+ state #x80) :u32) 0)
    (let ((received 0))
      (dotimes (try timeout)
        (when (zerop received)
          (io-delay)
          (let ((pkt-len (e1000-receive)))
            (when (not (zerop pkt-len))
              (let ((buf (e1000-rx-buf)))
                (when (eq (mem-ref (+ buf 12) :u8) #x08)
                  (when (eq (mem-ref (+ buf 13) :u8) 0)
                    (when (eq (mem-ref (+ buf 23) :u8) 17)
                      (udp-handle buf 14)
                      (setq received (mem-ref (+ state #x80) :u32))))))))))
      received)))

(defun udp-rx-data-ref (index)
  (let ((data-addr (mem-ref (+ (e1000-state-base) #x7C) :u32)))
    (mem-ref (+ data-addr index) :u8)))

;; ================================================================
;; TCP Client
;; ================================================================

(defun tcp-checksum (tcp-buf tcp-len)
  (let ((state (e1000-state-base))
        (sum 0))
    ;; Pseudo-header: src IP
    (setq sum (+ sum (logior (ash (mem-ref (+ state #x18) :u8) 8)
                             (mem-ref (+ state #x19) :u8))))
    (setq sum (+ sum (logior (ash (mem-ref (+ state #x1A) :u8) 8)
                             (mem-ref (+ state #x1B) :u8))))
    ;; Pseudo-header: dst IP
    (let ((dip (mem-ref (+ state #x38) :u32)))
      (setq sum (+ sum (logand (ash dip -16) #xFFFF)))
      (setq sum (+ sum (logand dip #xFFFF))))
    ;; Pseudo-header: zero, proto=6, TCP length
    (setq sum (+ sum 6))
    (setq sum (+ sum tcp-len))
    ;; TCP segment
    (let ((i 0))
      (dotimes (j (truncate tcp-len 2))
        (setq sum (+ sum (logior (ash (aref tcp-buf i) 8)
                                 (aref tcp-buf (+ i 1)))))
        (setq i (+ i 2)))
      (when (not (zerop (mod tcp-len 2)))
        (setq sum (+ sum (ash (aref tcp-buf i) 8)))))
    ;; Fold carry
    (let ((folded (+ (logand sum #xFFFF) (ash sum -16))))
      (let ((folded2 (+ (logand folded #xFFFF) (ash folded -16))))
        (logand (logxor folded2 #xFFFF) #xFFFF)))))

(defun tcp-send-segment (flags data data-len)
  (let ((state (e1000-state-base))
        (tcp-len (+ 20 data-len))
        (seg (make-array 1480)))
    (buf-write-u16 seg 0 (mem-ref (+ state #x34) :u16))
    (buf-write-u16 seg 2 (mem-ref (+ state #x36) :u16))
    (buf-write-u32 seg 4 (mem-ref (+ state #x3C) :u32))
    (buf-write-u32 seg 8 (mem-ref (+ state #x40) :u32))
    (aset seg 12 #x50) (aset seg 13 flags)
    (buf-write-u16 seg 14 8192)
    (aset seg 16 0) (aset seg 17 0)
    (aset seg 18 0) (aset seg 19 0)
    (when (not (zerop data-len))
      (dotimes (i data-len)
        (aset seg (+ 20 i) (aref data i))))
    (let ((csum (tcp-checksum seg tcp-len)))
      (aset seg 16 (logand (ash csum -8) #xFF))
      (aset seg 17 (logand csum #xFF)))
    (if (zerop data-len)
        (when (not (zerop (logand flags 3)))
          (setf (mem-ref (+ state #x3C) :u32)
                (+ (mem-ref (+ state #x3C) :u32) 1)))
        (setf (mem-ref (+ state #x3C) :u32)
              (+ (mem-ref (+ state #x3C) :u32) data-len)))
    (let ((dst-ip (mem-ref (+ state #x38) :u32)))
      (ip-send dst-ip 6 seg tcp-len))))

(defun tcp-connect (dst-ip dst-port)
  (let ((state (e1000-state-base)))
    (setf (mem-ref (+ state #x30) :u32) 1)
    (setf (mem-ref (+ state #x34) :u16) 49152)
    (setf (mem-ref (+ state #x36) :u16) dst-port)
    (setf (mem-ref (+ state #x38) :u32) dst-ip)
    (setf (mem-ref (+ state #x3C) :u32) 1000)
    (setf (mem-ref (+ state #x40) :u32) 0)
    (tcp-send-segment 2 (make-array 0) 0)
    (let ((connected 0))
      (dotimes (try 500)
        (when (zerop connected)
          (io-delay)
          (let ((pkt-len (e1000-receive)))
            (when (not (zerop pkt-len))
              (let ((buf (e1000-rx-buf)))
                (when (eq (mem-ref (+ buf 12) :u8) #x08)
                  (when (eq (mem-ref (+ buf 13) :u8) 0)
                    (when (eq (mem-ref (+ buf 23) :u8) 6)
                      (let ((tcp-flags (mem-ref (+ buf 47) :u8)))
                        (when (eq (logand tcp-flags #x12) #x12)
                          (let ((their-seq (buf-read-u32-mem buf 38)))
                            (setf (mem-ref (+ state #x40) :u32) (+ their-seq 1))
                            (tcp-send-segment 16 (make-array 0) 0)
                            (setf (mem-ref (+ state #x30) :u32) 2)
                            (setq connected 1))))))))))))
      (if (not (zerop connected))
          (progn
            (write-byte 84) (write-byte 67) (write-byte 80) (write-byte 58)
            (write-byte 79) (write-byte 75) (write-byte 10)
            1)
          (progn
            (write-byte 84) (write-byte 67) (write-byte 80) (write-byte 58)
            (write-byte 70) (write-byte 10)
            0)))))

(defun tcp-send (data len)
  (tcp-send-segment 24 data len))

(defun tcp-receive (timeout)
  (let ((state (e1000-state-base))
        (received 0))
    (dotimes (try timeout)
      (when (zerop received)
        (io-delay)
        (let ((pkt-len (e1000-receive)))
          (when (not (zerop pkt-len))
            (let ((buf (e1000-rx-buf)))
              (when (eq (mem-ref (+ buf 12) :u8) #x08)
                (when (eq (mem-ref (+ buf 13) :u8) 0)
                  (when (eq (mem-ref (+ buf 23) :u8) 6)
                    (let ((tcp-flags (mem-ref (+ buf 47) :u8))
                          (ip-total (buf-read-u16-mem buf 16))
                          (tcp-data-off (ash (logand (mem-ref (+ buf 46) :u8) #xF0) -2)))
                      (let ((data-len (- ip-total (+ 20 tcp-data-off))))
                        (when (> data-len 0)
                          (let ((their-seq (buf-read-u32-mem buf 38)))
                            (setf (mem-ref (+ state #x40) :u32) (+ their-seq data-len))
                            (tcp-send-segment 16 (make-array 0) 0)
                            (setq received data-len)))
                        (when (not (zerop (logand tcp-flags 1)))
                          (let ((their-seq (buf-read-u32-mem buf 38)))
                            (setf (mem-ref (+ state #x40) :u32) (+ their-seq 1))
                            (tcp-send-segment 16 (make-array 0) 0)
                            (setf (mem-ref (+ state #x30) :u32) 0)))))))))))))
    received))

(defun tcp-close ()
  (let ((state (e1000-state-base)))
    (tcp-send-segment 17 (make-array 0) 0)
    (setf (mem-ref (+ state #x30) :u32) 0)))

;; ================================================================
;; TCP Server (listen/accept)
;; ================================================================

(defun tcp-listen (port)
  (let ((state (e1000-state-base)))
    (setf (mem-ref (+ state #x30) :u32) 3)
    (setf (mem-ref (+ state #x34) :u16) port)
    (setf (mem-ref (+ state #x36) :u16) 0)
    (setf (mem-ref (+ state #x38) :u32) 0)
    1))

(defun tcp-accept (timeout)
  (let ((state (e1000-state-base))
        (accepted 0))
    (dotimes (try timeout)
      (when (zerop accepted)
        (io-delay)
        (let ((pkt-len (e1000-receive)))
          (when (not (zerop pkt-len))
            (let ((buf (e1000-rx-buf)))
              (when (eq (mem-ref (+ buf 12) :u8) #x08)
                (when (eq (mem-ref (+ buf 13) :u8) 0)
                  (when (eq (mem-ref (+ buf 23) :u8) 6)
                    (let ((tcp-flags (mem-ref (+ buf 47) :u8)))
                      (when (eq (logand tcp-flags #x02) #x02)
                        (let ((their-seq (buf-read-u32-mem buf 38))
                              (their-ip (buf-read-u32-mem buf 26))
                              (their-port (buf-read-u16-mem buf 34)))
                          (setf (mem-ref (+ state #x38) :u32) their-ip)
                          (setf (mem-ref (+ state #x36) :u16) their-port)
                          (setf (mem-ref (+ state #x3C) :u32) 1000)
                          (setf (mem-ref (+ state #x40) :u32) (+ their-seq 1))
                          (tcp-send-segment 18 (make-array 0) 0)
                          ;; Wait for ACK
                          (let ((ack-done 0))
                            (dotimes (d2 500)
                              (when (zerop ack-done)
                                (io-delay)
                                (let ((pkt-len2 (e1000-receive)))
                                  (when (not (zerop pkt-len2))
                                    (let ((b2 (e1000-rx-buf)))
                                      (when (eq (mem-ref (+ b2 12) :u8) #x08)
                                        (when (eq (mem-ref (+ b2 13) :u8) 0)
                                          (when (eq (mem-ref (+ b2 23) :u8) 6)
                                            (let ((f2 (mem-ref (+ b2 47) :u8)))
                                              (when (eq (logand f2 #x10) #x10)
                                                (setf (mem-ref (+ state #x30) :u32) 2)
                                                (setq ack-done 1)
                                                (setq accepted 1)))))))))))))))))))))))
    (if (not (zerop accepted))
        (progn
          (write-byte 76) (write-byte 79) (write-byte 75) (write-byte 10)
          1)
        (progn
          (write-byte 76) (write-byte 70) (write-byte 10)
          0))))

;; ================================================================
;; Multi-Connection TCP (for SSH server)
;; ================================================================

(defun conn-base (conn)
  (+ (ssh-conn-base) (ash conn 14)))

(defun conn-ssh (conn)
  (+ (conn-base conn) #x20))

(defun conn-alloc ()
  (let ((i 0) (found 0))
    (loop
      (when (>= i 4) (return (- 0 1)))
      (when (zerop found)
        (when (zerop (mem-ref (conn-base i) :u32))
          (setq found 1)
          (return i)))
      (setq i (+ i 1)))))

(defun conn-free (conn)
  (setf (mem-ref (conn-base conn) :u32) 0))

(defun conn-init (conn local-port remote-port remote-ip)
  (let ((cb (conn-base conn)))
    (setf (mem-ref cb :u32) 2)
    (setf (mem-ref (+ cb #x004) :u32) local-port)
    (setf (mem-ref (+ cb #x008) :u32) remote-port)
    (setf (mem-ref (+ cb #x00C) :u32) remote-ip)
    (setf (mem-ref (+ cb #x010) :u32) 1000)
    (setf (mem-ref (+ cb #x014) :u32) 0)
    (setf (mem-ref (+ cb #x018) :u32) 0)))

(defun tcp-checksum-conn (cb tcp-buf tcp-len)
  (let ((state (e1000-state-base))
        (sum 0))
    (setq sum (+ sum (logior (ash (mem-ref (+ state #x18) :u8) 8)
                             (mem-ref (+ state #x19) :u8))))
    (setq sum (+ sum (logior (ash (mem-ref (+ state #x1A) :u8) 8)
                             (mem-ref (+ state #x1B) :u8))))
    (let ((dip (mem-ref (+ cb #x00C) :u32)))
      (setq sum (+ sum (logand (ash dip -16) #xFFFF)))
      (setq sum (+ sum (logand dip #xFFFF))))
    (setq sum (+ sum 6))
    (setq sum (+ sum tcp-len))
    (let ((i 0))
      (dotimes (j (truncate tcp-len 2))
        (setq sum (+ sum (logior (ash (aref tcp-buf i) 8)
                                 (aref tcp-buf (+ i 1)))))
        (setq i (+ i 2)))
      (when (not (zerop (mod tcp-len 2)))
        (setq sum (+ sum (ash (aref tcp-buf i) 8)))))
    (let ((folded (+ (logand sum #xFFFF) (ash sum -16))))
      (let ((folded2 (+ (logand folded #xFFFF) (ash folded -16))))
        (logand (logxor folded2 #xFFFF) #xFFFF)))))

(defun tcp-send-segment-conn (cb flags data data-len)
  (let ((tcp-len (+ 20 data-len))
        (seg (make-array 1480)))
    (buf-write-u16 seg 0 (mem-ref (+ cb #x004) :u32))
    (buf-write-u16 seg 2 (mem-ref (+ cb #x008) :u32))
    (buf-write-u32 seg 4 (mem-ref (+ cb #x010) :u32))
    (buf-write-u32 seg 8 (mem-ref (+ cb #x014) :u32))
    (aset seg 12 #x50) (aset seg 13 flags)
    (buf-write-u16 seg 14 8192)
    (aset seg 16 0) (aset seg 17 0)
    (aset seg 18 0) (aset seg 19 0)
    (when (not (zerop data-len))
      (dotimes (i data-len)
        (aset seg (+ 20 i) (aref data i))))
    (let ((csum (tcp-checksum-conn cb seg tcp-len)))
      (aset seg 16 (logand (ash csum -8) #xFF))
      (aset seg 17 (logand csum #xFF)))
    (if (zerop data-len)
        (when (not (zerop (logand flags 3)))
          (setf (mem-ref (+ cb #x010) :u32)
                (+ (mem-ref (+ cb #x010) :u32) 1)))
        (setf (mem-ref (+ cb #x010) :u32)
              (+ (mem-ref (+ cb #x010) :u32) data-len)))
    (let ((dst-ip (mem-ref (+ cb #x00C) :u32)))
      (spin-lock (+ (ssh-ipc-base) #x60430))
      (ip-send dst-ip 6 seg tcp-len)
      (spin-unlock (+ (ssh-ipc-base) #x60430)))))

(defun tcp-send-conn (cb data len)
  (tcp-send-segment-conn cb 24 data len))

(defun tcp-ack-conn (cb)
  (tcp-send-segment-conn cb 16 (make-array 0) 0))

(defun tcp-close-conn (cb)
  (tcp-send-segment-conn cb 17 (make-array 0) 0)
  (setf (mem-ref cb :u32) 0))

(defun net-find-connection (src-ip src-port dst-port)
  (let ((i 0)
        (found (- 0 1)))
    (loop
      (when (>= i 4) (return found))
      (let ((cb (conn-base i)))
        (when (not (zerop (mem-ref cb :u32)))
          (when (eq (mem-ref (+ cb #x00C) :u32) src-ip)
            (when (eq (mem-ref (+ cb #x008) :u32) src-port)
              (when (eq (mem-ref (+ cb #x004) :u32) dst-port)
                (setq found i)
                (return found))))))
      (setq i (+ i 1)))))

(defun net-deliver-data (conn buf pkt-len tcp-flags)
  (let ((cb (conn-base conn))
        (ssh (conn-ssh conn)))
    (let ((ip-total (buf-read-u16-mem buf 16))
          (tcp-data-off (ash (logand (mem-ref (+ buf 46) :u8) #xF0) -2)))
      (let ((data-len (- ip-total (+ 20 tcp-data-off))))
        (when (> data-len 0)
          (let ((their-seq (buf-read-u32-mem buf 38)))
            (setf (mem-ref (+ cb #x014) :u32) (+ their-seq data-len))
            (tcp-ack-conn cb))
          (let ((buf-len (mem-ref (+ ssh #x6D4) :u32))
                (data-start (+ (+ (+ buf 14) 20) tcp-data-off)))
            (let ((i 0))
              (loop
                (when (>= i data-len) (return 0))
                (setf (mem-ref (+ (+ (+ ssh #x6D8) buf-len) i) :u8)
                      (mem-ref (+ data-start i) :u8))
                (setq i (+ i 1))))
            (setf (mem-ref (+ ssh #x6D4) :u32) (+ buf-len data-len))))))))

(defun net-wait-ack (conn)
  (let ((cb (conn-base conn))
        (acked 0)
        (tries 0))
    (loop
      (when (not (zerop acked)) (return 1))
      (when (> tries 500) (return 0))
      (io-delay)
      (let ((pkt-len (e1000-receive)))
        (when (not (zerop pkt-len))
          (let ((b2 (e1000-rx-buf)))
            (when (eq (mem-ref (+ b2 12) :u8) #x08)
              (when (eq (mem-ref (+ b2 13) :u8) 0)
                (when (eq (mem-ref (+ b2 23) :u8) 6)
                  (let ((f2 (mem-ref (+ b2 47) :u8)))
                    (when (eq (logand f2 #x10) #x10)
                      (setf (mem-ref cb :u32) 2)
                      (setq acked 1)))))))))
      (setq tries (+ tries 1)))))

(defun ssh-copy-host-key (conn)
  (let ((state (e1000-state-base))
        (ssh (conn-ssh conn)))
    ;; Copy private key (32 bytes) from global state+0x710 to ssh+0x110
    (let ((i 0))
      (loop
        (when (>= i 32) (return 0))
        (setf (mem-ref (+ ssh #x110 i) :u8) (mem-ref (+ state #x710 i) :u8))
        (setq i (+ i 1))))
    ;; Copy public key (32 bytes) from global state+0x730 to ssh+0x130
    (let ((i 0))
      (loop
        (when (>= i 32) (return 0))
        (setf (mem-ref (+ ssh #x130 i) :u8) (mem-ref (+ state #x730 i) :u8))
        (setq i (+ i 1))))
    (setf (mem-ref (+ ssh #x24) :u32) 1)))

(defun net-accept-connection (src-ip src-port dst-port buf)
  (let ((conn (conn-alloc)))
    (when (not (= conn (- 0 1)))
      (conn-init conn dst-port src-port src-ip)
      (let ((their-seq (buf-read-u32-mem buf 38)))
        (setf (mem-ref (+ (conn-base conn) #x014) :u32) (+ their-seq 1)))
      (tcp-send-segment-conn (conn-base conn) 18 (make-array 0) 0)
      (net-wait-ack conn)
      (when (eq (mem-ref (conn-base conn) :u32) 2)
        (ssh-copy-host-key conn)
        (let ((ssh (conn-ssh conn)))
          (setf (mem-ref ssh :u32) 0)
          (setf (mem-ref (+ ssh #x04) :u32) 0)
          (setf (mem-ref (+ ssh #x08) :u32) 0)
          (setf (mem-ref (+ ssh #x0C) :u32) 0)
          (setf (mem-ref (+ ssh #x10) :u32) 0)
          (setf (mem-ref (+ ssh #x6D4) :u32) 0)
          (setf (mem-ref (+ ssh #x28) :u32) 0)
          (setf (mem-ref (+ ssh #x150) :u32) 0)
          (setf (mem-ref (+ ssh #x154) :u32) 0)
          (setf (mem-ref (+ ssh #x2C) :u32)
                (+ src-port (* src-ip 7))))
        (setf (mem-ref (+ (+ (ssh-ipc-base) #x60448) (ash conn 3)) :u32) conn)
        (let ((handler-id (actor-spawn (nfn-lookup (conn-handler-fn conn)))))
          (setf (mem-ref (+ (conn-base conn) #x018) :u32) handler-id))))))

(defun conn-handler-fn (conn)
  (if (eq conn 0) (hash-of "ssh-handler-0")
      (if (eq conn 1) (hash-of "ssh-handler-1")
          (if (eq conn 2) (hash-of "ssh-handler-2")
              (hash-of "ssh-handler-3")))))

(defun ssh-connection-handler (conn)
  (let ((ssh (conn-ssh conn))
        (cb (conn-base conn)))
    (ssh-handle-connection ssh)
    (tcp-close-conn cb)
    (conn-free conn)
    (actor-exit)))

(defun ssh-handler-0 () (ssh-connection-handler 0))
(defun ssh-handler-1 () (ssh-connection-handler 1))
(defun ssh-handler-2 () (ssh-connection-handler 2))
(defun ssh-handler-3 () (ssh-connection-handler 3))

(defun net-handle-tcp (buf pkt-len)
  (let ((src-ip (buf-read-u32-mem buf 26))
        (src-port (buf-read-u16-mem buf 34))
        (dst-port (buf-read-u16-mem buf 36))
        (tcp-flags (mem-ref (+ buf 47) :u8)))
    (if (eq (logand tcp-flags #x12) #x02)
        ;; SYN: accept on SSH port or HTTP port (80)
        (if (eq dst-port (mem-ref (+ (ssh-ipc-base) #x60438) :u32))
            (net-accept-connection src-ip src-port dst-port buf)
            (when (eq dst-port 80)
              (net-accept-connection src-ip src-port dst-port buf)))
        (let ((conn (net-find-connection src-ip src-port dst-port)))
          (when (not (= conn (- 0 1)))
            (net-deliver-data conn buf pkt-len tcp-flags))))))

(defun net-actor-main ()
  (loop
    (io-delay)
    (let ((pkt-len (e1000-receive)))
      (if (zerop pkt-len)
          (yield)
          (let ((buf (e1000-rx-buf)))
            (let ((et-hi (mem-ref (+ buf 12) :u8))
                  (et-lo (mem-ref (+ buf 13) :u8)))
              (if (eq et-hi #x08)
                  (if (eq et-lo #x06)
                      (let ((arp-op (buf-read-u16-mem buf 20)))
                        (when (eq arp-op 1)
                          (arp-reply buf)))
                      (when (eq et-lo 0)
                        ;; Learn source MAC as gateway MAC (fixes broadcast dst on real hardware)
                        (let ((st (e1000-state-base)))
                          (dotimes (m 6)
                            (setf (mem-ref (+ st (+ #x28 m)) :u8)
                                  (mem-ref (+ buf (+ 6 m)) :u8))))
                        (let ((proto (mem-ref (+ buf 23) :u8)))
                          (if (eq proto 1)
                              (icmp-handle buf 14)
                              (when (eq proto 6)
                                (net-handle-tcp buf pkt-len))))))
                  ())))))))

;; ================================================================
;; High-level networking
;; ================================================================

(defun net-init ()
  (e1000-probe)
  (arp-resolve))

(defun net-state ()
  (let ((state (e1000-state-base)))
    (write-byte 73) (write-byte 80) (write-byte 58)
    (print-dec (mem-ref (+ state #x18) :u8))
    (write-byte 46)
    (print-dec (mem-ref (+ state #x19) :u8))
    (write-byte 46)
    (print-dec (mem-ref (+ state #x1A) :u8))
    (write-byte 46)
    (print-dec (mem-ref (+ state #x1B) :u8))
    (write-byte 10)
    (write-byte 71) (write-byte 87) (write-byte 58)
    (print-hex-byte (mem-ref (+ state #x28) :u8))
    (dotimes (i 5)
      (write-byte 58)
      (print-hex-byte (mem-ref (+ state #x29 i) :u8)))
    (write-byte 10)
    (write-byte 77) (write-byte 77) (write-byte 58)
    (dotimes (i 8)
      (print-hex-byte (mem-ref (+ state i) :u8)))
    (write-byte 10)
    (write-byte 84) (write-byte 67) (write-byte 58)
    (print-dec (e1000-read-reg #x400))
    (write-byte 10)
    (write-byte 83) (write-byte 84) (write-byte 58)
    (print-dec (e1000-read-reg 8))
    (write-byte 10)
    (write-byte 82) (write-byte 72) (write-byte 58)
    (print-dec (e1000-read-reg #x2810))
    (write-byte 10)
    (write-byte 82) (write-byte 84) (write-byte 58)
    (print-dec (e1000-read-reg #x2818))
    (write-byte 10)
    (write-byte 82) (write-byte 67) (write-byte 58)
    (print-dec (e1000-read-reg #x100))
    (write-byte 10)))

(defun tcp-test-send ()
  (let ((buf (make-array 4)))
    (aset buf 0 72) (aset buf 1 105) (aset buf 2 33) (aset buf 3 10)
    (tcp-send buf 4)))

(defun http-test (dst-ip dst-port)
  (tcp-connect dst-ip dst-port)
  (let ((req (make-array 18)))
    (aset req 0 71) (aset req 1 69) (aset req 2 84) (aset req 3 32)
    (aset req 4 47) (aset req 5 32) (aset req 6 72) (aset req 7 84)
    (aset req 8 84) (aset req 9 80) (aset req 10 47) (aset req 11 49)
    (aset req 12 46) (aset req 13 48) (aset req 14 13) (aset req 15 10)
    (aset req 16 13) (aset req 17 10)
    (tcp-send req 18)
    (let ((n (tcp-receive 500)))
      (if (> n 0)
          (progn
            (write-byte 82) (write-byte 88) (write-byte 58) (print-dec n) (write-byte 10)
            (tcp-close)
            n)
          (progn
            (write-byte 82) (write-byte 88) (write-byte 58)
            (write-byte 78) (write-byte 79) (write-byte 10)
            0)))))

(defun tcp-echo-test ()
  (tcp-listen 7)
  (tcp-accept 5000)
  (let ((data-len (tcp-receive 3000)))
    (when (> data-len 0)
      (let ((buf (make-array data-len))
            (rx (e1000-rx-buf)))
        (dotimes (i data-len)
          (aset buf i (mem-ref (+ rx 54 i) :u8)))
        (tcp-send buf data-len)))
    (tcp-close)))

;; ================================================================
;; ICMP
;; ================================================================

(defun icmp-checksum (buf start len)
  (let ((sum 0) (i 0))
    (dotimes (j (truncate len 2))
      (let ((word (logior (ash (aref buf (+ start i)) 8)
                          (aref buf (+ start i 1)))))
        (setq sum (+ sum word))
        (setq i (+ i 2))))
    (when (not (zerop (mod len 2)))
      (setq sum (+ sum (ash (aref buf (+ start i)) 8))))
    (let ((folded (+ (logand sum #xFFFF) (ash sum -16))))
      (let ((folded2 (+ (logand folded #xFFFF) (ash folded -16))))
        (logand (logxor folded2 #xFFFF) #xFFFF)))))

(defun icmp-handle (buf ip-offset)
  (let ((state (e1000-state-base))
        (icmp-offset (+ buf ip-offset 20)))
    (let ((icmp-type (mem-ref icmp-offset :u8)))
      (if (eq icmp-type 8)
          (let ((ip-total (buf-read-u16-mem buf (+ ip-offset 2)))
                (pkt (make-array 1514)))
            (dotimes (i 6) (aset pkt i (mem-ref (+ buf 6 i) :u8)))
            (dotimes (i 6) (aset pkt (+ 6 i) (mem-ref (+ state #x08 i) :u8)))
            (aset pkt 12 #x08) (aset pkt 13 0)
            (dotimes (i 20)
              (aset pkt (+ 14 i) (mem-ref (+ buf ip-offset i) :u8)))
            (dotimes (i 4)
              (let ((tmp (aref pkt (+ 26 i))))
                (aset pkt (+ 26 i) (aref pkt (+ 30 i)))
                (aset pkt (+ 30 i) tmp)))
            (aset pkt 24 0) (aset pkt 25 0)
            (let ((ipcsum (ip-checksum pkt 14 20)))
              (aset pkt 24 (logand (ash ipcsum -8) #xFF))
              (aset pkt 25 (logand ipcsum #xFF)))
            (let ((icmp-len (- ip-total 20)))
              (dotimes (i icmp-len)
                (aset pkt (+ 34 i) (mem-ref (+ icmp-offset i) :u8)))
              (aset pkt 34 0)
              (aset pkt 36 0) (aset pkt 37 0)
              (let ((icsum (icmp-checksum pkt 34 icmp-len)))
                (aset pkt 36 (logand (ash icsum -8) #xFF))
                (aset pkt 37 (logand icsum #xFF)))
              (e1000-send pkt (+ 14 ip-total))))
          (when (eq icmp-type 0)
            (write-byte 80) (write-byte 111) (write-byte 110)
            (write-byte 103) (write-byte 58)
            (print-dec (mem-ref (+ buf ip-offset 12) :u8))
            (write-byte 46)
            (print-dec (mem-ref (+ buf ip-offset 13) :u8))
            (write-byte 46)
            (print-dec (mem-ref (+ buf ip-offset 14) :u8))
            (write-byte 46)
            (print-dec (mem-ref (+ buf ip-offset 15) :u8))
            (write-byte 10))))))

(defun ping (dst-ip)
  (let ((state (e1000-state-base))
        (icmp-buf (make-array 64)))
    (aset icmp-buf 0 8) (aset icmp-buf 1 0)
    (aset icmp-buf 2 0) (aset icmp-buf 3 0)
    (aset icmp-buf 4 0) (aset icmp-buf 5 1)
    (let ((seq (mem-ref (+ state #x70) :u16)))
      (aset icmp-buf 6 (logand (ash seq -8) #xFF))
      (aset icmp-buf 7 (logand seq #xFF))
      (setf (mem-ref (+ state #x70) :u16) (+ seq 1)))
    (dotimes (i 56)
      (aset icmp-buf (+ 8 i) (logand i #xFF)))
    (let ((csum (icmp-checksum icmp-buf 0 64)))
      (aset icmp-buf 2 (logand (ash csum -8) #xFF))
      (aset icmp-buf 3 (logand csum #xFF)))
    (ip-send dst-ip 1 icmp-buf 64))
  (let ((got-reply 0))
    (dotimes (try 300)
      (when (zerop got-reply)
        (io-delay)
        (let ((pkt-len (e1000-receive)))
          (when (not (zerop pkt-len))
            (let ((buf (e1000-rx-buf)))
              (when (eq (mem-ref (+ buf 12) :u8) #x08)
                (when (eq (mem-ref (+ buf 13) :u8) 0)
                  (when (eq (mem-ref (+ buf 23) :u8) 1)
                    (when (eq (mem-ref (+ buf 34) :u8) 0)
                      (write-byte 80) (write-byte 111) (write-byte 110)
                      (write-byte 103) (write-byte 58)
                      (print-dec (mem-ref (+ buf 26) :u8))
                      (write-byte 46)
                      (print-dec (mem-ref (+ buf 27) :u8))
                      (write-byte 46)
                      (print-dec (mem-ref (+ buf 28) :u8))
                      (write-byte 46)
                      (print-dec (mem-ref (+ buf 29) :u8))
                      (write-byte 10)
                      (setq got-reply 1))))))))))
    got-reply))

(defun ping-test ()
  (ping 167772674))

;; ================================================================
;; Net receive (single dispatch)
;; ================================================================

(defun net-receive ()
  (let ((state (e1000-state-base))
        (pkt-len (e1000-receive)))
    (if (zerop pkt-len)
        0
        (let ((buf (e1000-rx-buf)))
          (let ((et-hi (mem-ref (+ buf 12) :u8))
                (et-lo (mem-ref (+ buf 13) :u8)))
            (if (eq et-hi #x08)
                (if (eq et-lo #x06)
                    (progn
                      (when (eq (mem-ref (+ buf 21) :u8) 2)
                        (dotimes (i 6)
                          (setf (mem-ref (+ state #x28 i) :u8)
                                (mem-ref (+ buf 22 i) :u8))))
                      (when (eq (mem-ref (+ buf 21) :u8) 1)
                        (let ((match 1))
                          (dotimes (i 4)
                            (unless (eq (mem-ref (+ buf 38 i) :u8)
                                        (mem-ref (+ state #x18 i) :u8))
                              (setq match 0)))
                          (when (not (zerop match))
                            (arp-reply buf))))
                      0)
                    (if (zerop et-lo)
                        (let ((ip-proto (mem-ref (+ buf 23) :u8))
                              (ip-total (buf-read-u16-mem buf 16)))
                          (if (eq ip-proto 1)
                              (progn (icmp-handle buf 14) 0)
                              (if (eq ip-proto 17)
                                  (progn (udp-handle buf 14) 0)
                                  (- ip-total 20))))
                        0))
                0))))))

;; ================================================================
;; DHCP Client
;; ================================================================

(defun ip-send-broadcast (proto payload-buf payload-len)
  (let ((state (e1000-state-base))
        (total-len (+ 20 payload-len))
        (pkt (make-array 1514)))
    (dotimes (i 6) (aset pkt i #xFF))
    (dotimes (i 6) (aset pkt (+ 6 i) (mem-ref (+ state #x08 i) :u8)))
    (aset pkt 12 #x08) (aset pkt 13 0)
    (aset pkt 14 #x45) (aset pkt 15 0)
    (buf-write-u16 pkt 16 total-len)
    (buf-write-u16 pkt 18 0)
    (aset pkt 20 0) (aset pkt 21 0)
    (aset pkt 22 64) (aset pkt 23 proto)
    (aset pkt 24 0) (aset pkt 25 0)
    (aset pkt 26 0) (aset pkt 27 0) (aset pkt 28 0) (aset pkt 29 0)
    (aset pkt 30 255) (aset pkt 31 255) (aset pkt 32 255) (aset pkt 33 255)
    (let ((csum (ip-checksum pkt 14 20)))
      (aset pkt 24 (logand (ash csum -8) #xFF))
      (aset pkt 25 (logand csum #xFF)))
    (dotimes (i payload-len)
      (aset pkt (+ 34 i) (aref payload-buf i)))
    (e1000-send pkt (+ 14 total-len))))

(defun udp-send-broadcast (dst-port src-port data len)
  (let ((udp-len (+ 8 len))
        (buf (make-array 1480)))
    (buf-write-u16 buf 0 src-port)
    (buf-write-u16 buf 2 dst-port)
    (buf-write-u16 buf 4 udp-len)
    (buf-write-u16 buf 6 0)
    (dotimes (i len) (aset buf (+ 8 i) (aref data i)))
    (ip-send-broadcast 17 buf udp-len)))

(defun dhcp-discover ()
  (let ((state (e1000-state-base))
        (pkt (make-array 300)))
    (aset pkt 0 1) (aset pkt 1 1) (aset pkt 2 6) (aset pkt 3 0)
    (aset pkt 4 #x12) (aset pkt 5 #x34) (aset pkt 6 #x56) (aset pkt 7 #x78)
    (setf (mem-ref (+ state #x64) :u32) #x12345678)
    (aset pkt 8 0) (aset pkt 9 0)
    (aset pkt 10 #x80) (aset pkt 11 0)
    (dotimes (i 4) (aset pkt (+ 12 i) 0))
    (dotimes (i 4) (aset pkt (+ 16 i) 0))
    (dotimes (i 4) (aset pkt (+ 20 i) 0))
    (dotimes (i 4) (aset pkt (+ 24 i) 0))
    (dotimes (i 6) (aset pkt (+ 28 i) (mem-ref (+ state #x08 i) :u8)))
    (dotimes (i 10) (aset pkt (+ 34 i) 0))
    (dotimes (i 64) (aset pkt (+ 44 i) 0))
    (dotimes (i 128) (aset pkt (+ 108 i) 0))
    (aset pkt 236 99) (aset pkt 237 130) (aset pkt 238 83) (aset pkt 239 99)
    (aset pkt 240 53) (aset pkt 241 1) (aset pkt 242 1)
    (aset pkt 243 55) (aset pkt 244 3)
    (aset pkt 245 1) (aset pkt 246 3) (aset pkt 247 6)
    (aset pkt 248 255)
    (setf (mem-ref (+ state #x60) :u32) 1)
    (udp-send-broadcast 67 68 pkt 249)))

(defun dhcp-request (offered-ip server-ip)
  (let ((state (e1000-state-base))
        (pkt (make-array 300)))
    (aset pkt 0 1) (aset pkt 1 1) (aset pkt 2 6) (aset pkt 3 0)
    (aset pkt 4 #x12) (aset pkt 5 #x34) (aset pkt 6 #x56) (aset pkt 7 #x78)
    (aset pkt 8 0) (aset pkt 9 0) (aset pkt 10 #x80) (aset pkt 11 0)
    (dotimes (i 16) (aset pkt (+ 12 i) 0))
    (dotimes (i 6) (aset pkt (+ 28 i) (mem-ref (+ state #x08 i) :u8)))
    (dotimes (i 10) (aset pkt (+ 34 i) 0))
    (dotimes (i 192) (aset pkt (+ 44 i) 0))
    (aset pkt 236 99) (aset pkt 237 130) (aset pkt 238 83) (aset pkt 239 99)
    (aset pkt 240 53) (aset pkt 241 1) (aset pkt 242 3)
    (aset pkt 243 50) (aset pkt 244 4)
    (aset pkt 245 (logand (ash offered-ip -24) #xFF))
    (aset pkt 246 (logand (ash offered-ip -16) #xFF))
    (aset pkt 247 (logand (ash offered-ip -8) #xFF))
    (aset pkt 248 (logand offered-ip #xFF))
    (aset pkt 249 54) (aset pkt 250 4)
    (aset pkt 251 (logand (ash server-ip -24) #xFF))
    (aset pkt 252 (logand (ash server-ip -16) #xFF))
    (aset pkt 253 (logand (ash server-ip -8) #xFF))
    (aset pkt 254 (logand server-ip #xFF))
    (aset pkt 255 255)
    (setf (mem-ref (+ state #x60) :u32) 2)
    (udp-send-broadcast 67 68 pkt 256)))

(defun dhcp-parse-offer ()
  (let ((state (e1000-state-base))
        (data-addr (mem-ref (+ (e1000-state-base) #x7C) :u32))
        (data-len (mem-ref (+ (e1000-state-base) #x80) :u32)))
    (let ((yiaddr (logior (ash (mem-ref (+ data-addr 16) :u8) 24)
                          (logior (ash (mem-ref (+ data-addr 17) :u8) 16)
                                  (logior (ash (mem-ref (+ data-addr 18) :u8) 8)
                                          (mem-ref (+ data-addr 19) :u8))))))
      (setf (mem-ref (+ state #x68) :u32) yiaddr)
      (let ((opt-offset 240) (done 0))
        (dotimes (iter 50)
          (when (zerop done)
            (when (< opt-offset data-len)
              (let ((opt-type (mem-ref (+ data-addr opt-offset) :u8)))
                (if (eq opt-type 255)
                    (setq done 1)
                    (if (eq opt-type 0)
                        (setq opt-offset (+ opt-offset 1))
                        (let ((opt-len (mem-ref (+ data-addr opt-offset 1) :u8)))
                          (when (eq opt-type 1)
                            (setf (mem-ref (+ state #x5C) :u32)
                                  (logior (ash (mem-ref (+ data-addr opt-offset 2) :u8) 24)
                                          (logior (ash (mem-ref (+ data-addr opt-offset 3) :u8) 16)
                                                  (logior (ash (mem-ref (+ data-addr opt-offset 4) :u8) 8)
                                                          (mem-ref (+ data-addr opt-offset 5) :u8))))))
                          (when (eq opt-type 3)
                            (setf (mem-ref (+ state #x1C) :u32)
                                  (logior (ash (mem-ref (+ data-addr opt-offset 2) :u8) 24)
                                          (logior (ash (mem-ref (+ data-addr opt-offset 3) :u8) 16)
                                                  (logior (ash (mem-ref (+ data-addr opt-offset 4) :u8) 8)
                                                          (mem-ref (+ data-addr opt-offset 5) :u8))))))
                          (when (eq opt-type 6)
                            (setf (mem-ref (+ state #x58) :u32)
                                  (logior (ash (mem-ref (+ data-addr opt-offset 2) :u8) 24)
                                          (logior (ash (mem-ref (+ data-addr opt-offset 3) :u8) 16)
                                                  (logior (ash (mem-ref (+ data-addr opt-offset 4) :u8) 8)
                                                          (mem-ref (+ data-addr opt-offset 5) :u8))))))
                          (when (eq opt-type 54)
                            (setf (mem-ref (+ state #x6C) :u32)
                                  (logior (ash (mem-ref (+ data-addr opt-offset 2) :u8) 24)
                                          (logior (ash (mem-ref (+ data-addr opt-offset 3) :u8) 16)
                                                  (logior (ash (mem-ref (+ data-addr opt-offset 4) :u8) 8)
                                                          (mem-ref (+ data-addr opt-offset 5) :u8))))))
                          (setq opt-offset (+ opt-offset 2 opt-len))))))))))
      yiaddr)))

(defun dhcp-client ()
  (let ((state (e1000-state-base)))
    (dhcp-discover)
    (write-byte 68) (write-byte 72) (write-byte 67) (write-byte 80) (write-byte 58)
    (write-byte 68) (write-byte 10)
    (let ((got-offer 0))
      (dotimes (try 500)
        (when (zerop got-offer)
          (io-delay)
          (let ((pkt-len (e1000-receive)))
            (when (not (zerop pkt-len))
              (let ((buf (e1000-rx-buf)))
                (when (eq (mem-ref (+ buf 12) :u8) #x08)
                  (when (eq (mem-ref (+ buf 13) :u8) 0)
                    (when (eq (mem-ref (+ buf 23) :u8) 17)
                      (let ((src-port (logior (ash (mem-ref (+ buf 34) :u8) 8)
                                              (mem-ref (+ buf 35) :u8))))
                        (when (eq src-port 67)
                          (udp-handle buf 14)
                          (let ((data-addr (mem-ref (+ state #x7C) :u32)))
                            (when (eq (mem-ref data-addr :u8) 2)
                              (when (eq (mem-ref (+ data-addr 236) :u8) 99)
                                (let ((offered (dhcp-parse-offer)))
                                  (when (not (zerop offered))
                                    (setq got-offer 1))))))))))))))))
      (if (zerop got-offer)
          (progn
            (write-byte 68) (write-byte 72) (write-byte 67) (write-byte 80) (write-byte 58)
            (write-byte 70) (write-byte 10)
            0)
          (let ((offered-ip (mem-ref (+ state #x68) :u32))
                (server-ip (mem-ref (+ state #x6C) :u32)))
            (dhcp-request offered-ip server-ip)
            (write-byte 68) (write-byte 72) (write-byte 67) (write-byte 80) (write-byte 58)
            (write-byte 82) (write-byte 10)
            (let ((got-ack 0))
              (dotimes (try 500)
                (when (zerop got-ack)
                  (io-delay)
                  (let ((pkt-len (e1000-receive)))
                    (when (not (zerop pkt-len))
                      (let ((buf (e1000-rx-buf)))
                        (when (eq (mem-ref (+ buf 12) :u8) #x08)
                          (when (eq (mem-ref (+ buf 13) :u8) 0)
                            (when (eq (mem-ref (+ buf 23) :u8) 17)
                              (let ((src-port (logior (ash (mem-ref (+ buf 34) :u8) 8)
                                                      (mem-ref (+ buf 35) :u8))))
                                (when (eq src-port 67)
                                  (udp-handle buf 14)
                                  (let ((data-addr (mem-ref (+ state #x7C) :u32)))
                                    (when (eq (mem-ref data-addr :u8) 2)
                                      (when (eq (mem-ref (+ data-addr 236) :u8) 99)
                                        (dhcp-parse-offer)
                                        (setq got-ack 1))))))))))))))
              (if (zerop got-ack)
                  (progn
                    (write-byte 68) (write-byte 72) (write-byte 67) (write-byte 80) (write-byte 58)
                    (write-byte 70) (write-byte 10)
                    0)
                  (progn
                    (let ((ip (mem-ref (+ state #x68) :u32)))
                      (setf (mem-ref (+ state #x18) :u8) (logand (ash ip -24) #xFF))
                      (setf (mem-ref (+ state #x19) :u8) (logand (ash ip -16) #xFF))
                      (setf (mem-ref (+ state #x1A) :u8) (logand (ash ip -8) #xFF))
                      (setf (mem-ref (+ state #x1B) :u8) (logand ip #xFF)))
                    (setf (mem-ref (+ state #x60) :u32) 3)
                    (write-byte 68) (write-byte 72) (write-byte 67) (write-byte 80)
                    (write-byte 58) (write-byte 73) (write-byte 80) (write-byte 61)
                    (print-dec (mem-ref (+ state #x18) :u8))
                    (write-byte 46)
                    (print-dec (mem-ref (+ state #x19) :u8))
                    (write-byte 46)
                    (print-dec (mem-ref (+ state #x1A) :u8))
                    (write-byte 46)
                    (print-dec (mem-ref (+ state #x1B) :u8))
                    (write-byte 10)
                    (let ((gw-ip (mem-ref (+ state #x1C) :u32)))
                      (arp-request gw-ip)
                      (let ((arp-done 0))
                        (dotimes (try 200)
                          (when (zerop arp-done)
                            (io-delay)
                            (let ((pkt-len (e1000-receive)))
                              (when (not (zerop pkt-len))
                                (let ((buf (e1000-rx-buf)))
                                  (when (eq (mem-ref (+ buf 12) :u8) #x08)
                                    (when (eq (mem-ref (+ buf 13) :u8) #x06)
                                      (when (eq (mem-ref (+ buf 21) :u8) 2)
                                        (dotimes (i 6)
                                          (setf (mem-ref (+ state #x28 i) :u8)
                                                (mem-ref (+ buf 22 i) :u8)))
                                        (setq arp-done 1)))))))))
                        arp-done))))))))))

(defun net-init-dhcp ()
  (e1000-probe)
  (dhcp-client))

;; ================================================================
;; DNS Resolver
;; ================================================================

(defun dns-encode-name (name-array name-len buf offset)
  (let ((write-pos (+ offset 1))
        (label-start offset)
        (label-len 0))
    (dotimes (i name-len)
      (let ((ch (aref name-array i)))
        (if (eq ch 46)
            (progn
              (aset buf label-start label-len)
              (setq label-start write-pos)
              (setq write-pos (+ write-pos 1))
              (setq label-len 0))
            (progn
              (aset buf write-pos ch)
              (setq write-pos (+ write-pos 1))
              (setq label-len (+ label-len 1))))))
    (aset buf label-start label-len)
    (aset buf write-pos 0)
    (+ (- write-pos offset) 1)))

(defun dns-build-query (name-array name-len buf)
  (aset buf 0 0) (aset buf 1 1)
  (aset buf 2 1) (aset buf 3 0)
  (aset buf 4 0) (aset buf 5 1)
  (aset buf 6 0) (aset buf 7 0)
  (aset buf 8 0) (aset buf 9 0)
  (aset buf 10 0) (aset buf 11 0)
  (let ((name-bytes (dns-encode-name name-array name-len buf 12)))
    (let ((qtype-offset (+ 12 name-bytes)))
      (aset buf qtype-offset 0) (aset buf (+ qtype-offset 1) 1)
      (aset buf (+ qtype-offset 2) 0) (aset buf (+ qtype-offset 3) 1)
      (+ qtype-offset 4))))

(defun dns-parse-response ()
  (let ((state (e1000-state-base)))
    (let ((data-addr (mem-ref (+ state #x7C) :u32))
          (data-len (mem-ref (+ state #x80) :u32)))
      (let ((ancount (logior (ash (mem-ref (+ data-addr 6) :u8) 8)
                             (mem-ref (+ data-addr 7) :u8))))
        (if (zerop ancount)
            0
            (let ((pos 12) (done 0))
              (dotimes (iter 64)
                (when (zerop done)
                  (let ((b (mem-ref (+ data-addr pos) :u8)))
                    (if (zerop b)
                        (progn (setq pos (+ pos 1)) (setq done 1))
                        (if (>= b 192)
                            (progn (setq pos (+ pos 2)) (setq done 1))
                            (setq pos (+ pos 1 b)))))))
              (setq pos (+ pos 4))
              (let ((done2 0))
                (dotimes (iter2 64)
                  (when (zerop done2)
                    (let ((b (mem-ref (+ data-addr pos) :u8)))
                      (if (zerop b)
                          (progn (setq pos (+ pos 1)) (setq done2 1))
                          (if (>= b 192)
                              (progn (setq pos (+ pos 2)) (setq done2 1))
                              (setq pos (+ pos 1 b))))))))
              (let ((rtype (logior (ash (mem-ref (+ data-addr pos) :u8) 8)
                                   (mem-ref (+ data-addr pos 1) :u8))))
                (setq pos (+ pos 10))
                (if (eq rtype 1)
                    (logior (ash (mem-ref (+ data-addr pos) :u8) 24)
                            (logior (ash (mem-ref (+ data-addr pos 1) :u8) 16)
                                    (logior (ash (mem-ref (+ data-addr pos 2) :u8) 8)
                                            (mem-ref (+ data-addr pos 3) :u8))))
                    0))))))))

(defun dns-resolve (name-array name-len)
  (let ((state (e1000-state-base))
        (query-buf (make-array 512)))
    (let ((query-len (dns-build-query name-array name-len query-buf)))
      (let ((dns-ip (mem-ref (+ state #x58) :u32)))
        (when (zerop dns-ip)
          (setq dns-ip #x0A000203))
        (udp-send dns-ip 53 12345 query-buf query-len)
        (let ((resp-len (udp-receive 500)))
          (if (zerop resp-len)
              (progn
                (write-byte 68) (write-byte 78) (write-byte 83) (write-byte 58)
                (write-byte 70) (write-byte 10)
                0)
              (let ((ip (dns-parse-response)))
                (write-byte 68) (write-byte 78) (write-byte 83) (write-byte 58)
                (if (zerop ip)
                    (progn (write-byte 70) (write-byte 10))
                    (progn
                      (print-dec (logand (ash ip -24) #xFF))
                      (write-byte 46)
                      (print-dec (logand (ash ip -16) #xFF))
                      (write-byte 46)
                      (print-dec (logand (ash ip -8) #xFF))
                      (write-byte 46)
                      (print-dec (logand ip #xFF))
                      (write-byte 10)))
                ip)))))))

(defun dns-test ()
  (let ((name (make-array 11)))
    (aset name 0 101) (aset name 1 120) (aset name 2 97)
    (aset name 3 109) (aset name 4 112) (aset name 5 108)
    (aset name 6 101) (aset name 7 46) (aset name 8 99)
    (aset name 9 111) (aset name 10 109)
    (dns-resolve name 11)))
