(defvar *net-source-text*
  (when *fixpoint-ssh-mode*
    (format t "~%SSH mode: loading networking source...~%")
    (let* ((net-dir (merge-pathnames "net/" *modus-base*))
           (override-names (mapcar #'first *override-fns*)))
      ;; Load 64-bit networking source
      (let ((text-64 (with-output-to-string (s)
                       ;; Arch adapters (i386 first, x86, aarch64 last)
                       (write-string (read-file-text (merge-pathnames "arch-i386.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "arch-x86.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "arch-aarch64.lisp" net-dir)) s)
                       (terpri s)
                       ;; USB drivers
                       (write-string (read-file-text (merge-pathnames "dwc2.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "usb.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "cdc-ether.lisp" net-dir)) s)
                       (terpri s)
                       ;; Network stack
                       (write-string (read-file-text (merge-pathnames "ip.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "crypto.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "ssh.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "aarch64-overrides.lisp" net-dir)) s)
                       (terpri s)
                       ;; NIC drivers
                       (write-string (read-file-text (merge-pathnames "ne2000.lisp" net-dir)) s)
                       (terpri s)
                       (write-string (read-file-text (merge-pathnames "e1000.lisp" net-dir)) s)
                       (terpri s))))
        ;; Load 32-bit override source (crypto-32, crypto-w32, 32bit-overrides, dwc2-32)
        (let ((text-32 (with-output-to-string (s)
                         (write-string (read-file-text (merge-pathnames "crypto-32.lisp" net-dir)) s)
                         (terpri s)
                         (write-string (read-file-text (merge-pathnames "crypto-w32.lisp" net-dir)) s)
                         (terpri s)
                         (write-string (read-file-text (merge-pathnames "32bit-overrides.lisp" net-dir)) s)
                         (terpri s)
                         ;; DWC2 32-bit overrides
                         (write-string "
(defun hcchar-chena () 0)
(defun hcchar-chdis () 0)
(defun grstctl-ahbidl () 0)
(defun hctsiz-pid-data0 ()
  (setf (mem-ref (+ #x01100000 #x60800) :u32) 0) 0)
(defun hctsiz-pid-data1 ()
  (setf (mem-ref (+ #x01100000 #x60800) :u32) 2) 0)
(defun hctsiz-pid-setup ()
  (setf (mem-ref (+ #x01100000 #x60800) :u32) 3) 0)
(defun dwc2-hprt0-mask () (- 0 47))
(defun dwc2-write-allones (addr)
  (dwc2-write addr (- 0 1)))
(defun dwc2-scratch () (+ #x01100000 #x60C00))
(defun dwc2-read-to-scratch (addr)
  (setf (mem-ref (dwc2-scratch) :u64) (mem-ref addr :u64)))
(defun dwc2-write-from-scratch (addr)
  (setf (mem-ref addr :u64) (mem-ref (dwc2-scratch) :u64)))
(defun dwc2-set-bit31 (addr)
  (dwc2-read-to-scratch addr)
  (let ((b3 (mem-ref (+ (dwc2-scratch) 3) :u8)))
    (setf (mem-ref (+ (dwc2-scratch) 3) :u8) (logior b3 #x80)))
  (dwc2-write-from-scratch addr))
(defun dwc2-set-bit30 (addr)
  (dwc2-read-to-scratch addr)
  (let ((b3 (mem-ref (+ (dwc2-scratch) 3) :u8)))
    (setf (mem-ref (+ (dwc2-scratch) 3) :u8) (logior b3 #x40)))
  (dwc2-write-from-scratch addr))
(defun dwc2-clear-bit30 (addr)
  (dwc2-read-to-scratch addr)
  (let ((b3 (mem-ref (+ (dwc2-scratch) 3) :u8)))
    (setf (mem-ref (+ (dwc2-scratch) 3) :u8) (logand b3 #x3F)))
  (dwc2-write-from-scratch addr))
(defun dwc2-test-bit31 (addr)
  (dwc2-read-to-scratch addr)
  (not (zerop (logand (mem-ref (+ (dwc2-scratch) 3) :u8) #x80))))
(defun dwc2-test-bit30 (addr)
  (dwc2-read-to-scratch addr)
  (not (zerop (logand (mem-ref (+ (dwc2-scratch) 3) :u8) #x40))))
(defun dwc2-init-32-setup ()
  (let ((cfg (dwc2-read (dwc2-gusbcfg))))
    (let ((with-host (logior cfg (gusbcfg-force-host))))
      (dwc2-write (dwc2-gusbcfg) with-host)
      (dwc2-clear-bit30 (dwc2-gusbcfg))))
  (dwc2-delay-ms 50)
  (dwc2-core-reset)
  (dwc2-write (dwc2-gahbcfg)
              (logior (gahbcfg-dma-en)
                      (logior (gahbcfg-hbstlen-incr4)
                              (gahbcfg-glbl-intr-en))))
  (dwc2-write (dwc2-grxfsiz) 1024)
  (dwc2-write (dwc2-gnptxfsiz) (logior (ash 1024 16) 256))
  (dwc2-write (dwc2-hptxfsiz) (logior (ash 1280 16) 256))
  (dwc2-flush-tx-fifo)
  (dwc2-flush-rx-fifo)
  (dwc2-write (dwc2-hcfg) 1)
  0)
(defun dwc2-init-32-channels ()
  (let ((ch 0))
    (loop
      (when (>= ch 16) (return nil))
      (dwc2-write-allones (dwc2-hcint ch))
      (dwc2-write (dwc2-hcintmsk ch) 0)
      (setq ch (+ ch 1))))
  (dwc2-write (dwc2-haintmsk) #xFFFF)
  (dwc2-write (dwc2-gintmsk) 0)
  0)
(defun dwc2-init-32-power ()
  (let ((hprt (dwc2-hprt0-read-safe)))
    (dwc2-write (dwc2-hprt0) (logior hprt (hprt0-prtpwr))))
  (dwc2-delay-ms 100)
  (write-byte 68) (write-byte 87) (write-byte 67)
  (write-byte 50) (write-byte 58)
  (let ((hprt (dwc2-read (dwc2-hprt0))))
    (if (not (zerop (logand hprt (hprt0-prtconnsts))))
        (progn (write-byte 79) (write-byte 75) (write-byte 10) 1)
        (progn (write-byte 78) (write-byte 67) (write-byte 10) 0))))
(defun dwc2-init ()
  (dwc2-init-32-setup)
  (dwc2-init-32-channels)
  (dwc2-init-32-power))
(defun dwc2-core-reset ()
  (let ((i 0))
    (loop
      (when (>= i 100000) (return nil))
      (when (dwc2-test-bit31 (dwc2-grstctl)) (return nil))
      (setq i (+ i 1))))
  (dwc2-write (dwc2-grstctl) (grstctl-csftrst))
  (let ((i 0))
    (loop
      (when (>= i 100000) (return nil))
      (when (zerop (logand (dwc2-read (dwc2-grstctl)) (grstctl-csftrst))) (return nil))
      (setq i (+ i 1))))
  (dwc2-delay-ms 10))
(defun dwc2-start-xfer-pid (ch)
  (let ((pid (mem-ref (+ #x01100000 #x60800) :u32)))
    (when (not (zerop pid))
      (let ((hctsiz-addr (dwc2-hctsiz ch)))
        (dwc2-read-to-scratch hctsiz-addr)
        (let ((b3 (mem-ref (+ (dwc2-scratch) 3) :u8)))
          (setf (mem-ref (+ (dwc2-scratch) 3) :u8) (logior b3 (ash pid 5))))
        (dwc2-write-from-scratch hctsiz-addr)))))
(defun dwc2-start-xfer-enable (ch)
  (let ((hcchar-addr (dwc2-hcchar ch)))
    (dwc2-read-to-scratch hcchar-addr)
    (let ((b3 (mem-ref (+ (dwc2-scratch) 3) :u8)))
      (setf (mem-ref (+ (dwc2-scratch) 3) :u8) (logior (logand b3 #x3F) #x80)))
    (dwc2-write-from-scratch hcchar-addr)))
(defun dwc2-start-transfer (ch hctsiz-val dma-addr)
  (dwc2-write (dwc2-hctsiz ch) hctsiz-val)
  (dwc2-start-xfer-pid ch)
  (dwc2-write (dwc2-hcdma ch) dma-addr)
  (dwc2-start-xfer-enable ch))
(defun dwc2-halt-channel (ch)
  (let ((hcchar-addr (dwc2-hcchar ch)))
    (dwc2-read-to-scratch hcchar-addr)
    (let ((b3 (mem-ref (+ (dwc2-scratch) 3) :u8)))
      (setf (mem-ref (+ (dwc2-scratch) 3) :u8) (logior b3 #xC0)))
    (dwc2-write-from-scratch hcchar-addr))
  (let ((j 0))
    (loop
      (when (>= j 10000) (return nil))
      (when (not (zerop (logand (dwc2-read (dwc2-hcint ch)) (hcint-chhltd)))) (return nil))
      (setq j (+ j 1))))
  (dwc2-write-allones (dwc2-hcint ch)))
(defun dwc2-poll-check-halted (hcint)
  (if (not (zerop (logand hcint (hcint-xfercompl)))) 1
      (if (not (zerop (logand hcint (hcint-stall)))) (- 0 1)
          (if (not (zerop (logand hcint (hcint-nak)))) 0
              (- 0 2)))))
(defun dwc2-poll-channel (ch)
  (let ((result (- 0 3)))
    (let ((i 0))
      (loop
        (when (>= i 50000)
          (dwc2-halt-channel ch)
          (return nil))
        (let ((hcint (dwc2-read (dwc2-hcint ch))))
          (when (not (zerop (logand hcint (hcint-chhltd))))
            (setq result (dwc2-poll-check-halted hcint))
            (dwc2-write-allones (dwc2-hcint ch))
            (return nil))
          (when (not (zerop (logand hcint (hcint-xfercompl))))
            (setq result 1)
            (dwc2-write-allones (dwc2-hcint ch))
            (return nil))
          (when (not (zerop (logand hcint (hcint-nak))))
            (dwc2-write (dwc2-hcint ch) (hcint-nak))))
        (setq i (+ i 1))))
    result))
(defun dwc2-poll-bulk-in (ch)
  (let ((hcint (dwc2-read (dwc2-hcint ch))))
    (if (not (zerop (logand hcint (hcint-chhltd))))
        (progn
          (dwc2-write-allones (dwc2-hcint ch))
          (if (not (zerop (logand hcint (hcint-xfercompl)))) 1
              (if (not (zerop (logand hcint (hcint-stall)))) (- 0 1) (- 0 2))))
        (if (not (zerop (logand hcint (hcint-xfercompl))))
            (progn (dwc2-write-allones (dwc2-hcint ch)) 1)
            (progn
              (when (not (zerop (logand hcint (hcint-nak))))
                (dwc2-write (dwc2-hcint ch) (hcint-nak)))
              0)))))
(defun dwc2-setup-channel (ch hcchar-val)
  (dwc2-write-allones (dwc2-hcint ch))
  (dwc2-write (dwc2-hcintmsk ch) #x7FF)
  (dwc2-write (dwc2-hcchar ch) hcchar-val)
  (dwc2-write (dwc2-hcsplt ch) 0))
(defun dwc2-port-reset ()
  (let ((hprt (dwc2-hprt0-read-safe)))
    (dwc2-write (dwc2-hprt0) (logior hprt (hprt0-prtrst))))
  (dwc2-delay-ms 60)
  (let ((hprt (dwc2-hprt0-read-safe)))
    (let ((cleared (logand hprt (logxor (hprt0-prtrst) (- 0 1)))))
      (dwc2-write (dwc2-hprt0) cleared)))
  (dwc2-delay-ms 20)
  (let ((hprt (dwc2-read (dwc2-hprt0))))
    (write-byte 80) (write-byte 79) (write-byte 82) (write-byte 84) (write-byte 58)
    (let ((speed (logand (ash hprt -17) 3)))
      (if (eq speed 0) (progn (write-byte 72) (write-byte 83))
          (if (eq speed 1) (progn (write-byte 70) (write-byte 83))
              (if (eq speed 2) (progn (write-byte 76) (write-byte 83)) 0)))
      (write-byte 10)
      speed)))

;;; ============================================================
;;; ARM32 architecture adapter functions (32-bit object headers)
;;; ============================================================

;; No PCI on ARM32 RPi
(defun pci-config-read (bus dev fn reg) 0)
(defun pci-config-write (bus dev fn reg val) nil)
(defun pci-assign-bars () nil)

;; DWC2 USB controller base address (BCM2836/BCM2837)
(defun dwc2-base () #x3F980000)

;; I/O delay: read UART to yield to QEMU event loop
(defun io-delay ()
  (dotimes (d 5000) (mem-ref #x3F201000 :u8)))

;; write-byte: capture-aware for SSH output routing
(defun write-byte (b)
  (let ((flags (mem-ref (+ #x01100000 #x14) :u32)))
    (when (zerop (logand flags 2))
      (write-char-serial b))
    (when (not (zerop (logand flags 1)))
      (let ((pos (mem-ref (+ #x01100000 #x18) :u32)))
        (when (< pos 4096)
          (setf (mem-ref (+ #x01100100 pos) :u8) b)
          (setf (mem-ref (+ #x01100000 #x18) :u32) (+ pos 1)))))))

;; Seed entropy from timing
(defun arch-seed-random ()
  (let ((s 0))
    (dotimes (i 4)
      (mem-ref #x3F201000 :u8)
      (setq s (logxor (ash s 8) (logand i #xFF))))
    (when (zerop s) (setq s 42))
    s))

;; DMA and state base addresses — ARM32 RPi (below 0x40000000)
(defun e1000-state-base () #x01060000)
(defun e1000-rx-desc-base () #x01000000)
(defun e1000-rx-buf-base () #x01001000)
(defun e1000-tx-desc-base () #x01041000)
(defun e1000-tx-buf-base () #x01041400)
(defun ssh-conn-base () #x01080000)
(defun usb-ring-base () #x01090000)
(defun ssh-ipc-base () #x01100000)
(defun usb-dma-base () #x01000000)

;; Stubs for x86-specific runtime functions
(defun init-gc-helper () nil)
(defun hash-of (name) 0)
(defun nfn-lookup (hash) 0)

;; Object allocation — 32-bit headers (4 bytes, not 8)
;; Scratch address 0x01070000 for object tag construction
(defun tag-as-object (aptr)
  (let ((raw (untag aptr)))
    (setf (mem-ref #x01070000 :u64) raw)
    (let ((b0 (mem-ref #x01070000 :u8)))
      (setf (mem-ref #x01070000 :u8) (logior b0 3))
      (mem-ref #x01070000 :u64))))

(defun try-alloc-obj (len subtag)
  (let ((aptr (get-alloc-ptr)))
    (let ((data-size (+ len 1)))
      (let ((padded (logand (+ data-size 15) (- 0 16))))
        (let ((total (logand (+ 4 (+ padded 15)) (- 0 16))))
          (if (< (+ aptr total) (get-alloc-limit))
              (progn
                (let ((header (logior (ash len 8) (untag subtag))))
                  (setf (mem-ref aptr :u32) header))
                (let ((i 0))
                  (loop
                    (if (< i padded)
                        (progn
                          (setf (mem-ref (+ aptr (+ 4 i)) :u32) 0)
                          (setq i (+ i 4)))
                        (return ()))))
                (set-alloc-ptr (+ aptr total))
                (tag-as-object aptr))
              0))))))

(defun make-array (len)
  (try-alloc-obj len #x32))

(defun aref (arr idx)
  (let ((raw (ash (logand arr (- 0 4)) 1)))
    (mem-ref (+ raw (+ 4 idx)) :u8)))

(defun aset (arr idx val)
  (let ((raw (ash (logand arr (- 0 4)) 1)))
    (setf (mem-ref (+ raw (+ 4 idx)) :u8) val)))

(defun array-length (arr)
  (let ((raw (ash (logand arr (- 0 4)) 1)))
    (ash (mem-ref raw :u32) -8)))

(defun numberp (obj)
  (eq obj (logand obj (- 0 1))))

;; Line editor state at ssh-ipc-base + offsets
(defun edit-line-len () (mem-ref (+ #x01100000 #x12800) :u64))
(defun edit-set-line-len (v) (setf (mem-ref (+ #x01100000 #x12800) :u64) v))
(defun edit-cursor-pos () (mem-ref (+ #x01100000 #x12808) :u64))
(defun edit-set-cursor-pos (v) (setf (mem-ref (+ #x01100000 #x12808) :u64) v))

;; Eval stubs — MVM doesn't have native compiler at runtime
(defun native-eval (form) 0)
(defun eval-line-expr (line) 0)
(defun rt-compile-defun (name args body) 0)

;; Print decimal number
(defun print-dec (n)
  (when (>= n 10)
    (print-dec (truncate n 10)))
  (write-byte (+ (mod n 10) 48)))

;; Prompt
(defun emit-prompt ()
  (if (zerop (mem-ref (+ #x01100000 #x12A00) :u64))
      (progn (write-byte 62) (write-byte 32))
      (progn
        (write-byte 109) (write-byte 111)
        (write-byte 100) (write-byte 117)
        (write-byte 115) (write-byte 62) (write-byte 32))))

;; Single-threaded stubs
(defun actor-spawn (fn) nil)
(defun actor-exit () nil)
(defun yield () (io-delay))
(defun receive ()
  (io-delay)
  (let ((pkt-len (e1000-receive)))
    (if (zerop pkt-len)
        1
        (let ((buf (e1000-rx-buf)))
          (let ((et-hi (mem-ref (+ buf 12) :u8))
                (et-lo (mem-ref (+ buf 13) :u8)))
            (if (eq et-hi #x08)
                (if (eq et-lo #x06)
                    (let ((arp-op (buf-read-u16-mem buf 20)))
                      (when (eq arp-op 1) (arp-reply buf)))
                    (when (eq et-lo 0)
                      (let ((proto (mem-ref (+ buf 23) :u8)))
                        (if (eq proto 1)
                            (icmp-handle buf 14)
                            (when (eq proto 6)
                              (net-handle-tcp buf pkt-len))))))
                ()))
          1))))
(defun spin-lock (addr) nil)
(defun spin-unlock (addr) nil)

;; CDC-Ether NIC interface (USB networking on ARM32)
(defun e1000-send (buf len)
  (let ((tx-buf (e1000-tx-buf-base)))
    (let ((i 0))
      (loop
        (when (>= i len) (return nil))
        (setf (mem-ref (+ tx-buf i) :u8) (aref buf i))
        (setq i (+ i 1))))
    (let ((result (usb-bulk-send tx-buf len)))
      (if (eq result 1) 1 0))))

(defun e1000-receive ()
  (let ((hctsiz-before (dwc2-read (dwc2-hctsiz 1))))
    (let ((result (usb-bulk-receive (e1000-rx-buf-base) 2048)))
      (if (eq result 1)
          (let ((remaining (logand hctsiz-before #x7FFFF)))
            (let ((actual (- 2048 remaining)))
              (setf (mem-ref (+ (e1000-state-base) #x44) :u32) actual)
              actual))
          0))))

(defun e1000-rx-buf ()
  (e1000-rx-buf-base))
" s)
                         (terpri s)
                         (write-string (read-file-text (merge-pathnames "crypto-32-fast.lisp" net-dir)) s)
                         (terpri s))))
          ;; Rename overridden defuns: c64- in 64-bit source, c32- in 32-bit source
          (let ((renamed-64 (fp-rename-defuns text-64 override-names "c64-"))
                (renamed-32 (fp-rename-defuns text-32 override-names "c32-"))
                (wrappers (fp-gen-dispatch-wrappers)))
            (let ((result (concatenate 'string
                                       renamed-64 (string #\Newline)
                                       renamed-32 (string #\Newline)
                                       wrappers)))
              (format t "  Networking source: ~D chars (64-bit: ~D, 32-bit: ~D, wrappers: ~D)~%"
                      (length result) (length renamed-64) (length renamed-32) (length wrappers))
              result)))))))
