;;; ============================================================
;;; i386→x64 cross-compilation overrides
;;; These override x64 translator functions for i386-host safety.
;;; Key issues: decode-u64 overflow, emit-u64 shift-by-32 no-op,
;;; img-patch-u32 byte-3 overflow for values with bit30!=bit31.
;;; ============================================================

;;; Raw LI handler for x64 output — safe on i386 host.
;;; LI bytecode: [17][vd:1][imm64:8] = 10 bytes.
;;; Emits x64 MOV reg, imm64 (REX.W + B8+r + 8 raw bytes).
(defun td-x64-emit-li-raw (buf bytes pos)
  (let ((vd (logand (aref bytes (+ pos 1)) 31)))
    (let ((d (dest-phys-or-scratch vd)))
      (emit-byte buf (if (reg-extended-p d) 73 72))
      (emit-byte buf (+ 184 (reg-code d)))
      (let ((b0 (+ pos 2)))
        (emit-byte buf (aref bytes b0))
        (emit-byte buf (aref bytes (+ b0 1)))
        (emit-byte buf (aref bytes (+ b0 2)))
        (emit-byte buf (aref bytes (+ b0 3)))
        (emit-byte buf (aref bytes (+ b0 4)))
        (emit-byte buf (aref bytes (+ b0 5)))
        (emit-byte buf (aref bytes (+ b0 6)))
        (emit-byte buf (aref bytes (+ b0 7))))
      (maybe-store-scratch buf vd))))

;;; Override emit-u64: architecture-aware.
;;; On i386, (ash v -32) is a no-op due to x86 shift masking, and
;;; #xFFFFFFFF overflows 30-bit fixnum. With LI and CONSP/ATOM intercepted,
;;; all remaining emit-u64 calls on i386 have values that fit in 32 bits.
;;; On x64/AArch64, use standard ldb decomposition (safe for 63-bit fixnums).
(defun emit-u64 (buf value)
  (if (= (td-read-u32 #x500008) 2)
      ;; i386 host: high32 always 0
      (progn (emit-u32 buf value)
             (emit-byte buf 0) (emit-byte buf 0)
             (emit-byte buf 0) (emit-byte buf 0))
      ;; x64/AArch64 host
      (let ((lo (logand value 4294967295)))
        (let ((hi (logand (ash value -32) 4294967295)))
          (emit-u32 buf lo)
          (emit-u32 buf hi)))))

;;; i386-safe version of td-translate-fn-body: intercepts LI (opcode 17)
;;; before decode-instruction to avoid decode-u64 overflow.
(defun td-translate-fn-body-li-safe (state)
  (let ((bytes (translate-state-mvm-bytes state))
        (offset (translate-state-mvm-offset state))
        (len (translate-state-mvm-length state)))
    (let ((pos offset)
          (limit (+ offset len)))
      (loop
        (when (>= pos limit) (return nil))
        (let ((lbl-idx (- pos *td-label-base*)))
          (let ((label (aref *td-label-array* lbl-idx)))
            (when (not (zerop label))
              (emit-label (translate-state-buf state) label))))
        (if (= (aref bytes pos) 17)
            (progn
              (td-x64-emit-li-raw (translate-state-buf state) bytes pos)
              (setq pos (+ pos 10)))
            (let ((decoded (decode-instruction bytes pos)))
              (let ((opcode (car decoded))
                    (operands (car (cdr decoded)))
                    (new-pos (cdr (cdr decoded))))
                (cond
                  ((= opcode 32)
                   (td-emit-add (translate-state-buf state) operands))
                  ((= opcode 33)
                   (td-emit-sub (translate-state-buf state) operands))
                  ((= opcode 40)
                   (td-emit-and (translate-state-buf state) operands))
                  ((= opcode 41)
                   (td-emit-or (translate-state-buf state) operands))
                  ((= opcode 42)
                   (td-emit-xor (translate-state-buf state) operands))
                  ((= opcode 85)
                   (let ((vd (car operands))
                         (vs (car (cdr operands))))
                     (let ((buf2 (translate-state-buf state)))
                       (let ((d (dest-phys-or-scratch vd))
                             (true-label (make-label))
                             (end-label (make-label)))
                         (emit-load-vreg buf2 vs d)
                         (emit-and-reg-imm buf2 d 15)
                         (emit-cmp-reg-imm buf2 d 1)
                         (emit-jcc buf2 :e true-label)
                         (emit-mov-reg-reg buf2 d (quote r15))
                         (emit-jmp buf2 end-label)
                         (let ((p1 (code-buffer-position buf2)))
                           (aset true-label 1 p1))
                         (emit-mov-reg-imm buf2 d 3735883785)
                         (let ((p2 (code-buffer-position buf2)))
                           (aset end-label 1 p2))
                         (maybe-store-scratch buf2 vd)))))
                  ((= opcode 86)
                   (let ((vd (car operands))
                         (vs (car (cdr operands))))
                     (let ((buf2 (translate-state-buf state)))
                       (let ((d (dest-phys-or-scratch vd))
                             (true-label (make-label))
                             (end-label (make-label)))
                         (emit-load-vreg buf2 vs d)
                         (emit-and-reg-imm buf2 d 15)
                         (emit-cmp-reg-imm buf2 d 1)
                         (emit-jcc buf2 :ne true-label)
                         (emit-mov-reg-reg buf2 d (quote r15))
                         (emit-jmp buf2 end-label)
                         (let ((p1 (code-buffer-position buf2)))
                           (aset true-label 1 p1))
                         (emit-mov-reg-imm buf2 d 3735883785)
                         (let ((p2 (code-buffer-position buf2)))
                           (aset end-label 1 p2))
                         (maybe-store-scratch buf2 vd)))))
                  ((= opcode 137)
                   (let ((buf2 (translate-state-buf state)))
                     (let ((skip-label (make-label)))
                       (emit-cmp-reg-reg buf2 (quote r12) (quote r14))
                       (emit-jcc buf2 :l skip-label)
                       (let ((gc-lbl (translate-state-gc-label state)))
                         (if gc-lbl
                             (emit-call buf2 gc-lbl)
                             (emit-int buf2 49)))
                       (let ((p1 (code-buffer-position buf2)))
                         (aset skip-label 1 p1)))))
                  ((= opcode 131)
                   (let ((target-offset (car operands)))
                     (let ((buf2 (translate-state-buf state))
                           (label (aref *td-fn-label-array* target-offset)))
                       (emit-mov-reg-mem buf2 (quote rbx) (quote rbp) -8)
                       (emit-mov-reg-reg buf2 (quote rsp) (quote rbp))
                       (emit-pop buf2 (quote rbp))
                       (if (zerop label)
                           (emit-jmp buf2 (make-label))
                           (emit-jmp buf2 label)))))
                  ((= opcode 128)
                   (let ((target-offset (car operands)))
                     (let ((label (aref *td-fn-label-array* target-offset)))
                       (if (zerop label)
                           (emit-call (translate-state-buf state) (make-label))
                           (emit-call (translate-state-buf state) label)))))
                  ((= opcode 167)
                   (let ((vd (car operands))
                         (target-offset (car (cdr operands))))
                     (let ((label (aref *td-fn-label-array* target-offset)))
                       (let ((d (dest-phys-or-scratch vd)))
                         (if (zerop label)
                             (emit-mov-reg-imm (translate-state-buf state) d 0)
                             (emit-lea-label (translate-state-buf state) d label))
                         (maybe-store-scratch (translate-state-buf state) vd)))))
                  (t
                   (translate-instruction state opcode operands new-pos)))
                (setq pos new-pos))))))))

;;; i386-safe td-translate-one-fn: uses td-translate-fn-body-li-safe
;;; instead of td-translate-fn-body (avoids last-defun-wins override).
(defun td-translate-one-fn-i386 (ctx fn-label offset len)
  (let ((buf (car ctx))
        (bytecode (car (cdr ctx)))
        (fn-offset-to-label (cdr (cdr ctx))))
    (let ((state (make-translate-state)))
      (set-translate-state-buf state buf)
      (set-translate-state-mvm-bytes state bytecode)
      (set-translate-state-mvm-length state len)
      (set-translate-state-mvm-offset state offset)
      (set-translate-state-function-table state fn-offset-to-label)
      (let ((lpos (code-buffer-position buf)))
        (aset fn-label 1 lpos)
        (let ((labels-ht (code-buffer-labels buf)))
          (puthash fn-label labels-ht lpos)))
      (emit-function-prologue buf)
      (setq *td-label-array* (make-array len))
      ;; Zero-initialize: make-array doesn't clear memory on bare metal
      (let ((zi 0))
        (loop
          (when (>= zi len) (return nil))
          (let ((dummy (aset *td-label-array* zi 0)))
            dummy)
          (setq zi (+ zi 1))))
      (setq *td-label-base* offset)
      (scan-branch-targets state)
      (td-translate-fn-body-li-safe state))))

;;; i386-safe translate-mvm-to-x64: uses td-translate-one-fn-i386.
;;; Does NOT override translate-mvm-to-x64 (avoids breaking x64/AArch64 hosts).
(defun translate-mvm-to-x64-from-i386 (bytecode function-table)
  (let ((buf (make-code-buffer)))
    (let ((n-functions (length function-table)))
      (print-dec n-functions) (write-char-serial 10)
      (let ((fn-labels (make-array n-functions)))
        (let ((fn-map (make-hash-table))
              (fn-offset-to-label (make-hash-table)))
          (setq *td-fn-label-array* (make-array (array-length bytecode)))
          (let ((rest-ft function-table)
                (i 0))
            (loop
              (when (>= i n-functions) (return nil))
              (let ((entry (car rest-ft)))
                (let ((name (car entry))
                      (offset (car (cdr entry))))
                  (let ((label (make-label)))
                    (aset fn-labels i label)
                    (puthash name fn-map label)
                    (puthash offset fn-offset-to-label label)
                    (let ((dummy (aset *td-fn-label-array* offset label)))
                      dummy))))
              (setq rest-ft (cdr rest-ft))
              (setq i (+ i 1))))
          (write-char-serial 84) (write-char-serial 10)
          (let ((ctx (cons buf (cons bytecode fn-offset-to-label))))
            (let ((rest-ft function-table)
                  (i 0))
              (loop
                (when (>= i n-functions) (return nil))
                (let ((entry (car rest-ft)))
                  (let ((offset (car (cdr entry)))
                        (len (car (cdr (cdr entry)))))
                    (let ((fn-label (aref fn-labels i)))
                      (td-translate-one-fn-i386 ctx fn-label offset len))))
                (setq rest-ft (cdr rest-ft))
                (setq i (+ i 1))
                (when (zerop (mod i 50))
                  (write-char-serial 35)
                  (print-dec i)
                  (write-char-serial 10)))))
          (fixup-labels buf)
          (let ((pos (code-buffer-position buf))
                (bytes (code-buffer-bytes buf)))
            (print-dec pos) (write-char-serial 10)
            (let ((fnv (td-fnv-native bytes pos)))
              (write-char-serial 70) (write-char-serial 78)
              (write-char-serial 86) (write-char-serial 58)
              (print-dec fnv) (write-char-serial 10)))
          (cons buf fn-map))))))

;;; i386-safe td-assemble-gen1-x64-i386: raw byte copies avoid u32 overflow.
;;; Separate name avoids clobbering td-assemble-gen1-x64 used by AArch64→x64.
(defun td-assemble-gen1-x64-i386 (result bc ft)
  (let ((buf (car result))
        (fn-map (cdr result)))
    (let ((native-bytes (code-buffer-bytes buf))
          (native-size (code-buffer-position buf)))
      (img-init)
      (write-char-serial 88) (write-char-serial 49)
      (write-char-serial 58) (write-char-serial 10)
      (let ((boot-size (td-generate-x64-boot)))
        (write-char-serial 80)
        (print-dec boot-size) (write-char-serial 10)
        ;; JMP rel32 to kernel-main
        (let ((km-hash (td-read-u32 #x500028)))
          (let ((km-label (gethash km-hash fn-map)))
            (let ((km-offset 0))
              (when km-label
                (setq km-offset (aref km-label 1)))
              (img-emit 233)
              (img-emit-u32 km-offset))))
        ;; Copy native code
        (write-char-serial 78)
        (td-write-u32 #x500050 (img-pos))
        (let ((i 0))
          (loop
            (when (>= i native-size) (return nil))
            (img-emit (aref native-bytes i))
            (setq i (+ i 1))
            (when (zerop (mod i 50000))
              (write-char-serial 46))))
        (write-char-serial 10)
        ;; Append bytecodes
        (write-char-serial 84)
        (let ((bc-len (array-length bc))
              (bc-img-offset (img-pos)))
          (let ((bi 0))
            (loop
              (when (>= bi bc-len) (return nil))
              (img-emit (aref bc bi))
              (setq bi (+ bi 1))))
          ;; Append function table — raw byte copy from source image
          ;; (avoids u32 overflow for name hashes with byte 3 >= 0x80 on i386)
          (let ((ft-img-offset (img-pos))
                (src-ft-addr (+ (td-read-u32 #x500030) (td-read-u32 #x500014)))
                (ft-count (td-read-u32 #x500018)))
            (let ((total-ft-bytes (* ft-count 12))
                  (bi 0))
              (loop
                (when (>= bi total-ft-bytes) (return nil))
                (img-emit (mem-ref (+ src-ft-addr bi) :u8))
                (setq bi (+ bi 1))))
            (write-char-serial 10)
            (print-dec ft-count) (write-char-serial 10)
            ;; Metadata at 0x400000
            (let ((md-img-off #x400000))
              ;; magic MVMT = 0x544D564D — write as individual bytes
              ;; (0x544D564D > 2^30, overflows i386 30-bit fixnum)
              (let ((base (+ #x08000000 md-img-off)))
                (setf (mem-ref base :u8) #x4D)
                (setf (mem-ref (+ base 1) :u8) #x56)
                (setf (mem-ref (+ base 2) :u8) #x4D)
                (setf (mem-ref (+ base 3) :u8) #x54))
              (img-patch-u32 (+ md-img-off 4) 1)
              ;; my-architecture = 0 (x64)
              (img-patch-u32 (+ md-img-off 8) 0)
              (img-patch-u32 (+ md-img-off 12) bc-img-offset)
              (img-patch-u32 (+ md-img-off 16) bc-len)
              (img-patch-u32 (+ md-img-off 20) ft-img-offset)
              (img-patch-u32 (+ md-img-off 24) ft-count)
              (img-patch-u32 (+ md-img-off 28) (td-read-u32 #x500050))
              (img-patch-u32 (+ md-img-off 32) native-size)
              (img-patch-u32 (+ md-img-off 36) boot-size)
              ;; kernel-main-hash-lo — raw byte copy (avoids u32 overflow on i386)
              (let ((dst-base (+ #x08000000 md-img-off 40)))
                (setf (mem-ref dst-base :u8) (mem-ref #x500028 :u8))
                (setf (mem-ref (+ dst-base 1) :u8) (mem-ref #x500029 :u8))
                (setf (mem-ref (+ dst-base 2) :u8) (mem-ref #x50002A :u8))
                (setf (mem-ref (+ dst-base 3) :u8) (mem-ref #x50002B :u8)))
              ;; kernel-main-native-offset
              (let ((km-label (gethash (td-read-u32 #x500028) fn-map)))
                (if km-label
                    (img-patch-u32 (+ md-img-off 44) (aref km-label 1))
                    (img-patch-u32 (+ md-img-off 44) 0)))
              ;; image-load-addr = 0x100000 (x64)
              (img-patch-u32 (+ md-img-off 48) #x100000)
              ;; target-architecture (default: 1=aarch64)
              (img-patch-u32 (+ md-img-off 52) 1)
              ;; mode (default: 0=cross-compile)
              (img-patch-u32 (+ md-img-off 56) 0))
            ;; Patch multiboot header
            (let ((total-size (+ #x400000 64)))
              (let ((load-end (+ #x100000 total-size)))
                (img-patch-u32 20 load-end)
                (img-patch-u32 24 load-end))
              (write-char-serial 88) (write-char-serial 49)
              (write-char-serial 61)
              (print-dec total-size) (write-char-serial 10)
              total-size)))))))

;;; Build x64 target from i386 host
(defun build-x64-from-i386 (bc ft)
  (let ((result (translate-mvm-to-x64-from-i386 bc ft)))
    (let ((buf (car result)))
      (let ((native-size (code-buffer-position buf)))
        (print-dec native-size) (write-char-serial 10)
        (let ((native-bytes (code-buffer-bytes buf)))
          (let ((hash (td-fnv-native native-bytes native-size)))
            (write-char-serial 70) (write-char-serial 78)
            (write-char-serial 86) (write-char-serial 58)
            (print-dec hash) (write-char-serial 10)))
        (td-assemble-gen1-x64-i386 result bc ft)
        native-size))))


