;;; crypto-mvm-split.lisp — MVM-safe split implementations of crypto functions
;;;
;;; These functions replace crypto.lisp's fe-*, ed-add, ed-double, ed-scalar-mult
;;; which have too many let bindings (exceeding the MVM compiler's 18+ nested let
;;; limit) or too many sequential forms (exceeding the ~25 form limit).
;;;
;;; Each function is split into smaller helpers that stay within MVM compiler limits.
;;; This file contains 64-bit implementations only (no 32-bit dispatch wrappers).
;;;
;;; Extracted from mvm/build-fixpoint.lisp.

;;; Flat helper: combine 4 values with logior (avoids nested expression clobber)
(defun flat-logior4 (a b c d)
  (let ((lo (logior a b)))
    (let ((mid (logior lo c)))
      (logior mid d))))

;;; Flat buf-read-u32 family — overrides that avoid nested logior miscompilation.
;;; On 64-bit, the high-byte mask is always 0xFF (no-op), so we read directly.
(defun buf-read-u32 (buf off)
  (let ((b0 (aref buf off)))
    (let ((b1 (aref buf (+ off 1))))
      (let ((b2 (aref buf (+ off 2))))
        (let ((b3 (aref buf (+ off 3))))
          (flat-logior4 (ash b0 24) (ash b1 16) (ash b2 8) b3))))))
(defun buf-read-u16-mem (addr off)
  (let ((a0 (+ addr off)))
    (let ((hi (mem-ref a0 :u8)))
      (let ((lo (mem-ref (+ a0 1) :u8)))
        (logior (ash hi 8) lo)))))
(defun buf-read-u32-mem (addr off)
  (let ((a0 (+ addr off)))
    (let ((b0 (mem-ref a0 :u8)))
      (let ((b1 (mem-ref (+ a0 1) :u8)))
        (let ((b2 (mem-ref (+ a0 2) :u8)))
          (let ((b3 (mem-ref (+ a0 3) :u8)))
            (flat-logior4 (ash b0 24) (ash b1 16) (ash b2 8) b3)))))))
(defun buf-read-u32-le (buf offset)
  (let ((b0 (aref buf offset)))
    (let ((b1 (aref buf (+ offset 1))))
      (let ((b2 (aref buf (+ offset 2))))
        (let ((b3 (aref buf (+ offset 3))))
          (flat-logior4 b0 (ash b1 8) (ash b2 16) (ash b3 24)))))))
(defun ssh-get-u32 (arr off)
  (let ((b0 (aref arr off)))
    (let ((b1 (aref arr (+ off 1))))
      (let ((b2 (aref arr (+ off 2))))
        (let ((b3 (aref arr (+ off 3))))
          (flat-logior4 (ash b0 24) (ash b1 16) (ash b2 8) b3))))))

;;; Safe buf-write-u32: pre-compute all values into let bindings to avoid
;;; variable-index ASET bug (value expression clobbers index register).
(defun buf-write-u32-helper (buf off v0 v1 v2 v3)
  (aset buf off v0)
  (let ((o1 (+ off 1)))
    (aset buf o1 v1))
  (let ((o2 (+ off 2)))
    (aset buf o2 v2))
  (let ((o3 (+ off 3)))
    (aset buf o3 v3)))
(defun buf-write-u32 (buf off val)
  (let ((v0 (logand (ash val -24) #xFF)))
    (let ((v1 (logand (ash val -16) #xFF)))
      (let ((v2 (logand (ash val -8) #xFF)))
        (let ((v3 (logand val #xFF)))
          (buf-write-u32-helper buf off v0 v1 v2 v3))))))

;;; Split fe-mul: the original has let* with ~43 bindings which exceeds
;;; the x64 translator's 32 frame slot limit (352 byte frame). Split into
;;; helpers that each use < 20 frame slots.
;;;
;;; Strategy: store pre-computed values (f*2, g*19) into temp arrays,
;;; then each product function reads from those arrays. Max 3 args per call.

;; Pre-compute doubled f limbs and g*19 limbs into temp arrays
;; ff[0..9] = f[0..9], ff[10..14] = f1*2, f3*2, f5*2, f7*2, f9*2
;; gg[0..9] = g[0..9], gg[10..18] = g1*19, g2*19, ..., g9*19
(defun fe-mul-precomp-f (ff f)
  ;; Copy f limbs to ff[0..9]
  (buf-write-u32 ff 0 (buf-read-u32 f 0))
  (buf-write-u32 ff 4 (buf-read-u32 f 4))
  (buf-write-u32 ff 8 (buf-read-u32 f 8))
  (buf-write-u32 ff 12 (buf-read-u32 f 12))
  (buf-write-u32 ff 16 (buf-read-u32 f 16))
  (buf-write-u32 ff 20 (buf-read-u32 f 20))
  (buf-write-u32 ff 24 (buf-read-u32 f 24))
  (buf-write-u32 ff 28 (buf-read-u32 f 28))
  (buf-write-u32 ff 32 (buf-read-u32 f 32))
  (buf-write-u32 ff 36 (buf-read-u32 f 36))
  ;; ff[10..14] = f1*2, f3*2, f5*2, f7*2, f9*2
  (buf-write-u32 ff 40 (* 2 (buf-read-u32 f 4)))
  (buf-write-u32 ff 44 (* 2 (buf-read-u32 f 12)))
  (buf-write-u32 ff 48 (* 2 (buf-read-u32 f 20)))
  (buf-write-u32 ff 52 (* 2 (buf-read-u32 f 28)))
  (buf-write-u32 ff 56 (* 2 (buf-read-u32 f 36)))
  0)

(defun fe-mul-precomp-g (gg g)
  ;; Copy g limbs to gg[0..9]
  (buf-write-u32 gg 0 (buf-read-u32 g 0))
  (buf-write-u32 gg 4 (buf-read-u32 g 4))
  (buf-write-u32 gg 8 (buf-read-u32 g 8))
  (buf-write-u32 gg 12 (buf-read-u32 g 12))
  (buf-write-u32 gg 16 (buf-read-u32 g 16))
  (buf-write-u32 gg 20 (buf-read-u32 g 20))
  (buf-write-u32 gg 24 (buf-read-u32 g 24))
  (buf-write-u32 gg 28 (buf-read-u32 g 28))
  (buf-write-u32 gg 32 (buf-read-u32 g 32))
  (buf-write-u32 gg 36 (buf-read-u32 g 36))
  ;; gg[10..18] = g1*19, g2*19, ..., g9*19
  (buf-write-u32 gg 40 (* 19 (buf-read-u32 g 4)))
  (buf-write-u32 gg 44 (* 19 (buf-read-u32 g 8)))
  (buf-write-u32 gg 48 (* 19 (buf-read-u32 g 12)))
  (buf-write-u32 gg 52 (* 19 (buf-read-u32 g 16)))
  (buf-write-u32 gg 56 (* 19 (buf-read-u32 g 20)))
  (buf-write-u32 gg 60 (* 19 (buf-read-u32 g 24)))
  (buf-write-u32 gg 64 (* 19 (buf-read-u32 g 28)))
  (buf-write-u32 gg 68 (* 19 (buf-read-u32 g 32)))
  (buf-write-u32 gg 72 (* 19 (buf-read-u32 g 36)))
  0)

;; Compute one h product: h[n] = sum of 10 f*g terms
;; ff layout: [f0..f9, f1*2, f3*2, f5*2, f7*2, f9*2]
;; gg layout: [g0..g9, g1*19, g2*19, ..., g9*19]
;; Even h (h0,h2,h4,h6,h8): use f1-2,f3-2,f5-2,f7-2,f9-2
;; Odd h (h1,h3,h5,h7,h9): use plain f values

;; Helper: read ff[i] — plain f for index 0-9, doubled f for 10-14
(defun ff-read (ff i)
  (buf-read-u32 ff (* i 4)))

;; h0 = f0*g0 + f1_2*g9_19 + f2*g8_19 + f3_2*g7_19 + f4*g6_19
;;     + f5_2*g5_19 + f6*g4_19 + f7_2*g3_19 + f8*g2_19 + f9_2*g1_19
;; NOTE: h values are 57+ bit intermediates — must use aset (tagged 63-bit),
;; NOT buf-write-u32 (truncates to 32 bits, destroying upper bits needed for carry).
(defun fe-mul-h0 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 0))))
    (let ((p1 (* (ff-read ff 10) (ff-read gg 18))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 17))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 11) (ff-read gg 16))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 15))))
              (let ((p5 (* (ff-read ff 12) (ff-read gg 14))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 13))))
                    (let ((p7 (* (ff-read ff 13) (ff-read gg 12))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 11))))
                        (let ((p9 (* (ff-read ff 14) (ff-read gg 10))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 0 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h1 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 1))))
    (let ((p1 (* (ff-read ff 1) (ff-read gg 0))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 18))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 3) (ff-read gg 17))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 16))))
              (let ((p5 (* (ff-read ff 5) (ff-read gg 15))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 14))))
                    (let ((p7 (* (ff-read ff 7) (ff-read gg 13))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 12))))
                        (let ((p9 (* (ff-read ff 9) (ff-read gg 11))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 1 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h2 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 2))))
    (let ((p1 (* (ff-read ff 10) (ff-read gg 1))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 0))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 11) (ff-read gg 18))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 17))))
              (let ((p5 (* (ff-read ff 12) (ff-read gg 16))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 15))))
                    (let ((p7 (* (ff-read ff 13) (ff-read gg 14))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 13))))
                        (let ((p9 (* (ff-read ff 14) (ff-read gg 12))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 2 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h3 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 3))))
    (let ((p1 (* (ff-read ff 1) (ff-read gg 2))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 1))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 3) (ff-read gg 0))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 18))))
              (let ((p5 (* (ff-read ff 5) (ff-read gg 17))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 16))))
                    (let ((p7 (* (ff-read ff 7) (ff-read gg 15))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 14))))
                        (let ((p9 (* (ff-read ff 9) (ff-read gg 13))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 3 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h4 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 4))))
    (let ((p1 (* (ff-read ff 10) (ff-read gg 3))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 2))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 11) (ff-read gg 1))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 0))))
              (let ((p5 (* (ff-read ff 12) (ff-read gg 18))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 17))))
                    (let ((p7 (* (ff-read ff 13) (ff-read gg 16))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 15))))
                        (let ((p9 (* (ff-read ff 14) (ff-read gg 14))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 4 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h5 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 5))))
    (let ((p1 (* (ff-read ff 1) (ff-read gg 4))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 3))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 3) (ff-read gg 2))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 1))))
              (let ((p5 (* (ff-read ff 5) (ff-read gg 0))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 18))))
                    (let ((p7 (* (ff-read ff 7) (ff-read gg 17))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 16))))
                        (let ((p9 (* (ff-read ff 9) (ff-read gg 15))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 5 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h6 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 6))))
    (let ((p1 (* (ff-read ff 10) (ff-read gg 5))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 4))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 11) (ff-read gg 3))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 2))))
              (let ((p5 (* (ff-read ff 12) (ff-read gg 1))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 0))))
                    (let ((p7 (* (ff-read ff 13) (ff-read gg 18))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 17))))
                        (let ((p9 (* (ff-read ff 14) (ff-read gg 16))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 6 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h7 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 7))))
    (let ((p1 (* (ff-read ff 1) (ff-read gg 6))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 5))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 3) (ff-read gg 4))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 3))))
              (let ((p5 (* (ff-read ff 5) (ff-read gg 2))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 1))))
                    (let ((p7 (* (ff-read ff 7) (ff-read gg 0))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 18))))
                        (let ((p9 (* (ff-read ff 9) (ff-read gg 17))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 7 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h8 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 8))))
    (let ((p1 (* (ff-read ff 10) (ff-read gg 7))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 6))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 11) (ff-read gg 5))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 4))))
              (let ((p5 (* (ff-read ff 12) (ff-read gg 3))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 2))))
                    (let ((p7 (* (ff-read ff 13) (ff-read gg 1))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 0))))
                        (let ((p9 (* (ff-read ff 14) (ff-read gg 18))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 8 (+ a (+ b c)))))))))))))))))

(defun fe-mul-h9 (h ff gg)
  (let ((p0 (* (ff-read ff 0) (ff-read gg 9))))
    (let ((p1 (* (ff-read ff 1) (ff-read gg 8))))
      (let ((p2 (* (ff-read ff 2) (ff-read gg 7))))
        (let ((a (+ p0 (+ p1 p2))))
          (let ((p3 (* (ff-read ff 3) (ff-read gg 6))))
            (let ((p4 (* (ff-read ff 4) (ff-read gg 5))))
              (let ((p5 (* (ff-read ff 5) (ff-read gg 4))))
                (let ((b (+ p3 (+ p4 p5))))
                  (let ((p6 (* (ff-read ff 6) (ff-read gg 3))))
                    (let ((p7 (* (ff-read ff 7) (ff-read gg 2))))
                      (let ((p8 (* (ff-read ff 8) (ff-read gg 1))))
                        (let ((p9 (* (ff-read ff 9) (ff-read gg 0))))
                          (let ((c (+ p6 (+ p7 (+ p8 p9)))))
                            (aset h 9 (+ a (+ b c)))))))))))))))))

;; Compute all 10 products (split into two halves to stay under 12 forms each)
(defun fe-mul-lo (h ff gg)
  (fe-mul-h0 h ff gg)
  (fe-mul-h1 h ff gg)
  (fe-mul-h2 h ff gg)
  (fe-mul-h3 h ff gg)
  (fe-mul-h4 h ff gg)
  0)

(defun fe-mul-hi (h ff gg)
  (fe-mul-h5 h ff gg)
  (fe-mul-h6 h ff gg)
  (fe-mul-h7 h ff gg)
  (fe-mul-h8 h ff gg)
  (fe-mul-h9 h ff gg)
  0)

;; Stage 2a: carry propagation c0-c4 in-place on h array (tagged 63-bit values)
(defun fe-mul-carry-lo (h)
  ;; c0
  (let ((h0 (aref h 0)))
    (let ((c0 (ash h0 -26)))
      (aset h 0 (logand h0 #x3FFFFFF))
      (aset h 1 (+ (aref h 1) c0))))
  ;; c1
  (let ((h1 (aref h 1)))
    (let ((c1 (ash h1 -25)))
      (aset h 1 (logand h1 #x1FFFFFF))
      (aset h 2 (+ (aref h 2) c1))))
  ;; c2
  (let ((h2 (aref h 2)))
    (let ((c2 (ash h2 -26)))
      (aset h 2 (logand h2 #x3FFFFFF))
      (aset h 3 (+ (aref h 3) c2))))
  ;; c3
  (let ((h3 (aref h 3)))
    (let ((c3 (ash h3 -25)))
      (aset h 3 (logand h3 #x1FFFFFF))
      (aset h 4 (+ (aref h 4) c3))))
  ;; c4
  (let ((h4 (aref h 4)))
    (let ((c4 (ash h4 -26)))
      (aset h 4 (logand h4 #x3FFFFFF))
      (aset h 5 (+ (aref h 5) c4))))
  0)

;; Stage 2b: carry c5-c9, wrap c9*19 back to h0, copy to dst
(defun fe-mul-carry-hi (dst h)
  ;; c5
  (let ((h5 (aref h 5)))
    (let ((c5 (ash h5 -25)))
      (aset h 5 (logand h5 #x1FFFFFF))
      (aset h 6 (+ (aref h 6) c5))))
  ;; c6
  (let ((h6 (aref h 6)))
    (let ((c6 (ash h6 -26)))
      (aset h 6 (logand h6 #x3FFFFFF))
      (aset h 7 (+ (aref h 7) c6))))
  ;; c7
  (let ((h7 (aref h 7)))
    (let ((c7 (ash h7 -25)))
      (aset h 7 (logand h7 #x1FFFFFF))
      (aset h 8 (+ (aref h 8) c7))))
  ;; c8
  (let ((h8 (aref h 8)))
    (let ((c8 (ash h8 -26)))
      (aset h 8 (logand h8 #x3FFFFFF))
      (aset h 9 (+ (aref h 9) c8))))
  ;; c9 → wraps back to h0 with *19
  (let ((h9 (aref h 9)))
    (let ((c9 (ash h9 -25)))
      (aset h 9 (logand h9 #x1FFFFFF))
      (let ((r0w (+ (aref h 0) (* c9 19))))
        (let ((c0b (ash r0w -26)))
          (aset h 0 (logand r0w #x3FFFFFF))
          (aset h 1 (+ (aref h 1) c0b))))))
  ;; Copy h to dst (h is tagged array, dst is byte array)
  (fe-mul-copy dst h)
  dst)

;; Copy 10 limbs from h (tagged array) to dst (byte array via buf-write-u32)
(defun fe-mul-copy (dst h)
  (buf-write-u32 dst 0 (aref h 0))
  (buf-write-u32 dst 4 (aref h 1))
  (buf-write-u32 dst 8 (aref h 2))
  (buf-write-u32 dst 12 (aref h 3))
  (buf-write-u32 dst 16 (aref h 4))
  (buf-write-u32 dst 20 (aref h 5))
  (buf-write-u32 dst 24 (aref h 6))
  (buf-write-u32 dst 28 (aref h 7))
  (buf-write-u32 dst 32 (aref h 8))
  (buf-write-u32 dst 36 (aref h 9))
  0)

;; Split fe-mul for 64-bit (avoids frame slot overflow from 43+ let* bindings)
;; h is a 10-element tagged array (not byte array!) because intermediate h values
;; are 57+ bit sums that don't fit in buf-write-u32's 32 bits.
(defun fe-mul-split (dst f g)
  (let ((ff (make-array 60)))
    (let ((gg (make-array 76)))
      (let ((h (make-array 10)))
        (dotimes (i 10) (aset h i 0))
        (fe-mul-precomp-f ff f)
        (fe-mul-precomp-g gg g)
        (fe-mul-lo h ff gg)
        (fe-mul-hi h ff gg)
        (fe-mul-carry-lo h)
        (fe-mul-carry-hi dst h))))
  dst)

;; Top-level fe-mul: calls fe-mul-split directly (64-bit only, no dispatch)
(defun fe-mul (dst f g)
  (fe-mul-split dst f g))

;;; Split ed-add: original has 20 let bindings (over 18 limit) + 15 forms.
;;; Split into init (extract point components) and compute (arithmetic).
;;; ed-add: restructured so helpers take <=4 args (avoid >4 arg overflow bug).
(defun ed-add (p q)
  (ed-add-compute p q))

(defun ed-add-compute (p q)
  (let ((x1 (car (car p))) (y1 (cdr (car p)))
        (z1 (car (cdr p))) (t1 (cdr (cdr p))))
    (let ((x2 (car (car q))) (y2 (cdr (car q)))
          (z2 (car (cdr q))) (t2 (cdr (cdr q))))
      (let ((w0 (make-array 40)) (w1 (make-array 40))
            (w2 (make-array 40)) (w3 (make-array 40)))
        (let ((w4 (make-array 40)) (w5 (make-array 40)))
          ;; A = (Y1-X1)*(Y2-X2)
          (fe-sub w0 y1 x1) (fe-sub w1 y2 x2)
          (fe-mul w2 w0 w1)
          ;; B = (Y1+X1)*(Y2+X2)
          (fe-add w0 y1 x1) (fe-add w1 y2 x2)
          (fe-mul w3 w0 w1)
          ;; C = T1 * 2*d * T2
          (fe-load-fixed w0 (+ (e1000-state-base) #x500))
          (fe-add w0 w0 w0)
          (fe-mul w0 t1 w0) (fe-mul w4 w0 t2)
          ;; D = 2 * Z1 * Z2
          (fe-mul w5 z1 z2) (fe-add w5 w5 w5)
          (ed-add-finish w2 w3 w4 w5))))))

(defun ed-add-finish (w2 w3 w4 w5)
  (let ((w6 (make-array 40)) (w7 (make-array 40)))
    (let ((rx (make-array 40)) (ry (make-array 40))
          (rz (make-array 40)) (rt (make-array 40)))
      ;; E = B - A, F = D - C, G = D + C, H = B + A
      (fe-sub w6 w3 w2) (fe-sub w7 w5 w4)
      (let ((w0g (make-array 40)) (w1h (make-array 40)))
        (fe-add w0g w5 w4) (fe-add w1h w3 w2)
        ;; X3=E*F, Y3=G*H, T3=E*H, Z3=F*G
        (fe-mul rx w6 w7) (fe-mul ry w0g w1h)
        (fe-mul rt w6 w1h) (fe-mul rz w7 w0g)
        (cons (cons rx ry) (cons rz rt))))))

;;; Override ed-double: original has 13 let bindings + 14 body forms = 27 forms.
;;; Exceeds ~25 sequential forms limit. Split into two helpers.
(defun ed-double-ab (x1 y1 z1 out)
  ;; out = [a, b, c, dd, e] as 5x40-byte regions in a 200-byte array
  ;; A = X1^2
  (let ((a (make-array 40)) (b (make-array 40)))
    (fe-sq a x1)
    (fe-sq b y1)
    (let ((c (make-array 40)))
      (fe-sq c z1)
      (fe-add c c c)
      (let ((dd (make-array 40)) (e (make-array 40)))
        (fe-sub dd (fe-from-int 0) a)
        (fe-add e x1 y1)
        (fe-sq e e)
        (fe-sub e e a)
        (fe-sub e e b)
        ;; Return (a . (b . (c . (dd . e))))
        (cons a (cons b (cons c (cons dd e))))))))

(defun ed-double-finish (pack)
  (let ((a (car pack)) (b (car (cdr pack)))
        (c (car (cdr (cdr pack)))))
    (let ((dd (car (cdr (cdr (cdr pack)))))
          (e (cdr (cdr (cdr (cdr pack))))))
      (let ((g (make-array 40)) (f (make-array 40))
            (h (make-array 40)))
        (fe-add g dd b)
        (fe-sub f g c)
        (fe-sub h dd b)
        (let ((rx (make-array 40)) (ry (make-array 40))
              (rz (make-array 40)) (rt (make-array 40)))
          (fe-mul rx e f)
          (fe-mul ry g h)
          (fe-mul rt e h)
          (fe-mul rz f g)
          (cons (cons rx ry) (cons rz rt)))))))

(defun ed-double (p)
  (let ((x1 (car (car p)))
        (y1 (cdr (car p)))
        (z1 (car (cdr p))))
    (let ((pack (ed-double-ab x1 y1 z1 0)))
      (ed-double-finish pack))))

;;; Override ed-scalar-mult: pass scalar via cons to avoid register clobber
(defun ed-scalar-mult-byte (result temp scalar byte-idx)
  ;; Process 8 bits from scalar[byte-idx]
  (let ((byte-val (aref scalar byte-idx)))
    (let ((b0 (logand byte-val 1)))
      (let ((r0 (if (not (zerop b0)) (ed-add result temp) result)))
        (let ((t0 (ed-double temp)))
          (let ((b1 (logand byte-val 2)))
            (let ((r1 (if (not (zerop b1)) (ed-add r0 t0) r0)))
              (let ((t1 (ed-double t0)))
                (let ((b2 (logand byte-val 4)))
                  (let ((r2 (if (not (zerop b2)) (ed-add r1 t1) r1)))
                    (let ((t2 (ed-double t1)))
                      (let ((b3 (logand byte-val 8)))
                        (let ((r3 (if (not (zerop b3)) (ed-add r2 t2) r2)))
                          (let ((t3 (ed-double t2)))
                            (ed-scalar-mult-byte2 r3 t3 byte-val)))))))))))))))

(defun ed-scalar-mult-byte2 (result temp byte-val)
  (let ((b4 (logand byte-val 16)))
    (let ((r4 (if (not (zerop b4)) (ed-add result temp) result)))
      (let ((t4 (ed-double temp)))
        (let ((b5 (logand byte-val 32)))
          (let ((r5 (if (not (zerop b5)) (ed-add r4 t4) r4)))
            (let ((t5 (ed-double t4)))
              (let ((b6 (logand byte-val 64)))
                (let ((r6 (if (not (zerop b6)) (ed-add r5 t5) r5)))
                  (let ((t6 (ed-double t5)))
                    (let ((b7 (logand byte-val 128)))
                      (let ((r7 (if (not (zerop b7)) (ed-add r6 t6) r6)))
                        (let ((t7 (ed-double t6)))
                          (cons r7 t7))))))))))))))

(defun ed-scalar-mult-loop (result temp scalar i)
  ;; Process bytes 0..31
  (if (>= i 32)
      result
      (let ((pair (ed-scalar-mult-byte result temp scalar i)))
        (ed-scalar-mult-loop (car pair) (cdr pair) scalar (+ i 1)))))

(defun ed-scalar-mult (scalar point)
  (let ((result (cons (cons (fe-from-int 0) (fe-from-int 1))
                      (cons (fe-from-int 1) (fe-from-int 0)))))
    (ed-scalar-mult-loop result point scalar 0)))

;;; Split fe-carry: original has let* with 32 bindings + 10 buf-write-u32 = 42 forms.
;;; Reuse the in-place carry pattern from fe-mul-carry.
;; fe-carry operates on byte arrays (post-carry 26/25-bit limbs fit in 32 bits)
;; Uses buf-read-u32/buf-write-u32 directly (NOT fe-mul-carry-lo which uses aref/aset)
(defun fe-carry (h)
  (fe-carry-lo h)
  (fe-carry-hi h)
  h)

(defun fe-carry-lo (h)
  (let ((h0 (buf-read-u32 h 0)))
    (let ((c0 (ash h0 -26)))
      (buf-write-u32 h 0 (logand h0 #x3FFFFFF))
      (buf-write-u32 h 4 (+ (buf-read-u32 h 4) c0))))
  (let ((h1 (buf-read-u32 h 4)))
    (let ((c1 (ash h1 -25)))
      (buf-write-u32 h 4 (logand h1 #x1FFFFFF))
      (buf-write-u32 h 8 (+ (buf-read-u32 h 8) c1))))
  (let ((h2 (buf-read-u32 h 8)))
    (let ((c2 (ash h2 -26)))
      (buf-write-u32 h 8 (logand h2 #x3FFFFFF))
      (buf-write-u32 h 12 (+ (buf-read-u32 h 12) c2))))
  (let ((h3 (buf-read-u32 h 12)))
    (let ((c3 (ash h3 -25)))
      (buf-write-u32 h 12 (logand h3 #x1FFFFFF))
      (buf-write-u32 h 16 (+ (buf-read-u32 h 16) c3))))
  (let ((h4 (buf-read-u32 h 16)))
    (let ((c4 (ash h4 -26)))
      (buf-write-u32 h 16 (logand h4 #x3FFFFFF))
      (buf-write-u32 h 20 (+ (buf-read-u32 h 20) c4))))
  0)

(defun fe-carry-hi (h)
  (let ((h5 (buf-read-u32 h 20)))
    (let ((c5 (ash h5 -25)))
      (buf-write-u32 h 20 (logand h5 #x1FFFFFF))
      (buf-write-u32 h 24 (+ (buf-read-u32 h 24) c5))))
  (let ((h6 (buf-read-u32 h 24)))
    (let ((c6 (ash h6 -26)))
      (buf-write-u32 h 24 (logand h6 #x3FFFFFF))
      (buf-write-u32 h 28 (+ (buf-read-u32 h 28) c6))))
  (let ((h7 (buf-read-u32 h 28)))
    (let ((c7 (ash h7 -25)))
      (buf-write-u32 h 28 (logand h7 #x1FFFFFF))
      (buf-write-u32 h 32 (+ (buf-read-u32 h 32) c7))))
  (let ((h8 (buf-read-u32 h 32)))
    (let ((c8 (ash h8 -26)))
      (buf-write-u32 h 32 (logand h8 #x3FFFFFF))
      (buf-write-u32 h 36 (+ (buf-read-u32 h 36) c8))))
  ;; c9 wraps to h0 with *19
  (let ((h9 (buf-read-u32 h 36)))
    (let ((c9 (ash h9 -25)))
      (buf-write-u32 h 36 (logand h9 #x1FFFFFF))
      (let ((r0w (+ (buf-read-u32 h 0) (* c9 19))))
        (let ((c0b (ash r0w -26)))
          (buf-write-u32 h 0 (logand r0w #x3FFFFFF))
          (buf-write-u32 h 4 (+ (buf-read-u32 h 4) c0b))))))
  0)

;;; Split fe-reduce: original has let* with 30 bindings + when with 10 buf-write-u32.
;;; Do two fe-carry calls, then check+reduce in two halves.
(defun fe-reduce-check (h)
  ;; Check if h >= p by trying h + 19. Return carry out of limb 9.
  ;; Do this in-place on a copy to avoid modifying h prematurely.
  (let ((t0 (+ (buf-read-u32 h 0) 19)))
    (let ((c0 (ash t0 -26)))
      (let ((t1 (+ (buf-read-u32 h 4) c0)))
        (let ((c1 (ash t1 -25)))
          (let ((t2 (+ (buf-read-u32 h 8) c1)))
            (let ((c2 (ash t2 -26)))
              (fe-reduce-check2 h c2))))))))

(defun fe-reduce-check2 (h c2)
  (let ((t3 (+ (buf-read-u32 h 12) c2)))
    (let ((c3 (ash t3 -25)))
      (let ((t4 (+ (buf-read-u32 h 16) c3)))
        (let ((c4 (ash t4 -26)))
          (let ((t5 (+ (buf-read-u32 h 20) c4)))
            (let ((c5 (ash t5 -25)))
              (fe-reduce-check3 h c5))))))))

(defun fe-reduce-check3 (h c5)
  (let ((t6 (+ (buf-read-u32 h 24) c5)))
    (let ((c6 (ash t6 -26)))
      (let ((t7 (+ (buf-read-u32 h 28) c6)))
        (let ((c7 (ash t7 -25)))
          (let ((t8 (+ (buf-read-u32 h 32) c7)))
            (let ((c8 (ash t8 -26)))
              (let ((t9 (+ (buf-read-u32 h 36) c8)))
                (ash t9 -25)))))))))

(defun fe-reduce-apply (h)
  ;; If h >= p, subtract p by adding 19 in-place
  ;; This is safe because fe-carry already normalized the limbs
  (let ((t0 (+ (buf-read-u32 h 0) 19)))
    (let ((c0 (ash t0 -26)))
      (buf-write-u32 h 0 (logand t0 #x3FFFFFF))
      (let ((t1 (+ (buf-read-u32 h 4) c0)))
        (let ((c1 (ash t1 -25)))
          (buf-write-u32 h 4 (logand t1 #x1FFFFFF))
          (fe-reduce-apply2 h c1))))))

(defun fe-reduce-apply2 (h c1)
  (let ((t2 (+ (buf-read-u32 h 8) c1)))
    (let ((c2 (ash t2 -26)))
      (buf-write-u32 h 8 (logand t2 #x3FFFFFF))
      (let ((t3 (+ (buf-read-u32 h 12) c2)))
        (let ((c3 (ash t3 -25)))
          (buf-write-u32 h 12 (logand t3 #x1FFFFFF))
          (fe-reduce-apply3 h c3))))))

(defun fe-reduce-apply3 (h c3)
  (let ((t4 (+ (buf-read-u32 h 16) c3)))
    (let ((c4 (ash t4 -26)))
      (buf-write-u32 h 16 (logand t4 #x3FFFFFF))
      (let ((t5 (+ (buf-read-u32 h 20) c4)))
        (let ((c5 (ash t5 -25)))
          (buf-write-u32 h 20 (logand t5 #x1FFFFFF))
          (fe-reduce-apply4 h c5))))))

(defun fe-reduce-apply4 (h c5)
  (let ((t6 (+ (buf-read-u32 h 24) c5)))
    (let ((c6 (ash t6 -26)))
      (buf-write-u32 h 24 (logand t6 #x3FFFFFF))
      (let ((t7 (+ (buf-read-u32 h 28) c6)))
        (let ((c7 (ash t7 -25)))
          (buf-write-u32 h 28 (logand t7 #x1FFFFFF))
          (let ((t8 (+ (buf-read-u32 h 32) c7)))
            (let ((c8 (ash t8 -26)))
              (buf-write-u32 h 32 (logand t8 #x3FFFFFF))
              (let ((t9 (+ (buf-read-u32 h 36) c8)))
                (buf-write-u32 h 36 (logand t9 #x1FFFFFF)))))))))
  0)

(defun fe-reduce (h)
  (fe-carry h)
  (fe-carry h)
  (let ((c9 (fe-reduce-check h)))
    (when (not (zerop c9))
      (fe-reduce-apply h)))
  h)

;;; Split fe-to-bytes: original has 11 let bindings + 32 aset calls = 43 forms,
;;; well past the ~25 sequential forms limit.
(defun fe-to-bytes-lo (r fe)
  ;; Bytes 0-15 from limbs 0-4
  (let ((l0 (buf-read-u32 fe 0)) (l1 (buf-read-u32 fe 4))
        (l2 (buf-read-u32 fe 8)) (l3 (buf-read-u32 fe 12))
        (l4 (buf-read-u32 fe 16)))
    (aset r 0 (logand l0 255))
    (aset r 1 (logand (ash l0 -8) 255))
    (aset r 2 (logand (ash l0 -16) 255))
    (aset r 3 (logand (logior (ash l0 -24) (ash l1 2)) 255))
    (aset r 4 (logand (ash l1 -6) 255))
    (aset r 5 (logand (ash l1 -14) 255))
    (aset r 6 (logand (logior (ash l1 -22) (ash l2 3)) 255))
    (aset r 7 (logand (ash l2 -5) 255))
    (aset r 8 (logand (ash l2 -13) 255))
    (aset r 9 (logand (logior (ash l2 -21) (ash l3 5)) 255))
    (aset r 10 (logand (ash l3 -3) 255))
    (aset r 11 (logand (ash l3 -11) 255))
    (fe-to-bytes-lo2 r l3 l4))
  0)

(defun fe-to-bytes-lo2 (r l3 l4)
  ;; Pre-mask l4 to 2 bits: (ash l4 6) overflows 30-bit fixnums when l4 > 2^24
  (aset r 12 (logand (logior (ash l3 -19) (ash (logand l4 3) 6)) 255))
  (aset r 13 (logand (ash l4 -2) 255))
  (aset r 14 (logand (ash l4 -10) 255))
  (aset r 15 (logand (ash l4 -18) 255))
  0)

(defun fe-to-bytes-hi (r fe)
  ;; Bytes 16-31 from limbs 5-9
  (let ((l5 (buf-read-u32 fe 20)) (l6 (buf-read-u32 fe 24))
        (l7 (buf-read-u32 fe 28)) (l8 (buf-read-u32 fe 32))
        (l9 (buf-read-u32 fe 36)))
    (aset r 16 (logand l5 255))
    (aset r 17 (logand (ash l5 -8) 255))
    (aset r 18 (logand (ash l5 -16) 255))
    (aset r 19 (logand (logior (ash l5 -24) (ash l6 1)) 255))
    (aset r 20 (logand (ash l6 -7) 255))
    (aset r 21 (logand (ash l6 -15) 255))
    (aset r 22 (logand (logior (ash l6 -23) (ash l7 3)) 255))
    (aset r 23 (logand (ash l7 -5) 255))
    (aset r 24 (logand (ash l7 -13) 255))
    (aset r 25 (logand (logior (ash l7 -21) (ash l8 4)) 255))
    (aset r 26 (logand (ash l8 -4) 255))
    (aset r 27 (logand (ash l8 -12) 255))
    (fe-to-bytes-hi2 r l8 l9))
  0)

(defun fe-to-bytes-hi2 (r l8 l9)
  ;; Pre-mask l9 to 2 bits: (ash l9 6) overflows 30-bit fixnums when l9 > 2^24
  (aset r 28 (logand (logior (ash l8 -20) (ash (logand l9 3) 6)) 255))
  (aset r 29 (logand (ash l9 -2) 255))
  (aset r 30 (logand (ash l9 -10) 255))
  (aset r 31 (logand (ash l9 -18) 255))
  0)

(defun fe-to-bytes (fe)
  (fe-reduce fe)
  (let ((r (make-array 32)))
    (fe-to-bytes-lo r fe)
    (fe-to-bytes-hi r fe)
    r))

;;; Split fe-invert: original has 32 sequential forms (over ~25 limit).
;;; Split into two halves. Each helper takes a state array (1 arg) to avoid
;;; the >4 arg overflow calling convention which is broken in cross-compilation.
(defun fe-invert-lo (s)
  (let ((z (aref s 0)) (z2 (aref s 1)) (z9 (aref s 2))
        (z11 (aref s 3)) (t0 (aref s 4)) (t1 (aref s 5)))
    (fe-sq z2 z)
    (fe-sq t0 z2)
    (fe-sq t1 t0)
    (fe-mul z9 z t1)
    (fe-mul z11 z2 z9)
    (fe-sq t0 z11)
    (fe-mul t0 z9 t0)
    ;; z^(2^10-1)
    (fe-sq t1 t0) (fe-sq-iter t1 4)
    (fe-mul t1 t1 t0)
    ;; z^(2^20-1)
    (fe-sq z2 t1) (fe-sq-iter z2 9)
    (fe-mul z2 z2 t1)
    0))

(defun fe-invert-hi (s)
  (let ((z11 (aref s 3)) (z2 (aref s 1)) (z9 (aref s 2))
        (t0 (aref s 4)) (t1 (aref s 5)))
    ;; z^(2^40-1)
    (fe-sq z9 z2) (fe-sq-iter z9 19)
    (fe-mul z9 z9 z2)
    ;; z^(2^50-1)
    (fe-sq t0 z9) (fe-sq-iter t0 9)
    (fe-mul t0 t0 t1)
    ;; z^(2^100-1)
    (fe-sq t1 t0) (fe-sq-iter t1 49)
    (fe-mul t1 t1 t0)
    ;; z^(2^200-1)
    (fe-sq z2 t1) (fe-sq-iter z2 99)
    (fe-mul z2 z2 t1)
    ;; z^(2^250-1)
    (fe-sq z9 z2) (fe-sq-iter z9 49)
    (fe-mul z9 z9 t0)
    ;; z^(2^255-21)
    (fe-sq z9 z9) (fe-sq-iter z9 4)
    (fe-mul t0 z9 z11)
    0))

(defun fe-invert (z)
  (let ((s (make-array 6)))
    (let ((z2 (make-array 40)) (z9 (make-array 40))
          (z11 (make-array 40)) (t0 (make-array 40)) (t1 (make-array 40)))
      (aset s 0 z) (aset s 1 z2) (aset s 2 z9)
      (aset s 3 z11) (aset s 4 t0) (aset s 5 t1)
      (fe-invert-lo s)
      (fe-invert-hi s)
      t0)))

;;; ============================================================
;;; SSH protocol helpers — MVM-safe versions
;;; ============================================================
;;; These override deeply-nested or variable-index-ASET versions from ssh.lisp.
;;; ssh-compute-exchange-hash in ssh.lisp has 24 nested lets (>18 limit).
;;; ssh-eh-write-u32 uses variable-index ASET that needs safe wrapping.

;;; Fixed ssh-eh-write-u32: safe version (avoids aset index clobber)
(defun ssh-eh-write-u32 (buf pos val)
  (let ((b0 (logand (ash val -24) #xFF)))
    (aset buf pos b0))
  (let ((p1 (+ pos 1)))
    (let ((b1 (logand (ash val -16) #xFF)))
      (aset buf p1 b1)))
  (let ((p2 (+ pos 2)))
    (let ((b2 (logand (ash val -8) #xFF)))
      (aset buf p2 b2)))
  (let ((p3 (+ pos 3)))
    (let ((b3 (logand val #xFF)))
      (aset buf p3 b3)))
  (+ pos 4))

;;; Fixed ssh-eh-write-arr: safe array-to-array copy with let bindings
(defun ssh-eh-write-arr (buf pos src len)
  (let ((p (ssh-eh-write-u32 buf pos len)))
    (let ((j 0))
      (loop
        (when (>= j len) (return 0))
        (let ((val (aref src j)))
          (let ((dst (+ p j)))
            (aset buf dst val)))
        (setq j (+ j 1))))
    (+ p len)))

;;; Fixed ssh-eh-write-mem: copies mem[src..src+len-1] to buf[pos+4..pos+4+len-1]
(defun ssh-eh-write-mem (buf pos src len)
  (let ((p (ssh-eh-write-u32 buf pos len)))
    (let ((j 0))
      (loop
        (when (>= j len) (return 0))
        (let ((addr (+ src j)))
          (let ((val (mem-ref addr :u8)))
            (let ((dst (+ p j)))
              (aset buf dst val))))
        (setq j (+ j 1))))
    (+ p len)))

;;; Fixed ssh-put-u32: safe version for SSH string construction
(defun ssh-put-u32 (arr off val)
  (let ((b0 (logand (ash val -24) #xFF)))
    (aset arr off b0))
  (let ((o1 (+ off 1)))
    (let ((b1 (logand (ash val -16) #xFF)))
      (aset arr o1 b1)))
  (let ((o2 (+ off 2)))
    (let ((b2 (logand (ash val -8) #xFF)))
      (aset arr o2 b2)))
  (let ((o3 (+ off 3)))
    (let ((b3 (logand val #xFF)))
      (aset arr o3 b3))))

;;; Fixed ssh-concat2: safe array copy with let bindings
(defun ssh-concat2 (a a-len b b-len)
  (let ((r (make-array (+ a-len b-len))))
    (let ((j 0))
      (loop
        (when (>= j a-len) (return 0))
        (let ((val (aref a j)))
          (let ((dummy (aset r j val)))
            dummy))
        (setq j (+ j 1))))
    (let ((j 0))
      (loop
        (when (>= j b-len) (return 0))
        (let ((val (aref b j)))
          (let ((dst (+ a-len j)))
            (let ((dummy (aset r dst val)))
              dummy)))
        (setq j (+ j 1))))
    r))

;;; Fixed ssh-make-str: safe version
(defun ssh-make-str (data data-len)
  (let ((r (make-array (+ 4 data-len))))
    (ssh-put-u32 r 0 data-len)
    (let ((j 0))
      (loop
        (when (>= j data-len) (return 0))
        (let ((val (aref data j)))
          (let ((dst (+ 4 j)))
            (let ((dummy (aset r dst val)))
              dummy)))
        (setq j (+ j 1))))
    r))

;;; Fixed ssh-mem-store: safe version
(defun ssh-mem-store (addr data len)
  (let ((j 0))
    (loop
      (when (>= j len) (return 0))
      (let ((val (aref data j)))
        (let ((dst (+ addr j)))
          (setf (mem-ref dst :u8) val)))
      (setq j (+ j 1)))))

;;; Fixed ssh-mem-load: safe version
(defun ssh-mem-load (arr addr len)
  (let ((j 0))
    (loop
      (when (>= j len) (return 0))
      (let ((src (+ addr j)))
        (let ((val (mem-ref src :u8)))
          (let ((dummy (aset arr j val)))
            dummy)))
      (setq j (+ j 1)))))

;;; Flat ssh-compute-exchange-hash: max 8 nested lets (replaces 24-nested version)
(defun ssh-compute-exchange-hash (ssh cli-eph srv-eph shared-secret)
  (sha256-init)
  (let ((cb (- ssh #x20))
        (buf (make-array 2048))
        (pos 0))
    ;; V_C: client version string
    (let ((vc-len (mem-ref (+ ssh #x6D0) :u32)))
      (setq pos (ssh-eh-write-mem buf pos (+ ssh #x650) vc-len)))
    ;; V_S: server version "SSH-2.0-Modus_1.0" (17 bytes)
    (let ((vs (make-array 17)))
      (aset vs 0 83) (aset vs 1 83) (aset vs 2 72) (aset vs 3 45)
      (aset vs 4 50) (aset vs 5 46) (aset vs 6 48) (aset vs 7 45)
      (aset vs 8 77) (aset vs 9 111) (aset vs 10 100) (aset vs 11 117)
      (aset vs 12 115) (aset vs 13 95) (aset vs 14 49) (aset vs 15 46)
      (aset vs 16 48)
      (setq pos (ssh-eh-write-arr buf pos vs 17)))
    ;; I_C: client kexinit
    (let ((ic-len (mem-ref (+ ssh #x20) :u32)))
      (setq pos (ssh-eh-write-mem buf pos (+ cb #x1F00) ic-len)))
    ;; I_S: server kexinit
    (let ((is-len (mem-ref (+ ssh #x1C) :u32)))
      (setq pos (ssh-eh-write-mem buf pos (+ cb #x1700) is-len)))
    ;; K_S: host key blob
    (let ((hk-enc (ssh-encode-host-key ssh)))
      (setq pos (ssh-eh-write-arr buf pos hk-enc (array-length hk-enc))))
    ;; Q_C: client ephemeral public key
    (setq pos (ssh-eh-write-arr buf pos cli-eph 32))
    ;; Q_S: server ephemeral public key
    (setq pos (ssh-eh-write-arr buf pos srv-eph 32))
    ;; K: shared secret as mpint
    (let ((k-mpint (ssh-make-mpint shared-secret)))
      (let ((klen (array-length k-mpint)))
        (dotimes (i klen)
          (aset buf (+ pos i) (aref k-mpint i)))
        (setq pos (+ pos klen))))
    ;; Hash
    (let ((input (make-array pos)))
      (dotimes (i pos)
        (aset input i (aref buf i)))
      (sha256 input))))
