;;;; crypto-32-fast.lisp — Cons-free fe-mul/fe-sq for 32-bit targets
;;;;
;;;; Load AFTER crypto-32.lisp (last-defun-wins).
;;;;
;;;; Replaces pair-arithmetic fe-mul/fe-sq with memory-based versions.
;;;; Uses MVM mul26lo/mul26hi opcodes for hardware wide multiply.
;;;; All intermediate (hi, lo) pairs stored in scratch memory.
;;;;
;;;; Scratch memory layout at (fe-scratch-base):
;;;;   +0x00: f[0..9] + f-doubled[0..4] (15 × 4 = 60 bytes)
;;;;   +0x3C: g[0..9] (10 × 4 = 40 bytes)
;;;;   +0x64: h[0..9] 3-word (hi2/hi/lo) (10 × 12 = 120 bytes)
;;;;   +0xDC: result limbs r[0..9] (40 bytes)
;;;;
;;;; Uses 3-word accumulators to stay within 30-bit fixnum range.
;;;; Each h[k] word is kept < 2^26 via immediate carry propagation.
;;;;
;;;; fe-scratch-base is defined per architecture in arch-*.lisp

;; ================================================================
;; Read inputs to scratch memory
;; ================================================================

(defun fe-read-f-scratch (f)
  (let ((fb (+ (ash (logand f (- 0 4)) 1) 4)))
    (let ((base (fe-scratch-base)))
      (let ((i 0))
        (loop
          (when (>= i 40) (return 0))
          (setf (mem-ref (+ base i) :u32) (mem-ref (+ fb i) :u32))
          (setq i (+ i 4)))))))

(defun fe-precompute-fd ()
  (let ((base (fe-scratch-base)))
    (setf (mem-ref (+ base #x28) :u32) (* 2 (mem-ref (+ base #x04) :u32)))
    (setf (mem-ref (+ base #x2C) :u32) (* 2 (mem-ref (+ base #x0C) :u32)))
    (setf (mem-ref (+ base #x30) :u32) (* 2 (mem-ref (+ base #x14) :u32)))
    (setf (mem-ref (+ base #x34) :u32) (* 2 (mem-ref (+ base #x1C) :u32)))
    (setf (mem-ref (+ base #x38) :u32) (* 2 (mem-ref (+ base #x24) :u32)))))

(defun fe-read-g-scratch (g)
  (let ((gb (+ (ash (logand g (- 0 4)) 1) 4)))
    (let ((base (+ (fe-scratch-base) #x3C)))
      (let ((i 0))
        (loop
          (when (>= i 40) (return 0))
          (setf (mem-ref (+ base i) :u32) (mem-ref (+ gb i) :u32))
          (setq i (+ i 4)))))))

;; ================================================================
;; Multiply-accumulate using mul26lo/mul26hi opcodes
;; ================================================================
;;
;; Each fm-plain/fm-red takes (base k fi gi) where base = fe-scratch-base.
;; Addresses computed inline: f@base+fi*4, g@base+0x3C+gi*4, h@base+0x64+k*8.
;; This eliminates 6 function calls per multiply (was: fs-f-addr, fs-g-addr,
;; fs-h-addr each calling fe-scratch-base).

;; Read f[fi] from scratch
(defun fs-read-f (base fi)
  (let ((b base))
    (mem-ref (+ b (* fi 4)) :u32)))

;; Read g[gi] from scratch
(defun fs-read-g (base gi)
  (let ((b base))
    (mem-ref (+ b (+ #x3C (* gi 4))) :u32)))

;; Clear 3-word h[k] (hi2, hi, lo)
(defun fh-clear (base k)
  (let ((addr (+ base (+ #x64 (* k 12)))))
    (setf (mem-ref addr :u32) 0)
    (setf (mem-ref (+ addr 4) :u32) 0)
    (setf (mem-ref (+ addr 8) :u32) 0)))

;; Accumulate (rhi2, rhi, rlo) into 3-word h[k]
;; Each word kept < 2^26 via immediate carry propagation
(defun fh-acc-3 (base k rhi2 rhi rlo)
  (let ((b base))
    (let ((addr (+ b (+ #x64 (* k 12)))))
      (let ((lo (+ (mem-ref (+ addr 8) :u32) rlo)))
        (let ((carry-lo (ash lo -26)))
          (setf (mem-ref (+ addr 8) :u32) (logand lo 67108863))
          (let ((hi (+ (mem-ref (+ addr 4) :u32) (+ rhi carry-lo))))
            (let ((carry-hi (ash hi -26)))
              (setf (mem-ref (+ addr 4) :u32) (logand hi 67108863))
              (setf (mem-ref addr :u32)
                    (+ (mem-ref addr :u32) (+ rhi2 carry-hi))))))))))

;; Legacy 2-word fh-acc (used by diagnostic tests only)
(defun fh-acc (base k mhi mlo)
  (fh-acc-3 base k 0 mhi mlo))

;; Plain: f[fi] * g[gi] → accumulate to h[k]
(defun fm-plain (base k fi gi)
  (let ((b base))
    (let ((kk k))
      (let ((a (fs-read-f b fi)))
        (let ((bb (fs-read-g b gi)))
          (let ((mlo (mul26lo a bb)))
            (let ((mhi (mul26hi a bb)))
              (fh-acc-3 b kk 0 mhi mlo))))))))

;; Multiply (mhi, mlo) by 19 via hardware mul, accumulate to h[k]
;; Uses mul26lo/mul26hi to avoid 30-bit fixnum overflow
(defun fmul19-acc-3 (base k mhi mlo)
  (let ((b base))
    (let ((kk k))
      (let ((lo19-lo (mul26lo mlo 19)))
        (let ((lo19-hi (mul26hi mlo 19)))
          (let ((hi19-lo (mul26lo mhi 19)))
            (let ((hi19-hi (mul26hi mhi 19)))
              (let ((rhi (+ hi19-lo lo19-hi)))
                (fh-acc-3 b kk hi19-hi rhi lo19-lo)))))))))

;; Reduced: f[fi] * g[gi] * 19 → accumulate to h[k]
(defun fm-red (base k fi gi)
  (let ((b base))
    (let ((kk k))
      (let ((a (fs-read-f b fi)))
        (let ((bb (fs-read-g b gi)))
          (let ((mlo (mul26lo a bb)))
            (let ((mhi (mul26hi a bb)))
              (fmul19-acc-3 b kk mhi mlo))))))))

;; ================================================================
;; Compute h[0..9]
;; f indices: 0-9 = f0..f9, 10-14 = f1*2,f3*2,f5*2,f7*2,f9*2
;; g indices: 0-9 = g0..g9
;; ================================================================

(defun fe-compute-h0 (base)
  (let ((b base))
    (fh-clear b 0)
    (fm-plain b 0 0 0)
    (fm-red b 0 10 9)
    (fm-red b 0 2 8)
    (fm-red b 0 11 7)
    (fm-red b 0 4 6)
    (fm-red b 0 12 5)
    (fm-red b 0 6 4)
    (fm-red b 0 13 3)
    (fm-red b 0 8 2)
    (fm-red b 0 14 1)))

(defun fe-compute-h1 (base)
  (let ((b base))
    (fh-clear b 1)
    (fm-plain b 1 0 1)
    (fm-plain b 1 1 0)
    (fm-red b 1 2 9)
    (fm-red b 1 3 8)
    (fm-red b 1 4 7)
    (fm-red b 1 5 6)
    (fm-red b 1 6 5)
    (fm-red b 1 7 4)
    (fm-red b 1 8 3)
    (fm-red b 1 9 2)))

(defun fe-compute-h2 (base)
  (let ((b base))
    (fh-clear b 2)
    (fm-plain b 2 0 2)
    (fm-plain b 2 10 1)
    (fm-plain b 2 2 0)
    (fm-red b 2 11 9)
    (fm-red b 2 4 8)
    (fm-red b 2 12 7)
    (fm-red b 2 6 6)
    (fm-red b 2 13 5)
    (fm-red b 2 8 4)
    (fm-red b 2 14 3)))

(defun fe-compute-h3 (base)
  (let ((b base))
    (fh-clear b 3)
    (fm-plain b 3 0 3)
    (fm-plain b 3 1 2)
    (fm-plain b 3 2 1)
    (fm-plain b 3 3 0)
    (fm-red b 3 4 9)
    (fm-red b 3 5 8)
    (fm-red b 3 6 7)
    (fm-red b 3 7 6)
    (fm-red b 3 8 5)
    (fm-red b 3 9 4)))

(defun fe-compute-h4 (base)
  (let ((b base))
    (fh-clear b 4)
    (fm-plain b 4 0 4)
    (fm-plain b 4 10 3)
    (fm-plain b 4 2 2)
    (fm-plain b 4 11 1)
    (fm-plain b 4 4 0)
    (fm-red b 4 12 9)
    (fm-red b 4 6 8)
    (fm-red b 4 13 7)
    (fm-red b 4 8 6)
    (fm-red b 4 14 5)))

(defun fe-compute-h5 (base)
  (let ((b base))
    (fh-clear b 5)
    (fm-plain b 5 0 5)
    (fm-plain b 5 1 4)
    (fm-plain b 5 2 3)
    (fm-plain b 5 3 2)
    (fm-plain b 5 4 1)
    (fm-plain b 5 5 0)
    (fm-red b 5 6 9)
    (fm-red b 5 7 8)
    (fm-red b 5 8 7)
    (fm-red b 5 9 6)))

(defun fe-compute-h6 (base)
  (let ((b base))
    (fh-clear b 6)
    (fm-plain b 6 0 6)
    (fm-plain b 6 10 5)
    (fm-plain b 6 2 4)
    (fm-plain b 6 11 3)
    (fm-plain b 6 4 2)
    (fm-plain b 6 12 1)
    (fm-plain b 6 6 0)
    (fm-red b 6 13 9)
    (fm-red b 6 8 8)
    (fm-red b 6 14 7)))

(defun fe-compute-h7 (base)
  (let ((b base))
    (fh-clear b 7)
    (fm-plain b 7 0 7)
    (fm-plain b 7 1 6)
    (fm-plain b 7 2 5)
    (fm-plain b 7 3 4)
    (fm-plain b 7 4 3)
    (fm-plain b 7 5 2)
    (fm-plain b 7 6 1)
    (fm-plain b 7 7 0)
    (fm-red b 7 8 9)
    (fm-red b 7 9 8)))

(defun fe-compute-h8 (base)
  (let ((b base))
    (fh-clear b 8)
    (fm-plain b 8 0 8)
    (fm-plain b 8 10 7)
    (fm-plain b 8 2 6)
    (fm-plain b 8 11 5)
    (fm-plain b 8 4 4)
    (fm-plain b 8 12 3)
    (fm-plain b 8 6 2)
    (fm-plain b 8 13 1)
    (fm-plain b 8 8 0)
    (fm-red b 8 14 9)))

(defun fe-compute-h9 (base)
  (let ((b base))
    (fh-clear b 9)
    (fm-plain b 9 0 9)
    (fm-plain b 9 1 8)
    (fm-plain b 9 2 7)
    (fm-plain b 9 3 6)
    (fm-plain b 9 4 5)
    (fm-plain b 9 5 4)
    (fm-plain b 9 6 3)
    (fm-plain b 9 7 2)
    (fm-plain b 9 8 1)
    (fm-plain b 9 9 0)))

;; ================================================================
;; Carry propagation
;; ================================================================

;; Carry: 26-bit step with 3-word h[k]
(defun fc-step26 (base k)
  (let ((b base))
    (let ((addr (+ b (+ #x64 (* k 12)))))
      (let ((hi2 (mem-ref addr :u32)))
        (let ((hi (mem-ref (+ addr 4) :u32)))
          (let ((lo (mem-ref (+ addr 8) :u32)))
            (setf (mem-ref (+ b (+ #xDC (* k 4))) :u32) lo)
            (let ((naddr (+ addr 12)))
              (let ((nlo (+ (mem-ref (+ naddr 8) :u32) hi)))
                (let ((carry (ash nlo -26)))
                  (setf (mem-ref (+ naddr 8) :u32) (logand nlo 67108863))
                  (let ((nhi (+ (mem-ref (+ naddr 4) :u32) (+ hi2 carry))))
                    (let ((carry2 (ash nhi -26)))
                      (setf (mem-ref (+ naddr 4) :u32) (logand nhi 67108863))
                      (setf (mem-ref naddr :u32)
                            (+ (mem-ref naddr :u32) carry2)))))))))))))

;; Carry: 25-bit step with 3-word h[k]
(defun fc-step25 (base k)
  (let ((b base))
    (let ((addr (+ b (+ #x64 (* k 12)))))
      (let ((hi2 (mem-ref addr :u32)))
        (let ((hi (mem-ref (+ addr 4) :u32)))
          (let ((lo (mem-ref (+ addr 8) :u32)))
            (setf (mem-ref (+ b (+ #xDC (* k 4))) :u32) (logand lo 33554431))
            (let ((c-lo (ash lo -25)))
              (let ((carry-a (+ (* hi 2) c-lo)))
                (let ((naddr (+ addr 12)))
                  (let ((nlo (+ (mem-ref (+ naddr 8) :u32) carry-a)))
                    (let ((carry (ash nlo -26)))
                      (setf (mem-ref (+ naddr 8) :u32) (logand nlo 67108863))
                      (let ((nhi (+ (mem-ref (+ naddr 4) :u32) (+ (* hi2 2) carry))))
                        (let ((carry2 (ash nhi -26)))
                          (setf (mem-ref (+ naddr 4) :u32) (logand nhi 67108863))
                          (setf (mem-ref naddr :u32)
                                (+ (mem-ref naddr :u32) carry2)))))))))))))))

(defun fc-chain (base)
  (let ((b base))
    (fc-step26 b 0)
    (fc-step25 b 1)
    (fc-step26 b 2)
    (fc-step25 b 3)
    (fc-step26 b 4)
    (fc-step25 b 5)
    (fc-step26 b 6)
    (fc-step25 b 7)
    (fc-step26 b 8)))

;; Wrap carry from h[9] back to r[0]*19
(defun fc-wrap (base)
  (let ((b base))
    (let ((addr (+ b (+ #x64 (* 9 12)))))
      (let ((hi2 (mem-ref addr :u32)))
        (let ((hi (mem-ref (+ addr 4) :u32)))
          (let ((lo (mem-ref (+ addr 8) :u32)))
            (let ((r-base (+ b #xDC)))
              (setf (mem-ref (+ r-base 36) :u32) (logand lo 33554431))
              (let ((c-lo (ash lo -25)))
                (fc-wrap-mul b hi2 hi c-lo)))))))))

(defun fc-wrap-mul (base hi2 hi c-lo)
  (let ((b base))
    (let ((carry-a (+ (* hi 2) c-lo)))
      (let ((c19-lo (mul26lo carry-a 19)))
        (let ((c19-hi (mul26hi carry-a 19)))
          (let ((carry-b38 (* hi2 38)))
            (let ((r-base (+ b #xDC)))
              (let ((r0 (+ (mem-ref r-base :u32) c19-lo)))
                (let ((c0 (ash r0 -26)))
                  (setf (mem-ref r-base :u32) (logand r0 67108863))
                  (setf (mem-ref (+ r-base 4) :u32)
                        (+ (mem-ref (+ r-base 4) :u32)
                           (+ c0 (+ c19-hi carry-b38)))))))))))))

(defun fc-write-dst (base dst)
  (let ((b base))
    (let ((db (+ (ash (logand dst (- 0 4)) 1) 4)))
      (let ((r-base (+ b #xDC)))
        (let ((i 0))
          (loop
            (when (>= i 40) (return 0))
            (setf (mem-ref (+ db i) :u32) (mem-ref (+ r-base i) :u32))
            (setq i (+ i 4))))))))

(defun fe-carry-fast (base dst)
  (let ((b base))
    (let ((d dst))
      (fc-chain b)
      (fc-wrap b)
      (fc-write-dst b d))))

;; ================================================================
;; Override fe-mul and fe-sq
;; ================================================================

(defun fe-mul (dst f g)
  (let ((d dst))
    (let ((ff f))
      (let ((gg g))
        (let ((b (fe-scratch-base)))
          (fe-read-f-scratch ff)
          (fe-precompute-fd)
          (fe-read-g-scratch gg)
          (fe-mul-inner b d))))))

(defun fe-mul-inner (base dst)
  (let ((b base))
    (let ((d dst))
      (fe-compute-h0 b)
      (fe-compute-h1 b)
      (fe-compute-h2 b)
      (fe-compute-h3 b)
      (fe-compute-h4 b)
      (fe-compute-h5 b)
      (fe-compute-h6 b)
      (fe-compute-h7 b)
      (fe-compute-h8 b)
      (fe-compute-h9 b)
      (fe-carry-fast b d)
      d)))

(defun fe-sq (dst f)
  (fe-mul dst f f))

;; ================================================================
;; Direct memory access overrides (32-bit, 4-byte object header)
;; Replace buf-read-u32 / buf-write-u32 with mem-ref :u32
;; Base formula: (+ (ash (logand fe (- 0 4)) 1) 4) → data byte 0
;; ================================================================

(defun fe-copy (dst src)
  (let ((db (+ (ash (logand dst (- 0 4)) 1) 4)))
    (let ((sb (+ (ash (logand src (- 0 4)) 1) 4)))
      (setf (mem-ref db :u32) (mem-ref sb :u32))
      (setf (mem-ref (+ db 4) :u32) (mem-ref (+ sb 4) :u32))
      (setf (mem-ref (+ db 8) :u32) (mem-ref (+ sb 8) :u32))
      (setf (mem-ref (+ db 12) :u32) (mem-ref (+ sb 12) :u32))
      (setf (mem-ref (+ db 16) :u32) (mem-ref (+ sb 16) :u32))
      (setf (mem-ref (+ db 20) :u32) (mem-ref (+ sb 20) :u32))
      (setf (mem-ref (+ db 24) :u32) (mem-ref (+ sb 24) :u32))
      (setf (mem-ref (+ db 28) :u32) (mem-ref (+ sb 28) :u32))
      (setf (mem-ref (+ db 32) :u32) (mem-ref (+ sb 32) :u32))
      (setf (mem-ref (+ db 36) :u32) (mem-ref (+ sb 36) :u32))))
  dst)

(defun fe-add (dst a b)
  (let ((db (+ (ash (logand dst (- 0 4)) 1) 4)))
    (let ((ab (+ (ash (logand a (- 0 4)) 1) 4)))
      (let ((bb (+ (ash (logand b (- 0 4)) 1) 4)))
        (setf (mem-ref db :u32) (+ (mem-ref ab :u32) (mem-ref bb :u32)))
        (setf (mem-ref (+ db 4) :u32) (+ (mem-ref (+ ab 4) :u32) (mem-ref (+ bb 4) :u32)))
        (setf (mem-ref (+ db 8) :u32) (+ (mem-ref (+ ab 8) :u32) (mem-ref (+ bb 8) :u32)))
        (setf (mem-ref (+ db 12) :u32) (+ (mem-ref (+ ab 12) :u32) (mem-ref (+ bb 12) :u32)))
        (setf (mem-ref (+ db 16) :u32) (+ (mem-ref (+ ab 16) :u32) (mem-ref (+ bb 16) :u32)))
        (setf (mem-ref (+ db 20) :u32) (+ (mem-ref (+ ab 20) :u32) (mem-ref (+ bb 20) :u32)))
        (setf (mem-ref (+ db 24) :u32) (+ (mem-ref (+ ab 24) :u32) (mem-ref (+ bb 24) :u32)))
        (setf (mem-ref (+ db 28) :u32) (+ (mem-ref (+ ab 28) :u32) (mem-ref (+ bb 28) :u32)))
        (setf (mem-ref (+ db 32) :u32) (+ (mem-ref (+ ab 32) :u32) (mem-ref (+ bb 32) :u32)))
        (setf (mem-ref (+ db 36) :u32) (+ (mem-ref (+ ab 36) :u32) (mem-ref (+ bb 36) :u32))))))
  dst)

(defun fe-sub (dst a b)
  (let ((d dst))
    (let ((db (+ (ash (logand d (- 0 4)) 1) 4)))
      (let ((ab (+ (ash (logand a (- 0 4)) 1) 4)))
        (let ((bb (+ (ash (logand b (- 0 4)) 1) 4)))
          (setf (mem-ref db :u32) (+ (- (mem-ref ab :u32) (mem-ref bb :u32)) 134217690))
          (setf (mem-ref (+ db 4) :u32) (+ (- (mem-ref (+ ab 4) :u32) (mem-ref (+ bb 4) :u32)) 67108862))
          (setf (mem-ref (+ db 8) :u32) (+ (- (mem-ref (+ ab 8) :u32) (mem-ref (+ bb 8) :u32)) 134217726))
          (setf (mem-ref (+ db 12) :u32) (+ (- (mem-ref (+ ab 12) :u32) (mem-ref (+ bb 12) :u32)) 67108862))
          (setf (mem-ref (+ db 16) :u32) (+ (- (mem-ref (+ ab 16) :u32) (mem-ref (+ bb 16) :u32)) 134217726))
          (setf (mem-ref (+ db 20) :u32) (+ (- (mem-ref (+ ab 20) :u32) (mem-ref (+ bb 20) :u32)) 67108862))
          (setf (mem-ref (+ db 24) :u32) (+ (- (mem-ref (+ ab 24) :u32) (mem-ref (+ bb 24) :u32)) 134217726))
          (setf (mem-ref (+ db 28) :u32) (+ (- (mem-ref (+ ab 28) :u32) (mem-ref (+ bb 28) :u32)) 67108862))
          (setf (mem-ref (+ db 32) :u32) (+ (- (mem-ref (+ ab 32) :u32) (mem-ref (+ bb 32) :u32)) 134217726))
          (setf (mem-ref (+ db 36) :u32) (+ (- (mem-ref (+ ab 36) :u32) (mem-ref (+ bb 36) :u32)) 67108862)))))
    (fe-carry d)))

;; fe-carry helpers using mem-ref :u32
(defun fe-carry-m-even (hb off cin)
  (let ((v (+ (mem-ref (+ hb off) :u32) cin)))
    (setf (mem-ref (+ hb off) :u32) (logand v #x3FFFFFF))
    (ash v -26)))

(defun fe-carry-m-odd (hb off cin)
  (let ((v (+ (mem-ref (+ hb off) :u32) cin)))
    (setf (mem-ref (+ hb off) :u32) (logand v #x1FFFFFF))
    (ash v -25)))

(defun fe-carry (h)
  (let ((hb (+ (ash (logand h (- 0 4)) 1) 4)))
    (let ((c (fe-carry-m-even hb 0 0)))
      (setq c (fe-carry-m-odd hb 4 c))
      (setq c (fe-carry-m-even hb 8 c))
      (setq c (fe-carry-m-odd hb 12 c))
      (setq c (fe-carry-m-even hb 16 c))
      (setq c (fe-carry-m-odd hb 20 c))
      (setq c (fe-carry-m-even hb 24 c))
      (setq c (fe-carry-m-odd hb 28 c))
      (setq c (fe-carry-m-even hb 32 c))
      (setq c (fe-carry-m-odd hb 36 c))
      ;; Wrap: c * 19 back to limb 0
      (let ((r0w (+ (mem-ref hb :u32) (* c 19))))
        (setf (mem-ref hb :u32) (logand r0w #x3FFFFFF))
        (setf (mem-ref (+ hb 4) :u32)
              (+ (mem-ref (+ hb 4) :u32) (ash r0w -26))))))
  h)

;; fe-reduce helpers using mem-ref :u32
(defun fe-reduce-m-check (hb)
  (let ((t0 (+ (mem-ref hb :u32) 19)))
    (let ((c (ash t0 -26)))
      (let ((t1 (+ (mem-ref (+ hb 4) :u32) c)))
        (setq c (ash t1 -25))
        (let ((t2 (+ (mem-ref (+ hb 8) :u32) c)))
          (setq c (ash t2 -26))
          (fe-reduce-m-check2 hb c))))))

(defun fe-reduce-m-check2 (hb cin)
  (let ((h hb))
    (let ((c cin))
      (let ((t3 (+ (mem-ref (+ h 12) :u32) c)))
        (setq c (ash t3 -25))
        (let ((t4 (+ (mem-ref (+ h 16) :u32) c)))
          (setq c (ash t4 -26))
          (let ((t5 (+ (mem-ref (+ h 20) :u32) c)))
            (setq c (ash t5 -25))
            (fe-reduce-m-check3 h c)))))))

(defun fe-reduce-m-check3 (hb cin)
  (let ((h hb))
    (let ((c cin))
      (let ((t6 (+ (mem-ref (+ h 24) :u32) c)))
        (setq c (ash t6 -26))
        (let ((t7 (+ (mem-ref (+ h 28) :u32) c)))
          (setq c (ash t7 -25))
          (let ((t8 (+ (mem-ref (+ h 32) :u32) c)))
            (setq c (ash t8 -26))
            (let ((t9 (+ (mem-ref (+ h 36) :u32) c)))
              (ash t9 -25))))))))

(defun fe-reduce-m-apply (hb)
  (let ((h hb))
    (let ((t0 (+ (mem-ref h :u32) 19)))
      (let ((c (ash t0 -26)))
        (setf (mem-ref h :u32) (logand t0 #x3FFFFFF))
        (let ((t1 (+ (mem-ref (+ h 4) :u32) c)))
          (setq c (ash t1 -25))
          (setf (mem-ref (+ h 4) :u32) (logand t1 #x1FFFFFF))
          (let ((t2 (+ (mem-ref (+ h 8) :u32) c)))
            (setq c (ash t2 -26))
            (setf (mem-ref (+ h 8) :u32) (logand t2 #x3FFFFFF))
            (fe-reduce-m-apply2 h c)))))))

(defun fe-reduce-m-apply2 (hb cin)
  (let ((h hb))
    (let ((c cin))
      (let ((t3 (+ (mem-ref (+ h 12) :u32) c)))
        (setq c (ash t3 -25))
        (setf (mem-ref (+ h 12) :u32) (logand t3 #x1FFFFFF))
        (let ((t4 (+ (mem-ref (+ h 16) :u32) c)))
          (setq c (ash t4 -26))
          (setf (mem-ref (+ h 16) :u32) (logand t4 #x3FFFFFF))
          (let ((t5 (+ (mem-ref (+ h 20) :u32) c)))
            (setq c (ash t5 -25))
            (setf (mem-ref (+ h 20) :u32) (logand t5 #x1FFFFFF))
            (fe-reduce-m-apply3 h c)))))))

(defun fe-reduce-m-apply3 (hb cin)
  (let ((h hb))
    (let ((c cin))
      (let ((t6 (+ (mem-ref (+ h 24) :u32) c)))
        (setq c (ash t6 -26))
        (setf (mem-ref (+ h 24) :u32) (logand t6 #x3FFFFFF))
        (let ((t7 (+ (mem-ref (+ h 28) :u32) c)))
          (setq c (ash t7 -25))
          (setf (mem-ref (+ h 28) :u32) (logand t7 #x1FFFFFF))
          (let ((t8 (+ (mem-ref (+ h 32) :u32) c)))
            (setq c (ash t8 -26))
            (setf (mem-ref (+ h 32) :u32) (logand t8 #x3FFFFFF))
            (let ((t9 (+ (mem-ref (+ h 36) :u32) c)))
              (setf (mem-ref (+ h 36) :u32) (logand t9 #x1FFFFFF)))))))))

(defun fe-reduce (h)
  (let ((hh h))
    (fe-carry hh)
    (fe-carry hh)
    (let ((hb (+ (ash (logand hh (- 0 4)) 1) 4)))
      (when (not (zerop (fe-reduce-m-check hb)))
        (fe-reduce-m-apply hb)))
    hh))

(defun fe-from-int (n)
  (let ((fe (make-array 40)))
    (dotimes (i 40) (aset fe i 0))
    (let ((fb (+ (ash (logand fe (- 0 4)) 1) 4)))
      (setf (mem-ref fb :u32) (logand n #x3FFFFFF))
      (setf (mem-ref (+ fb 4) :u32) (logand (ash n -26) #x1FFFFFF)))
    fe))

(defun fe-store-fixed (fe addr)
  (let ((fb (+ (ash (logand fe (- 0 4)) 1) 4)))
    (let ((a addr))
      (let ((off 0))
        (dotimes (i 10)
          (setf (mem-ref (+ a off) :u32) (mem-ref (+ fb off) :u32))
          (setq off (+ off 4)))))))

(defun fe-load-fixed (dst addr)
  (let ((db (+ (ash (logand dst (- 0 4)) 1) 4)))
    (let ((a addr))
      (let ((off 0))
        (dotimes (i 10)
          (setf (mem-ref (+ db off) :u32) (mem-ref (+ a off) :u32))
          (setq off (+ off 4)))))))

;; fe-from-bytes: read raw bytes, write limbs via mem-ref :u32
;; Split into two halves to stay under form count limits
(defun fe-from-bytes (bytes)
  (let ((b bytes))
    (let ((fe (make-array 40)))
      (let ((fb (+ (ash (logand fe (- 0 4)) 1) 4)))
        (fe-from-bytes-lo fb b)
        (fe-from-bytes-hi fb b))
      fe)))

;; Helper: merge 4 values with logior, avoiding 4-level nesting
;; which clobbers on i386 (4 GPRs)
(defun fb-merge4 (a b c d)
  (let ((aa a))
    (let ((bb b))
      (let ((ab (logior aa bb)))
        (let ((cc c))
          (let ((abc (logior ab cc)))
            (let ((dd d))
              (logior abc dd))))))))

(defun fe-from-bytes-lo (fb bytes)
  (let ((f fb))
    (let ((b bytes))
      (let ((l0 (fb-merge4 (aref b 0) (ash (aref b 1) 8)
                            (ash (aref b 2) 16) (ash (logand (aref b 3) #x03) 24))))
        (setf (mem-ref f :u32) l0))
      (let ((l1 (fb-merge4 (ash (aref b 3) -2) (ash (aref b 4) 6)
                            (ash (aref b 5) 14) (ash (logand (aref b 6) #x07) 22))))
        (setf (mem-ref (+ f 4) :u32) l1))
      (fe-from-bytes-lo2 f b))))

(defun fe-from-bytes-lo2 (fb bytes)
  (let ((f fb))
    (let ((b bytes))
      (let ((l2 (fb-merge4 (ash (aref b 6) -3) (ash (aref b 7) 5)
                            (ash (aref b 8) 13) (ash (logand (aref b 9) #x1F) 21))))
        (setf (mem-ref (+ f 8) :u32) l2))
      (let ((l3 (fb-merge4 (ash (aref b 9) -5) (ash (aref b 10) 3)
                            (ash (aref b 11) 11) (ash (logand (aref b 12) #x3F) 19))))
        (setf (mem-ref (+ f 12) :u32) l3))
      (let ((l4 (fb-merge4 (ash (aref b 12) -6) (ash (aref b 13) 2)
                            (ash (aref b 14) 10) (ash (aref b 15) 18))))
        (setf (mem-ref (+ f 16) :u32) l4)))))

(defun fe-from-bytes-hi (fb bytes)
  (let ((f fb))
    (let ((b bytes))
      (let ((l5 (fb-merge4 (aref b 16) (ash (aref b 17) 8)
                            (ash (aref b 18) 16) (ash (logand (aref b 19) #x01) 24))))
        (setf (mem-ref (+ f 20) :u32) l5))
      (let ((l6 (fb-merge4 (ash (aref b 19) -1) (ash (aref b 20) 7)
                            (ash (aref b 21) 15) (ash (logand (aref b 22) #x07) 23))))
        (setf (mem-ref (+ f 24) :u32) l6))
      (fe-from-bytes-hi2 f b))))

(defun fe-from-bytes-hi2 (fb bytes)
  (let ((f fb))
    (let ((b bytes))
      (let ((l7 (fb-merge4 (ash (aref b 22) -3) (ash (aref b 23) 5)
                            (ash (aref b 24) 13) (ash (logand (aref b 25) #x0F) 21))))
        (setf (mem-ref (+ f 28) :u32) l7))
      (let ((l8 (fb-merge4 (ash (aref b 25) -4) (ash (aref b 26) 4)
                            (ash (aref b 27) 12) (ash (logand (aref b 28) #x3F) 20))))
        (setf (mem-ref (+ f 32) :u32) l8))
      (let ((l9raw (fb-merge4 (ash (aref b 28) -6) (ash (aref b 29) 2)
                               (ash (aref b 30) 10) (ash (aref b 31) 18))))
        (let ((l9 (logand l9raw #x1FFFFFF)))
          (setf (mem-ref (+ f 36) :u32) l9))))))

;; fe-to-bytes: read limbs via mem-ref :u32, write raw bytes
;; Split into two halves; uses 30-bit-safe shifts (pre-mask before ash l4/l9)
(defun fe-to-bytes (fe)
  (let ((f fe))
    (fe-reduce f)
    (let ((r (make-array 32)))
      (let ((fb (+ (ash (logand f (- 0 4)) 1) 4)))
        (fe-to-bytes-lo r fb)
        (fe-to-bytes-hi r fb))
      r)))

;; Helper: merge two partial byte values with logior + mask to 0xFF
;; Avoids nested logior/logand/ash which clobbers on i386 (4 GPRs)
(defun tb-merge (a b)
  (let ((aa a))
    (let ((bb b))
      (logand (logior aa bb) #xFF))))

(defun fe-to-bytes-lo (r fb)
  (let ((rr r))
    (let ((f fb))
      (let ((l0 (mem-ref f :u32))
            (l1 (mem-ref (+ f 4) :u32)))
        (aset rr 0 (logand l0 #xFF))
        (aset rr 1 (logand (ash l0 -8) #xFF))
        (aset rr 2 (logand (ash l0 -16) #xFF))
        (let ((b3 (tb-merge (ash l0 -24) (ash l1 2))))
          (aset rr 3 b3))
        (aset rr 4 (logand (ash l1 -6) #xFF))
        (aset rr 5 (logand (ash l1 -14) #xFF))
        (fe-to-bytes-lo2 rr f)))))

(defun fe-to-bytes-lo2 (r fb)
  (let ((rr r))
    (let ((f fb))
      (let ((l2 (mem-ref (+ f 8) :u32))
            (l1 (mem-ref (+ f 4) :u32)))
        (let ((b6 (tb-merge (ash l1 -22) (ash l2 3))))
          (aset rr 6 b6))
        (aset rr 7 (logand (ash l2 -5) #xFF))
        (aset rr 8 (logand (ash l2 -13) #xFF))
        (fe-to-bytes-lo3 rr f)))))

(defun fe-to-bytes-lo3 (r fb)
  (let ((rr r))
    (let ((f fb))
      (let ((l2 (mem-ref (+ f 8) :u32))
            (l3 (mem-ref (+ f 12) :u32)))
        (let ((b9 (tb-merge (ash l2 -21) (ash l3 5))))
          (aset rr 9 b9))
        (aset rr 10 (logand (ash l3 -3) #xFF))
        (aset rr 11 (logand (ash l3 -11) #xFF))
        (let ((l4 (mem-ref (+ f 16) :u32)))
          (let ((l4lo (logand l4 #x03)))
            (let ((b12 (tb-merge (ash l3 -19) (ash l4lo 6))))
              (aset rr 12 b12)))
          (aset rr 13 (logand (ash l4 -2) #xFF))
          (aset rr 14 (logand (ash l4 -10) #xFF))
          (aset rr 15 (logand (ash l4 -18) #xFF)))))))

(defun fe-to-bytes-hi (r fb)
  (let ((rr r))
    (let ((f fb))
      (let ((l5 (mem-ref (+ f 20) :u32))
            (l6 (mem-ref (+ f 24) :u32)))
        (aset rr 16 (logand l5 #xFF))
        (aset rr 17 (logand (ash l5 -8) #xFF))
        (aset rr 18 (logand (ash l5 -16) #xFF))
        (let ((b19 (tb-merge (ash l5 -24) (ash l6 1))))
          (aset rr 19 b19))
        (aset rr 20 (logand (ash l6 -7) #xFF))
        (aset rr 21 (logand (ash l6 -15) #xFF))
        (fe-to-bytes-hi2 rr f)))))

(defun fe-to-bytes-hi2 (r fb)
  (let ((rr r))
    (let ((f fb))
      (let ((l6 (mem-ref (+ f 24) :u32))
            (l7 (mem-ref (+ f 28) :u32)))
        (let ((b22 (tb-merge (ash l6 -23) (ash l7 3))))
          (aset rr 22 b22))
        (aset rr 23 (logand (ash l7 -5) #xFF))
        (aset rr 24 (logand (ash l7 -13) #xFF))
        (fe-to-bytes-hi3 rr f)))))

(defun fe-to-bytes-hi3 (r fb)
  (let ((rr r))
    (let ((f fb))
      (let ((l7 (mem-ref (+ f 28) :u32))
            (l8 (mem-ref (+ f 32) :u32)))
        (let ((b25 (tb-merge (ash l7 -21) (ash l8 4))))
          (aset rr 25 b25))
        (aset rr 26 (logand (ash l8 -4) #xFF))
        (aset rr 27 (logand (ash l8 -12) #xFF))
        (let ((l9 (mem-ref (+ f 36) :u32)))
          (let ((l9lo (logand l9 #x03)))
            (let ((b28 (tb-merge (ash l8 -20) (ash l9lo 6))))
              (aset rr 28 b28)))
          (aset rr 29 (logand (ash l9 -2) #xFF))
          (aset rr 30 (logand (ash l9 -10) #xFF))
          (aset rr 31 (logand (ash l9 -18) #xFF)))))))

;; ================================================================
;; x25519 and fe-invert overrides
;; Split into small functions to stay under MVM compiler limits
;; (original has 20-binding let and 25+ sequential forms)
;; ================================================================

(defun fe-sq-iter (dst n)
  (dotimes (i n)
    (fe-sq dst dst)))

;;; fe-invert split into 3 parts to stay under 25 sequential forms
(defun fe-invert-p1 (z z2 z9 z11 t0 t1)
  (let ((zz z))
    (let ((zz2 z2))
      (let ((zz9 z9))
        (let ((zz11 z11))
          (let ((tt0 t0))
            (let ((tt1 t1))
              (fe-sq zz2 zz)
              (fe-sq tt0 zz2)
              (fe-sq tt1 tt0)
              (fe-mul zz9 zz tt1)
              (fe-mul zz11 zz2 zz9)
              (fe-sq tt0 zz11)
              (fe-mul tt0 zz9 tt0)
              (fe-sq tt1 tt0)
              (fe-sq-iter tt1 4)
              (fe-mul tt1 tt1 tt0)
              (fe-sq zz2 tt1)
              (fe-sq-iter zz2 9)
              (fe-mul zz2 zz2 tt1))))))))

(defun fe-invert-p2 (z2 z9 t0 t1)
  (let ((zz2 z2))
    (let ((zz9 z9))
      (let ((tt0 t0))
        (let ((tt1 t1))
          (fe-sq zz9 zz2)
          (fe-sq-iter zz9 19)
          (fe-mul zz9 zz9 zz2)
          (fe-sq tt0 zz9)
          (fe-sq-iter tt0 9)
          (fe-mul tt0 tt0 tt1)
          (fe-sq tt1 tt0)
          (fe-sq-iter tt1 49)
          (fe-mul tt1 tt1 tt0)
          (fe-sq zz2 tt1)
          (fe-sq-iter zz2 99)
          (fe-mul zz2 zz2 tt1))))))

(defun fe-invert-p3 (z2 z9 z11 t0)
  (let ((zz2 z2))
    (let ((zz9 z9))
      (let ((zz11 z11))
        (let ((tt0 t0))
          (fe-sq zz9 zz2)
          (fe-sq-iter zz9 49)
          (fe-mul zz9 zz9 tt0)
          (fe-sq zz9 zz9)
          (fe-sq-iter zz9 4)
          (fe-mul tt0 zz9 zz11)
          tt0)))))

(defun fe-invert (z)
  (let ((zz z))
    (let ((z2 (make-array 40)))
      (let ((z9 (make-array 40)))
        (let ((z11 (make-array 40)))
          (let ((t0 (make-array 40)))
            (let ((t1 (make-array 40)))
              (fe-invert-p1 zz z2 z9 z11 t0 t1)
              (fe-invert-p2 z2 z9 t0 t1)
              (fe-invert-p3 z2 z9 z11 t0))))))))

;;; x25519 context: array of 18 pointers to fe arrays
;;; ctx[0]=kc, [1]=x1, [2]=x2, [3]=z2, [4]=x3, [5]=z3,
;;; [6]=a, [7]=aa, [8]=b, [9]=bb, [10]=fe-e, [11]=c,
;;; [12]=d, [13]=da, [14]=cb, [15]=t1, [16]=t2, [17]=a24
(defun x25-alloc-ctx ()
  (let ((ctx (make-array 18)))
    (aset ctx 0 (make-array 32))
    (x25-alloc-ctx2 ctx)))

(defun x25-alloc-ctx2 (ctx)
  (let ((c ctx))
    (let ((i 1))
      (loop
        (when (> i 17) (return c))
        (aset c i (make-array 40))
        (setq i (+ i 1))))))

(defun x25-ladder-step (ctx)
  (let ((c ctx))
    (let ((x2 (aref c 2)))
      (let ((z2 (aref c 3)))
        (let ((x3 (aref c 4)))
          (let ((z3 (aref c 5)))
            (let ((a (aref c 6)))
              (let ((aa (aref c 7)))
                (let ((b (aref c 8)))
                  (let ((bb (aref c 9)))
                    (fe-add a x2 z2)
                    (fe-sq aa a)
                    (fe-sub b x2 z2)
                    (fe-sq bb b)
                    (x25-step-mid c)))))))))))

(defun x25-step-mid (ctx)
  (let ((c ctx))
    (let ((x3 (aref c 4)))
      (let ((z3 (aref c 5)))
        (let ((aa (aref c 7)))
          (let ((bb (aref c 9)))
            (let ((fe-e (aref c 10)))
              (let ((cc (aref c 11)))
                (let ((d (aref c 12)))
                  (fe-sub fe-e aa bb)
                  (fe-add cc x3 z3)
                  (fe-sub d x3 z3)
                  (fe-mul (aref c 13) d (aref c 6))
                  (fe-mul (aref c 14) cc (aref c 8))
                  (x25-step-fin c))))))))))

(defun x25-step-fin (ctx)
  (let ((c ctx))
    (let ((t1 (aref c 15)))
      (let ((da (aref c 13)))
        (let ((cb (aref c 14)))
          (let ((t2 (aref c 16)))
            (fe-add t1 da cb)
            (fe-sq (aref c 4) t1)
            (fe-sub t1 da cb)
            (fe-sq t2 t1)
            (fe-mul (aref c 5) (aref c 1) t2)
            (fe-mul (aref c 2) (aref c 7) (aref c 9))
            (fe-mul t1 (aref c 17) (aref c 10))
            (fe-add t2 (aref c 7) t1)
            (fe-mul (aref c 3) (aref c 10) t2)))))))

(defun x25-cswap (ctx)
  (let ((c ctx))
    (let ((t1 (aref c 15)))
      (fe-copy t1 (aref c 2))
      (fe-copy (aref c 2) (aref c 4))
      (fe-copy (aref c 4) t1)
      (fe-copy t1 (aref c 3))
      (fe-copy (aref c 3) (aref c 5))
      (fe-copy (aref c 5) t1))))

(defun x25-get-bit (kc pos)
  (let ((k kc))
    (let ((p pos))
      (let ((byte-idx (ash p -3)))
        (let ((bit-idx (logand p 7)))
          (let ((byte-val (aref k byte-idx)))
            (let ((mask (ash 1 bit-idx)))
              (if (zerop (logand byte-val mask)) 0 1))))))))

(defun x25-loop-iter (ctx kc swap pos)
  (let ((c ctx))
    (let ((k kc))
      (let ((s swap))
        (let ((p pos))
          (let ((kt (x25-get-bit k p)))
            (when (not (= kt s))
              (x25-cswap c))
            (setq s kt)
            (x25-ladder-step c)
            s))))))

(defun x25-loop (ctx kc)
  (let ((c ctx))
    (let ((k kc))
      (let ((swap 0))
        (let ((pos 254))
          (dotimes (iter 255)
            (setq swap (x25-loop-iter c k swap pos))
            (setq pos (- pos 1)))
          (x25-loop-fin c swap))))))

(defun x25-loop-fin (ctx swap)
  (let ((c ctx))
    (when (not (zerop swap))
      (x25-cswap c))
    (fe-mul (aref c 15) (aref c 2) (fe-invert (aref c 3)))
    (fe-to-bytes (aref c 15))))

(defun x25-init (ctx k u)
  (let ((c ctx))
    (let ((kk k))
      (let ((uu u))
        (let ((kc (aref c 0)))
          (dotimes (i 32) (aset kc i (aref kk i)))
          (aset kc 0 (logand (aref kc 0) 248))
          (aset kc 31 (logand (aref kc 31) 127))
          (aset kc 31 (logior (aref kc 31) 64))
          (fe-copy (aref c 1) (fe-from-bytes uu))
          (x25-init2 c kc))))))

(defun x25-init2 (ctx kc)
  (let ((c ctx))
    (let ((k kc))
      (let ((x2 (aref c 2)))
        (let ((z2 (aref c 3)))
          (let ((z3 (aref c 5)))
            (let ((a24 (aref c 17)))
              (dotimes (i 40) (aset x2 i 0))
              (let ((x2b (+ (ash (logand x2 (- 0 4)) 1) 4)))
                (setf (mem-ref x2b :u32) 1))
              (dotimes (i 40) (aset z2 i 0))
              (fe-copy (aref c 4) (aref c 1))
              (dotimes (i 40) (aset z3 i 0))
              (let ((z3b (+ (ash (logand z3 (- 0 4)) 1) 4)))
                (setf (mem-ref z3b :u32) 1))
              (dotimes (i 40) (aset a24 i 0))
              (let ((a24b (+ (ash (logand a24 (- 0 4)) 1) 4)))
                (setf (mem-ref a24b :u32) 121665))
              k)))))))

(defun x25519 (k u)
  (let ((ctx (x25-alloc-ctx)))
    (let ((kc (x25-init ctx k u)))
      (x25-loop ctx kc))))
