;;;; mvm-ssh-fixes.lisp - Safe overrides for MVM-compiled SSH
;;;;
;;;; Fixes variable-index ASET/AREF register clobber bugs in ssh.lisp functions.
;;;; The MVM compiler's x64 translator clobbers registers when aset/aref have
;;;; computed index expressions like (aset arr (+ off i) val). These overrides
;;;; use explicit let bindings to avoid the clobber.
;;;;
;;;; Also includes arena-based crypto overrides to prevent heap exhaustion
;;;; during Ed25519 operations (fe-pow-sqrt, ed-recover-x generate ~2MB garbage).
;;;;
;;;; Must load AFTER ssh.lisp and aarch64-overrides.lisp (last-defun-wins).

;;; Fixed buf-write-u32: original has (aset buf (+ off N) val) variable-index bug.
;;; This is CRITICAL because SHA-256/SHA-512 use buf-write-u32 throughout.
(defun buf-write-u32-helper (buf off v0 v1 v2 v3)
  (aset buf off v0)
  (let ((o1 (+ off 1)))
    (aset buf o1 v1))
  (let ((o2 (+ off 2)))
    (aset buf o2 v2))
  (let ((o3 (+ off 3)))
    (aset buf o3 v3)))
(defun buf-write-u32 (buf off val)
  (let ((v0 (logand (ash val -24) #xFF)))
    (let ((v1 (logand (ash val -16) #xFF)))
      (let ((v2 (logand (ash val -8) #xFF)))
        (let ((v3 (logand val #xFF)))
          (buf-write-u32-helper buf off v0 v1 v2 v3))))))

;;; Fixed buf-copy-mac: original has (aset buf (+ dest-off i) ...) variable-index bug
(defun buf-copy-mac (buf dest-off src-addr)
  (dotimes (i 6)
    (let ((dst (+ dest-off i)))
      (let ((val (mem-ref (+ src-addr i) :u8)))
        (aset buf dst val)))))

;;; Fixed concat-bytes: original has (aset r (+ a-len i) (aref b i)) bug
(defun concat-bytes (a a-len b b-len)
  (let ((r (make-array (+ a-len b-len))))
    (let ((j 0))
      (loop
        (when (>= j a-len) (return 0))
        (let ((val (aref a j)))
          (let ((dummy (aset r j val))) dummy))
        (setq j (+ j 1))))
    (let ((j 0))
      (loop
        (when (>= j b-len) (return 0))
        (let ((val (aref b j)))
          (let ((dst (+ a-len j)))
            (let ((dummy (aset r dst val))) dummy)))
        (setq j (+ j 1))))
    r))

;;; Fixed concat3-bytes: original has variable-index ASET bugs
(defun concat3-bytes (a al b bl c clen)
  (let ((r (make-array (+ (+ al bl) clen))))
    (let ((j 0))
      (loop
        (when (>= j al) (return 0))
        (let ((val (aref a j)))
          (let ((dummy (aset r j val))) dummy))
        (setq j (+ j 1))))
    (let ((j 0))
      (loop
        (when (>= j bl) (return 0))
        (let ((val (aref b j)))
          (let ((dst (+ al j)))
            (let ((dummy (aset r dst val))) dummy)))
        (setq j (+ j 1))))
    (let ((j 0))
      (loop
        (when (>= j clen) (return 0))
        (let ((val (aref c j)))
          (let ((dst (+ (+ al bl) j)))
            (let ((dummy (aset r dst val))) dummy)))
        (setq j (+ j 1))))
    r))

;;; Flat helper: combine 4 values with logior (avoids nested expression clobber)
(defun flat-logior4 (a b c d)
  (let ((lo (logior a b)))
    (let ((mid (logior lo c)))
      (logior mid d))))

;;; Helper: safe mem-to-array copy
(defun safe-copy-mem-to-arr (arr base len)
  (let ((j 0))
    (loop
      (when (>= j len) (return 0))
      (let ((addr (+ base j)))
        (let ((val (mem-ref addr :u8)))
          (aset arr j val)))
      (setq j (+ j 1)))))

;;; Helper: safe array-to-array copy with offset
(defun poly-safe-copy (dst src offset len)
  (let ((j 0))
    (loop
      (when (>= j len) (return 0))
      (let ((idx (+ offset j)))
        (let ((val (aref src idx)))
          (aset dst j val)))
      (setq j (+ j 1)))))

;;; Fixed ssh-put-u32: safe version (original uses aset with computed index)
(defun ssh-put-u32 (arr off val)
  (let ((b0 (logand (ash val -24) #xFF)))
    (aset arr off b0))
  (let ((o1 (+ off 1)))
    (let ((b1 (logand (ash val -16) #xFF)))
      (aset arr o1 b1)))
  (let ((o2 (+ off 2)))
    (let ((b2 (logand (ash val -8) #xFF)))
      (aset arr o2 b2)))
  (let ((o3 (+ off 3)))
    (let ((b3 (logand val #xFF)))
      (aset arr o3 b3))))

;;; Fixed ssh-get-u32: use flat-logior4 to avoid nested logior clobber
(defun ssh-get-u32 (arr off)
  (let ((b0 (aref arr off)))
    (let ((b1 (aref arr (+ off 1))))
      (let ((b2 (aref arr (+ off 2))))
        (let ((b3 (aref arr (+ off 3))))
          (flat-logior4 (ash b0 24) (ash b1 16) (ash b2 8) b3))))))

;;; Fixed ssh-concat2: safe array copy with let bindings
(defun ssh-concat2 (a a-len b b-len)
  (let ((r (make-array (+ a-len b-len))))
    (let ((j 0))
      (loop
        (when (>= j a-len) (return 0))
        (let ((val (aref a j)))
          (let ((dummy (aset r j val)))
            dummy))
        (setq j (+ j 1))))
    (let ((j 0))
      (loop
        (when (>= j b-len) (return 0))
        (let ((val (aref b j)))
          (let ((dst (+ a-len j)))
            (let ((dummy (aset r dst val)))
              dummy)))
        (setq j (+ j 1))))
    r))

;;; Fixed ssh-make-str: safe version
(defun ssh-make-str (data data-len)
  (let ((r (make-array (+ 4 data-len))))
    (ssh-put-u32 r 0 data-len)
    (let ((j 0))
      (loop
        (when (>= j data-len) (return 0))
        (let ((val (aref data j)))
          (let ((dst (+ 4 j)))
            (let ((dummy (aset r dst val)))
              dummy)))
        (setq j (+ j 1))))
    r))

;;; Fixed ssh-make-mpint: original uses 3-arg + in (+ 4 need-zero i)
(defun ssh-make-mpint (bytes)
  (let ((start 0))
    (let ((done 0))
      (loop
        (if (< start 32)
            (if (zerop (aref bytes start))
                (if (zerop done) (setq start (+ start 1)) (return ()))
                (progn (setq done 1) (return ())))
            (return ()))))
    (let ((sig-len (- 32 start))
          (need-zero 0))
      (when (> sig-len 0)
        (when (not (zerop (logand (aref bytes start) #x80)))
          (setq need-zero 1)))
      (let ((total (+ sig-len need-zero)))
        (let ((r (make-array (+ 4 total))))
          (ssh-put-u32 r 0 total)
          (when need-zero (aset r 4 0))
          (let ((base (+ 4 need-zero)))
            (dotimes (i sig-len)
              (let ((src-idx (+ start i)))
                (let ((val (aref bytes src-idx)))
                  (let ((dst-idx (+ base i)))
                    (aset r dst-idx val))))))
          r)))))

;;; Fixed ssh-mem-store: safe version
(defun ssh-mem-store (addr data len)
  (let ((j 0))
    (loop
      (when (>= j len) (return 0))
      (let ((val (aref data j)))
        (let ((dst (+ addr j)))
          (setf (mem-ref dst :u8) val)))
      (setq j (+ j 1)))))

;;; Fixed ssh-mem-load: safe version
(defun ssh-mem-load (arr addr len)
  (let ((j 0))
    (loop
      (when (>= j len) (return 0))
      (let ((src (+ addr j)))
        (let ((val (mem-ref src :u8)))
          (let ((dummy (aset arr j val)))
            dummy)))
      (setq j (+ j 1)))))

;;; Fixed ssh-buf-to-array: safe mem-to-array copy
(defun ssh-buf-to-array (ssh len)
  (let ((arr (make-array len))
        (base (+ ssh #x6D8)))
    (safe-copy-mem-to-arr arr base len)
    arr))

;;; Fixed ssh-buf-consume: safe byte-by-byte shift
(defun ssh-buf-consume (ssh n)
  (let ((buf-len (mem-ref (+ ssh #x6D4) :u32)))
    (let ((remaining (- buf-len n)))
      (when (> remaining 0)
        (let ((dst (+ ssh #x6D8))
              (src (+ (+ ssh #x6D8) n)))
          (let ((j 0))
            (loop
              (when (>= j remaining) (return 0))
              (let ((src-addr (+ src j)))
                (let ((val (mem-ref src-addr :u8)))
                  (let ((dst-addr (+ dst j)))
                    (setf (mem-ref dst-addr :u8) val))))
              (setq j (+ j 1))))))
      (setf (mem-ref (+ ssh #x6D4) :u32) remaining)
      remaining)))

;;; Fixed buf-read-u16-mem: flat version
(defun buf-read-u16-mem (addr off)
  (let ((a0 (+ addr off)))
    (let ((hi (mem-ref a0 :u8)))
      (let ((lo (mem-ref (+ a0 1) :u8)))
        (logior (ash hi 8) lo)))))

;;; Safe chacha20-crypt: avoids register clobber in inner loop
(defun chacha20-crypt-block (result data ks base data-len)
  (let ((i 0))
    (loop
      (when (>= i 64) (return 0))
      (let ((idx (+ base i)))
        (when (< idx data-len)
          (let ((dv (aref data idx)))
            (let ((kv (aref ks i)))
              (let ((xv (logxor dv kv)))
                (aset result idx xv))))))
      (setq i (+ i 1)))))

(defun chacha20-crypt (key nonce data data-len counter)
  (let ((result (make-array data-len))
        (block-num 0))
    (loop
      (when (not (< (* block-num 64) data-len)) (return ()))
      (let ((ks (chacha-block key nonce (+ counter block-num))))
        (let ((base (* block-num 64)))
          (chacha20-crypt-block result data ks base data-len)))
      (setq block-num (+ block-num 1)))
    result))

;;; Safe ssh-derive-key: uses safe ssh-concat2 (avoids deeply nested lets)
(defun ssh-derive-key (ssh key-id needed-len)
  (let ((k-arr (make-array 32)))
    (ssh-mem-load k-arr (+ ssh #x070) 32)
    (let ((k-mpint (ssh-make-mpint k-arr)))
      (let ((h (make-array 32)))
        (ssh-mem-load h (+ ssh #x050) 32)
        (let ((id (make-array 1)))
          (aset id 0 key-id)
          (let ((sid (make-array 32)))
            (ssh-mem-load sid (+ ssh #x030) 32)
            (let ((p1 (ssh-concat2 k-mpint (array-length k-mpint)
                                    h 32)))
              (let ((p2 (ssh-concat2 p1 (array-length p1) id 1)))
                (let ((p3 (ssh-concat2 p2 (array-length p2) sid 32)))
                  (let ((k1 (sha256 p3 (array-length p3))))
                    (if (> needed-len 32)
                        (let ((p4 (ssh-concat2 k-mpint (array-length k-mpint)
                                                h 32)))
                          (let ((p5 (ssh-concat2 p4 (array-length p4) k1 32)))
                            (let ((k2 (sha256 p5 (array-length p5))))
                              (ssh-concat2 k1 32 k2 32))))
                        k1)))))))))))

;;; Arena-based fe-pow-sqrt: prevents heap exhaustion
(defun fe-pow-sqrt (u)
  (let ((z2 (make-array 40))
        (z9 (make-array 40))
        (z11 (make-array 40))
        (t0 (make-array 40))
        (t1 (make-array 40)))
    (let ((arena-save (get-alloc-ptr)))
      (fe-sq z2 u)
      (fe-sq t0 z2)
      (fe-sq t1 t0)
      (fe-mul z9 u t1)
      (fe-mul z11 z2 z9)
      (fe-sq t0 z11)
      (fe-mul t0 z9 t0)
      (set-alloc-ptr arena-save)
      (fe-sq t1 t0) (fe-sq-iter t1 4)
      (fe-mul t1 t1 t0)
      (set-alloc-ptr arena-save)
      (fe-sq z2 t1) (fe-sq-iter z2 9)
      (fe-mul z2 z2 t1)
      (set-alloc-ptr arena-save)
      (fe-sq z9 z2) (fe-sq-iter z9 19)
      (fe-mul z9 z9 z2)
      (set-alloc-ptr arena-save)
      (fe-sq t0 z9) (fe-sq-iter t0 9)
      (fe-mul t0 t0 t1)
      (set-alloc-ptr arena-save)
      (fe-sq t1 t0) (fe-sq-iter t1 49)
      (fe-mul t1 t1 t0)
      (set-alloc-ptr arena-save)
      (fe-sq z2 t1) (fe-sq-iter z2 99)
      (fe-mul z2 z2 t1)
      (set-alloc-ptr arena-save)
      (fe-sq z9 z2) (fe-sq-iter z9 49)
      (fe-mul z9 z9 t0)
      (set-alloc-ptr arena-save)
      (fe-sq z9 z9)
      (fe-mul z9 z9 u)
      (fe-sq t0 z9)
      t0)))

;;; Arena-based ed-recover-x
(defun ed-recover-x (y sign)
  (let ((d-fe (make-array 40))
        (y2 (make-array 40))
        (y2m1 (make-array 40))
        (dy2 (make-array 40))
        (dy2p1 (make-array 40))
        (u (make-array 40))
        (x (make-array 40))
        (x2 (make-array 40))
        (sm (make-array 40)))
    (let ((arena-save (get-alloc-ptr)))
      (fe-load-fixed d-fe (+ (e1000-state-base) #x500))
      (fe-sq y2 y)
      (fe-sub y2m1 y2 (fe-from-int 1))
      (fe-mul dy2 d-fe y2)
      (fe-add dy2p1 dy2 (fe-from-int 1))
      (set-alloc-ptr arena-save)
      (fe-mul u y2m1 (fe-invert dy2p1))
      (set-alloc-ptr arena-save)
      (fe-copy x (fe-pow-sqrt u))
      (set-alloc-ptr arena-save)
      (fe-sq x2 x)
      (when (zerop (fe-equal x2 u))
        (fe-load-fixed sm (+ (e1000-state-base) #x578))
        (fe-mul x x sm))
      (set-alloc-ptr arena-save)
      (let ((xb (fe-to-bytes x)))
        (let ((x-odd (logand (aref xb 0) 1)))
          (if sign
              (when (zerop x-odd)
                (fe-sub x (fe-from-int 0) x))
              (unless (zerop x-odd)
                (fe-sub x (fe-from-int 0) x)))))
      (set-alloc-ptr arena-save)
      x)))

;;; Safe ssh-dispatch-msg and helpers
(defun ssh-dispatch-svc (ssh payload svc-len)
  (let ((svc (make-array 32)))
    (poly-safe-copy svc payload 5 svc-len)
    (ssh-send-service-accept ssh svc svc-len)))

(defun ssh-dispatch-exec (ssh payload cmd-off flag-addr)
  (let ((cmd-len (ssh-get-u32 payload cmd-off)))
    (let ((cmd (make-array cmd-len)))
      (let ((cmd-data-off (+ cmd-off 4)))
        (poly-safe-copy cmd payload cmd-data-off cmd-len))
      (ssh-eval-line ssh cmd cmd-len)
      (ssh-dispatch-exec-close ssh flag-addr))))

(defun ssh-dispatch-exec-close (ssh flag-addr)
  (let ((cli-chan (mem-ref (+ ssh #x18) :u32)))
    (let ((eof-msg (make-array 5)))
      (aset eof-msg 0 96)
      (ssh-put-u32 eof-msg 1 cli-chan)
      (ssh-send-payload ssh eof-msg 5))
    (let ((close-msg (make-array 5)))
      (aset close-msg 0 97)
      (ssh-put-u32 close-msg 1 cli-chan)
      (ssh-send-payload ssh close-msg 5)))
  (setf (mem-ref flag-addr :u32) 0))

(defun ssh-dispatch-chanreq (ssh payload flag-addr)
  (let ((rtype-len (ssh-get-u32 payload 5)))
    (let ((want-reply-off (+ 9 rtype-len)))
      (let ((want-reply (aref payload want-reply-off)))
        (when (not (zerop want-reply))
          (ssh-send-channel-success ssh
           (mem-ref (+ ssh #x18) :u32)))))
    (when (eq rtype-len 5)
      (when (eq (aref payload 9) 115)
        (ssh-send-prompt ssh)))
    (when (eq rtype-len 4)
      (when (eq (aref payload 9) 101)
        (let ((cmd-off (+ 10 rtype-len)))
          (ssh-dispatch-exec ssh payload cmd-off flag-addr))))))

(defun ssh-dispatch-eof-close (ssh flag-addr)
  (let ((cli-chan (mem-ref (+ ssh #x18) :u32)))
    (let ((eof-msg (make-array 5)))
      (aset eof-msg 0 96)
      (ssh-put-u32 eof-msg 1 cli-chan)
      (ssh-send-payload ssh eof-msg 5))
    (let ((close-msg (make-array 5)))
      (aset close-msg 0 97)
      (ssh-put-u32 close-msg 1 cli-chan)
      (ssh-send-payload ssh close-msg 5)))
  (setf (mem-ref flag-addr :u32) 0))

(defun ssh-dispatch-msg (ssh payload plen flag-addr)
  (let ((msg-type (aref payload 0)))
    (when (eq msg-type 5)
      (let ((svc-len (ssh-get-u32 payload 1)))
        (ssh-dispatch-svc ssh payload svc-len)))
    (when (eq msg-type 50)
      (ssh-handle-userauth ssh payload plen))
    (when (eq msg-type 90)
      (let ((ctype-len (ssh-get-u32 payload 1)))
        (let ((cli-chan (ssh-get-u32 payload (+ 5 ctype-len))))
          (setf (mem-ref (+ ssh #x18) :u32) cli-chan)
          (setf (mem-ref (+ ssh #x14) :u32) 0)
          (ssh-send-channel-confirm ssh cli-chan 0))))
    (when (eq msg-type 98)
      (ssh-dispatch-chanreq ssh payload flag-addr))
    (when (eq msg-type 94)
      (ssh-handle-channel-data ssh payload plen))
    (when (eq msg-type 96)
      (ssh-dispatch-eof-close ssh flag-addr))
    (when (eq msg-type 97)
      (setf (mem-ref flag-addr :u32) 0))
    (when (eq msg-type 1)
      (setf (mem-ref flag-addr :u32) 0))))

;;; Channel data handling (cd-* functions)
(defun cd-init-edit-state ()
  (edit-set-line-len 0)
  (edit-set-cursor-pos 0))

(defun cd-setup-capture ()
  (let ((base (ssh-ipc-base)))
    (setf (mem-ref (+ base #x12A00) :u64) 1)
    (setf (mem-ref (+ base #x14) :u32) 3)
    (setf (mem-ref (+ base #x18) :u32) 0)))

(defun cd-do-enter (ssh)
  (let ((s ssh))
    (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 0)
    (ssh-flush-output s)
    (cd-send-newline s)
    (ssh-do-eval s)
    (cd-send-prompt s)
    (cd-reinit-edit)))

(defun cd-send-newline (ssh)
  (let ((s ssh))
    (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 3)
    (setf (mem-ref (+ (ssh-ipc-base) #x18) :u32) 0)
    (write-byte 10)
    (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 0)
    (ssh-flush-output s)))

(defun cd-send-prompt (ssh)
  (let ((s ssh))
    (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 3)
    (setf (mem-ref (+ (ssh-ipc-base) #x18) :u32) 0)
    (emit-prompt)
    (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 0)
    (ssh-flush-output s)))

(defun cd-reinit-edit ()
  (edit-set-line-len 0)
  (edit-set-cursor-pos 0)
  (setf (mem-ref (+ (ssh-ipc-base) #x12810) :u64) 0)
  (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 3)
  (setf (mem-ref (+ (ssh-ipc-base) #x18) :u32) 0))

(defun cd-process-one (s p i)
  (let ((byte (aref p (+ 9 i))))
    (let ((rc (handle-edit-byte byte)))
      (if (eq rc 1) (cd-do-enter s) ()))))

(defun cd-process-bytes (ssh payload data-len)
  (let ((s ssh))
    (let ((p payload))
      (let ((dlen data-len))
        (let ((i 0))
          (loop
            (if (< i dlen)
                (progn
                  (cd-process-one s p i)
                  (setq i (+ i 1)))
                (return 0))))))))

(defun cd-channel-finish (ssh)
  (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 0)
  (ssh-flush-output ssh)
  (setf (mem-ref (+ (ssh-ipc-base) #x12A00) :u64) 0))

(defun ssh-handle-channel-data (ssh payload plen)
  (let ((s ssh))
    (let ((p payload))
      (let ((data-len (ssh-get-u32 p 5)))
        (cd-init-edit-state)
        (cd-setup-capture)
        (cd-process-bytes s p data-len)
        (cd-channel-finish s)))))

(defun cd-copy-capture-buf (out out-len)
  (let ((base (+ (ssh-ipc-base) #x100)))
    (dotimes (i out-len)
      (aset out i (mem-ref (+ base i) :u8)))))

(defun cd-flush-eval-output (ssh)
  (let ((s ssh))
    (let ((out-len (mem-ref (+ (ssh-ipc-base) #x18) :u32)))
      (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 0)
      (when (> out-len 0)
        (let ((out (make-array out-len)))
          (cd-copy-capture-buf out out-len)
          (ssh-send-string s out out-len))))))

(defun cd-eval-and-print (ssh)
  (let ((s ssh))
    (let ((lst (buf-read-list)))
      (let ((globals (ssh-get-globals)))
        (let ((result (eval-sexp lst nil globals)))
          (setf (mem-ref (+ (ssh-ipc-base) #x14) :u32) 3)
          (setf (mem-ref (+ (ssh-ipc-base) #x18) :u32) 0)
          (write-byte 10)
          (write-byte 61) (write-byte 32)
          (ssh-print-sexp result)
          (write-byte 10)
          (cd-flush-eval-output s))))))

(defun ssh-do-eval-expr (ssh)
  (let ((s ssh))
    (let ((len (edit-line-len)))
      (setf (mem-ref (+ (ssh-ipc-base) #x20) :u32) 1)
      (setf (mem-ref (+ (ssh-ipc-base) #x24) :u32) len)
      (cd-eval-and-print s))))

;;; le-u32: safe little-endian u32 assembly (avoids nested logior clobber)
(defun le-u32 (b0 b1 b2 b3)
  (let ((lo (logior b0 (ash b1 8))))
    (let ((hi (logior (ash b2 16) (ash b3 24))))
      (logior lo hi))))

;;; Safe chacha-setup: original uses nested logior which silently clobbers
(defun chacha-setup-load-key (s key)
  (dotimes (i 8)
    (let ((j (* i 4)))
      (let ((b0 (aref key j)))
        (let ((b1 (aref key (+ j 1))))
          (let ((b2 (aref key (+ j 2))))
            (let ((b3 (aref key (+ j 3))))
              (let ((val (le-u32 b0 b1 b2 b3)))
                (let ((soff (+ 16 j)))
                  (buf-write-u32 s soff val))))))))))
(defun chacha-setup-load-nonce (s nonce)
  (dotimes (i 3)
    (let ((j (* i 4)))
      (let ((b0 (aref nonce j)))
        (let ((b1 (aref nonce (+ j 1))))
          (let ((b2 (aref nonce (+ j 2))))
            (let ((b3 (aref nonce (+ j 3))))
              (let ((val (le-u32 b0 b1 b2 b3)))
                (let ((soff (+ 52 j)))
                  (buf-write-u32 s soff val))))))))))
(defun chacha-setup (key nonce counter)
  (let ((s (make-array 64)))
    (buf-write-u32 s 0 #x61707865)
    (buf-write-u32 s 4 #x3320646e)
    (buf-write-u32 s 8 #x79622d32)
    (buf-write-u32 s 12 #x6b206574)
    (chacha-setup-load-key s key)
    (buf-write-u32 s 48 counter)
    (chacha-setup-load-nonce s nonce)
    s))

;;; Safe chacha-block: uses safe output writing
(defun chacha-block-write-word (out off sum)
  (let ((v0 (logand sum #xFF)))
    (let ((v1 (logand (ash sum -8) #xFF)))
      (let ((v2 (logand (ash sum -16) #xFF)))
        (let ((v3 (logand (ash sum -24) #xFF)))
          (buf-write-u32-helper out off v0 v1 v2 v3))))))

(defun chacha-block-output (out work state)
  (dotimes (i 16)
    (let ((off (* i 4)))
      (let ((wv (buf-read-u32 work off)))
        (let ((sv (buf-read-u32 state off)))
          (let ((sum (logand (+ wv sv) #xFFFFFFFF)))
            (chacha-block-write-word out off sum)))))))

(defun chacha-block (key nonce counter)
  (let ((state (chacha-setup key nonce counter))
        (work (make-array 64)))
    (dotimes (i 64)
      (aset work i (aref state i)))
    (chacha-inner work)
    (let ((out (make-array 64)))
      (chacha-block-output out work state)
      out)))

;;; Split fe-invert: original has 32 sequential forms (>25 limit → miscompile)
;;; Ported from fixpoint's proven split implementation.
(defun fe-invert-lo (s)
  (let ((z (aref s 0)) (z2 (aref s 1)) (z9 (aref s 2))
        (z11 (aref s 3)) (t0 (aref s 4)) (t1 (aref s 5)))
    (fe-sq z2 z)
    (fe-sq t0 z2)
    (fe-sq t1 t0)
    (fe-mul z9 z t1)
    (fe-mul z11 z2 z9)
    (fe-sq t0 z11)
    (fe-mul t0 z9 t0)
    (fe-sq t1 t0) (fe-sq-iter t1 4)
    (fe-mul t1 t1 t0)
    (fe-sq z2 t1) (fe-sq-iter z2 9)
    (fe-mul z2 z2 t1)
    0))

(defun fe-invert-hi (s)
  (let ((z11 (aref s 3)) (z2 (aref s 1)) (z9 (aref s 2))
        (t0 (aref s 4)) (t1 (aref s 5)))
    (fe-sq z9 z2) (fe-sq-iter z9 19)
    (fe-mul z9 z9 z2)
    (fe-sq t0 z9) (fe-sq-iter t0 9)
    (fe-mul t0 t0 t1)
    (fe-sq t1 t0) (fe-sq-iter t1 49)
    (fe-mul t1 t1 t0)
    (fe-sq z2 t1) (fe-sq-iter z2 99)
    (fe-mul z2 z2 t1)
    (fe-sq z9 z2) (fe-sq-iter z9 49)
    (fe-mul z9 z9 t0)
    (fe-sq z9 z9) (fe-sq-iter z9 4)
    (fe-mul t0 z9 z11)
    0))

(defun fe-invert (z)
  (let ((s (make-array 6)))
    (let ((z2 (make-array 40)) (z9 (make-array 40))
          (z11 (make-array 40)) (t0 (make-array 40)) (t1 (make-array 40)))
      (aset s 0 z) (aset s 1 z2) (aset s 2 z9)
      (aset s 3 z11) (aset s 4 t0) (aset s 5 t1)
      (fe-invert-lo s)
      (fe-invert-hi s)
      t0)))

;;; Split ed-add: original has 20 let bindings (>18 limit) + 21 sequential forms
;;; Ported from fixpoint's proven split implementation.
(defun ed-add-compute (p q)
  (let ((x1 (car (car p))) (y1 (cdr (car p)))
        (z1 (car (cdr p))) (t1 (cdr (cdr p))))
    (let ((x2 (car (car q))) (y2 (cdr (car q)))
          (z2 (car (cdr q))) (t2 (cdr (cdr q))))
      (let ((w0 (make-array 40)) (w1 (make-array 40))
            (w2 (make-array 40)) (w3 (make-array 40)))
        (let ((w4 (make-array 40)) (w5 (make-array 40)))
          (fe-sub w0 y1 x1) (fe-sub w1 y2 x2)
          (fe-mul w2 w0 w1)
          (fe-add w0 y1 x1) (fe-add w1 y2 x2)
          (fe-mul w3 w0 w1)
          (fe-load-fixed w0 (+ (e1000-state-base) #x500))
          (fe-add w0 w0 w0)
          (fe-mul w0 t1 w0) (fe-mul w4 w0 t2)
          (fe-mul w5 z1 z2) (fe-add w5 w5 w5)
          (ed-add-finish w2 w3 w4 w5))))))

(defun ed-add-finish (w2 w3 w4 w5)
  (let ((w6 (make-array 40)) (w7 (make-array 40)))
    (let ((rx (make-array 40)) (ry (make-array 40))
          (rz (make-array 40)) (rt (make-array 40)))
      (fe-sub w6 w3 w2) (fe-sub w7 w5 w4)
      (let ((w0g (make-array 40)) (w1h (make-array 40)))
        (fe-add w0g w5 w4) (fe-add w1h w3 w2)
        (fe-mul rx w6 w7) (fe-mul ry w0g w1h)
        (fe-mul rt w6 w1h) (fe-mul rz w7 w0g)
        (cons (cons rx ry) (cons rz rt))))))

(defun ed-add (p q)
  (ed-add-compute p q))

;;; Split ed-double: original has 12 let bindings + 17 sequential forms
;;; Ported from fixpoint's proven split implementation.
(defun ed-double-ab (x1 y1 z1 out)
  (let ((a (make-array 40)) (b (make-array 40)))
    (fe-sq a x1)
    (fe-sq b y1)
    (let ((c (make-array 40)))
      (fe-sq c z1)
      (fe-add c c c)
      (let ((dd (make-array 40)) (e (make-array 40)))
        (fe-sub dd (fe-from-int 0) a)
        (fe-add e x1 y1)
        (fe-sq e e)
        (fe-sub e e a)
        (fe-sub e e b)
        (cons a (cons b (cons c (cons dd e))))))))

(defun ed-double-finish (pack)
  (let ((a (car pack)) (b (car (cdr pack)))
        (c (car (cdr (cdr pack)))))
    (let ((dd (car (cdr (cdr (cdr pack)))))
          (e (cdr (cdr (cdr (cdr pack))))))
      (let ((g (make-array 40)) (f (make-array 40))
            (h (make-array 40)))
        (fe-add g dd b)
        (fe-sub f g c)
        (fe-sub h dd b)
        (let ((rx (make-array 40)) (ry (make-array 40))
              (rz (make-array 40)) (rt (make-array 40)))
          (fe-mul rx e f)
          (fe-mul ry g h)
          (fe-mul rt e h)
          (fe-mul rz f g)
          (cons (cons rx ry) (cons rz rt)))))))

(defun ed-double (p)
  (let ((x1 (car (car p)))
        (y1 (cdr (car p)))
        (z1 (car (cdr p))))
    (let ((pack (ed-double-ab x1 y1 z1 0)))
      (ed-double-finish pack))))

;;; Split ed-scalar-mult: unrolled byte processing avoids deep loop nesting
;;; Ported from fixpoint's proven implementation.
(defun ed-scalar-mult-byte (result temp scalar byte-idx)
  (let ((byte-val (aref scalar byte-idx)))
    (let ((b0 (logand byte-val 1)))
      (let ((r0 (if (not (zerop b0)) (ed-add result temp) result)))
        (let ((t0 (ed-double temp)))
          (let ((b1 (logand byte-val 2)))
            (let ((r1 (if (not (zerop b1)) (ed-add r0 t0) r0)))
              (let ((t1 (ed-double t0)))
                (let ((b2 (logand byte-val 4)))
                  (let ((r2 (if (not (zerop b2)) (ed-add r1 t1) r1)))
                    (let ((t2 (ed-double t1)))
                      (let ((b3 (logand byte-val 8)))
                        (let ((r3 (if (not (zerop b3)) (ed-add r2 t2) r2)))
                          (let ((t3 (ed-double t2)))
                            (ed-scalar-mult-byte2 r3 t3 byte-val)))))))))))))))

(defun ed-scalar-mult-byte2 (result temp byte-val)
  (let ((b4 (logand byte-val 16)))
    (let ((r4 (if (not (zerop b4)) (ed-add result temp) result)))
      (let ((t4 (ed-double temp)))
        (let ((b5 (logand byte-val 32)))
          (let ((r5 (if (not (zerop b5)) (ed-add r4 t4) r4)))
            (let ((t5 (ed-double t4)))
              (let ((b6 (logand byte-val 64)))
                (let ((r6 (if (not (zerop b6)) (ed-add r5 t5) r5)))
                  (let ((t6 (ed-double t5)))
                    (let ((b7 (logand byte-val 128)))
                      (let ((r7 (if (not (zerop b7)) (ed-add r6 t6) r6)))
                        (let ((t7 (ed-double t6)))
                          (cons r7 t7))))))))))))))

(defun ed-scalar-mult-loop (result temp scalar i)
  (if (>= i 32)
      result
      (let ((pair (ed-scalar-mult-byte result temp scalar i)))
        (ed-scalar-mult-loop (car pair) (cdr pair) scalar (+ i 1)))))

(defun ed-scalar-mult (scalar point)
  (let ((s scalar))
    (let ((p point))
      (let ((result (cons (cons (fe-from-int 0) (fe-from-int 1))
                          (cons (fe-from-int 1) (fe-from-int 0)))))
        (ed-scalar-mult-loop result p s 0)))))

;;; Safe ed25519-sign-fast: uses safe-copy-mem-to-arr
(defun ed25519-sign-fast (message msg-len)
  (let ((state (e1000-state-base)))
    (let ((s (make-array 32)))
      (safe-copy-mem-to-arr s (+ state #x680) 32)
      (let ((prefix (make-array 32)))
        (safe-copy-mem-to-arr prefix (+ state #x6A0) 32)
        (let ((a-enc (make-array 32)))
          (safe-copy-mem-to-arr a-enc (+ state #x730) 32)
          (let ((r-input (concat-bytes prefix 32 message msg-len)))
            (let ((r (ed-reduce-scalar (sha512 r-input))))
              (let ((r-enc (ed-encode-point (ed-base-mult r))))
                (let ((k-input (concat3-bytes r-enc 32 a-enc 32 message msg-len)))
                  (let ((k (ed-reduce-scalar (sha512 k-input))))
                    (let ((ks (ed-scalar-mult-mod-l k s)))
                      (let ((sig-s (ed-scalar-add r ks)))
                        (concat-bytes r-enc 32 sig-s 32)))))))))))))
