;;;; x86-ssh-overrides.lisp - Single-threaded SSH overrides for x86-64
;;;;
;;;; The MVM x64 translator emits NOP for YIELD, so actor scheduling
;;;; doesn't work. These overrides replace actor-based SSH with a
;;;; single-threaded model where net-actor-main runs directly.
;;;;
;;;; Extracted from aarch64-overrides.lisp (portable Lisp, not arch-specific).

;; Override receive: poll E1000 directly instead of actor mailbox
(defun receive ()
  (loop
    (io-delay)
    (let ((pkt-len (e1000-receive)))
      (when (not (zerop pkt-len))
        (let ((buf (e1000-rx-buf)))
          (let ((et-hi (mem-ref (+ buf 12) :u8))
                (et-lo (mem-ref (+ buf 13) :u8)))
            (if (eq et-hi #x08)
                (if (eq et-lo #x06)
                    (let ((arp-op (buf-read-u16-mem buf 20)))
                      (when (eq arp-op 1)
                        (arp-reply buf)))
                    (when (eq et-lo 0)
                      ;; Learn source MAC as gateway MAC
                      (let ((st (e1000-state-base)))
                        (dotimes (m 6)
                          (setf (mem-ref (+ st (+ #x28 m)) :u8)
                                (mem-ref (+ buf (+ 6 m)) :u8))))
                      (let ((proto (mem-ref (+ buf 23) :u8)))
                        (if (eq proto 1)
                            (icmp-handle buf 14)
                            (when (eq proto 6)
                              (net-handle-tcp buf pkt-len))))))
                ()))
          1))))
  1)

;; Override ssh-server for single-threaded x86
(defun ssh-server (port)
  (ssh-seed-random)
  (ssh-init-strings)
  (init-gc-helper)
  (when (zerop (mem-ref (+ (e1000-state-base) #x624) :u32))
    (ssh-use-default-key))
  (write-byte 83) (write-byte 83) (write-byte 72)
  (write-byte 58) (print-dec port) (write-byte 10)
  ;; Store listen port
  (setf (mem-ref (+ (ssh-ipc-base) #x60438) :u32) port)
  ;; Clear connection table
  (let ((i 0))
    (loop
      (when (>= i 4) (return 0))
      (setf (mem-ref (conn-base i) :u32) 0)
      (setq i (+ i 1))))
  ;; Single-threaded: run network loop directly (never returns)
  (net-actor-main))

;; Override ssh-connection-handler: no actor-exit
(defun ssh-connection-handler (conn)
  (let ((ssh (conn-ssh conn))
        (cb (conn-base conn)))
    (ssh-handle-connection ssh)
    (tcp-close-conn cb)
    (conn-free conn)))

;; Override ssh-handle-connection for single-threaded operation
(defun ssh-handle-connection (ssh)
  (let ((cb (- ssh #x20)))
    (ssh-send-version ssh)
    (when (zerop (ssh-receive-version ssh))
      (return ()))
    (let ((kexinit (ssh-build-kexinit ssh)))
      (ssh-send-payload ssh kexinit (array-length kexinit)))
    (let ((cli-kex (ssh-receive-packet ssh 100)))
      (when (zerop cli-kex) (return ()))
      (let ((cli-kex-payload (car cli-kex)))
        (when (not (eq (aref cli-kex-payload 0) 20)) (return ()))
        (ssh-mem-store (+ cb #x1F00) cli-kex-payload (cdr cli-kex))
        (setf (mem-ref (+ ssh #x20) :u32) (cdr cli-kex))
        (let ((kex-init (ssh-receive-packet ssh 100)))
          (when (zerop kex-init) (return ()))
          (let ((kex-payload (car kex-init)))
            (when (not (eq (aref kex-payload 0) 30)) (return ()))
            (ssh-handle-kex ssh kex-payload (cdr kex-init))
            (ssh-send-newkeys ssh)
            (let ((nk (ssh-receive-packet ssh 100)))
              (when (zerop nk) (return ()))
              (when (not (eq (aref (car nk) 0) 21)) (return ()))
              (ssh-derive-keys ssh)
              (ssh-message-loop ssh))))))))

;; Message dispatch - flat when chain
(defun ssh-dispatch-msg (ssh payload plen flag-addr)
  (let ((msg-type (aref payload 0)))
    (when (eq msg-type 5)
      (let ((svc-len (ssh-get-u32 payload 1))
            (svc (make-array 32)))
        (dotimes (i svc-len)
          (aset svc i (aref payload (+ 5 i))))
        (ssh-send-service-accept ssh svc svc-len)))
    (when (eq msg-type 50)
      (ssh-handle-userauth ssh payload plen))
    (when (eq msg-type 90)
      (let ((ctype-len (ssh-get-u32 payload 1)))
        (let ((cli-chan (ssh-get-u32 payload (+ 5 ctype-len))))
          (setf (mem-ref (+ ssh #x18) :u32) cli-chan)
          (setf (mem-ref (+ ssh #x14) :u32) 0)
          (ssh-send-channel-confirm ssh cli-chan 0))))
    (when (eq msg-type 98)
      (let ((rtype-len (ssh-get-u32 payload 5)))
        (let ((want-reply (aref payload (+ 9 rtype-len))))
          (when (not (zerop want-reply))
            (ssh-send-channel-success ssh
             (mem-ref (+ ssh #x18) :u32)))
          ;; "shell" → send prompt
          (when (eq rtype-len 5)
            (when (eq (aref payload 9) 115)
              (ssh-send-prompt ssh)))
          ;; "exec" → execute command
          (when (eq rtype-len 4)
            (when (eq (aref payload 9) 101)
              (let ((cmd-off (+ 10 rtype-len)))
                (let ((cmd-len (ssh-get-u32 payload cmd-off)))
                  (let ((cmd (make-array cmd-len)))
                    (dotimes (i cmd-len)
                      (aset cmd i (aref payload (+ cmd-off 4 i))))
                    (ssh-eval-line ssh cmd cmd-len)
                    ;; Send EOF + CLOSE after exec
                    (let ((cli-chan (mem-ref (+ ssh #x18) :u32)))
                      (let ((eof-msg (make-array 5)))
                        (aset eof-msg 0 96)
                        (ssh-put-u32 eof-msg 1 cli-chan)
                        (ssh-send-payload ssh eof-msg 5))
                      (let ((close-msg (make-array 5)))
                        (aset close-msg 0 97)
                        (ssh-put-u32 close-msg 1 cli-chan)
                        (ssh-send-payload ssh close-msg 5)))
                    (setf (mem-ref flag-addr :u32) 0)))))))))
    (when (eq msg-type 94)
      (ssh-handle-channel-data ssh payload plen))
    (when (eq msg-type 97)
      (setf (mem-ref flag-addr :u32) 0))
    (when (eq msg-type 1)
      (setf (mem-ref flag-addr :u32) 0))))

;; Message loop - polls until client disconnects
(defun ssh-message-loop (ssh)
  (let ((flag-addr (+ (conn-ssh 3) #x700)))
    (setf (mem-ref flag-addr :u32) 1)
    (loop
      (when (zerop (mem-ref flag-addr :u32)) (return ()))
      (let ((pkt (ssh-receive-packet ssh 50000)))
        (when pkt
          (ssh-dispatch-msg ssh (car pkt) (cdr pkt) flag-addr))))))

;; Override net-wait-ack: deliver piggybacked data
(defun net-wait-ack (conn)
  (let ((cb (conn-base conn))
        (acked 0)
        (tries 0))
    (loop
      (when (not (zerop acked)) (return 1))
      (when (> tries 500) (return 0))
      (io-delay)
      (let ((pkt-len (e1000-receive)))
        (when (not (zerop pkt-len))
          (let ((b2 (e1000-rx-buf)))
            (when (eq (mem-ref (+ b2 12) :u8) #x08)
              (when (eq (mem-ref (+ b2 13) :u8) 0)
                (when (eq (mem-ref (+ b2 23) :u8) 6)
                  (let ((f2 (mem-ref (+ b2 47) :u8)))
                    (when (eq (logand f2 #x10) #x10)
                      (setf (mem-ref cb :u32) 2)
                      (setq acked 1)
                      (net-deliver-data conn b2 pkt-len f2)))))))))
      (setq tries (+ tries 1)))))

;; Override net-accept-connection: run handler directly
(defun net-accept-connection (src-ip src-port dst-port buf)
  (let ((conn (conn-alloc)))
    (when (not (= conn (- 0 1)))
      (conn-init conn dst-port src-port src-ip)
      (setf (mem-ref (+ (conn-base conn) #x1C) :u32) 0)
      (when (eq dst-port 80)
        (setf (mem-ref (+ (conn-base conn) #x1C) :u32) 1))
      (let ((their-seq (buf-read-u32-mem buf 38)))
        (setf (mem-ref (+ (conn-base conn) #x014) :u32) (+ their-seq 1)))
      ;; Init recv buffer BEFORE net-wait-ack
      (let ((ssh (conn-ssh conn)))
        (setf (mem-ref (+ ssh #x6D4) :u32) 0))
      (tcp-send-segment-conn (conn-base conn) 18 (make-array 0) 0)
      (net-wait-ack conn)
      (when (eq (mem-ref (conn-base conn) :u32) 2)
        (if (eq (mem-ref (+ (conn-base conn) #x1C) :u32) 1)
            (http-connection-handler conn)
            (progn
              (ssh-copy-host-key conn)
              (let ((ssh (conn-ssh conn)))
                (setf (mem-ref ssh :u32) 0)
                (setf (mem-ref (+ ssh #x04) :u32) 0)
                (setf (mem-ref (+ ssh #x08) :u32) 0)
                (setf (mem-ref (+ ssh #x0C) :u32) 0)
                (setf (mem-ref (+ ssh #x10) :u32) 0)
                (setf (mem-ref (+ ssh #x28) :u32) 0)
                (setf (mem-ref (+ ssh #x150) :u32) 0)
                (setf (mem-ref (+ ssh #x154) :u32) 0)
                (setf (mem-ref (+ ssh #x2C) :u32)
                      (+ src-port (* src-ip 7))))
              (setf (mem-ref (+ (ssh-ipc-base) #x60448) :u32) conn)
              (ssh-connection-handler conn)))))))
